### ISSUE TITLE
Automated script tasks name not showing in History tab

### ISSUE THREAD

**Issue by subzdev** [amidaware/tacticalrmm#1000]
1. Create an automation policy.
2. Add a script to the tasks tab
3. Add automation policy to agent
4. Go to Tasks tab for agent and Run task
5. Script/Command column not filled out with the name of the script ran

**Comment by silversword411** [comment]
Can you include screenshot of this happening?

**Comment by subzdev** [comment]
https://discord.com/channels/736478043522072608/744282073870630912/948758014565941359

**Comment by silversword411** [comment]
That shouldn't have taken that long. It only happens when task is the scheduled one run by system. 

![2022-03-16_171240 - firefox_Tactical_RMM_—_Mozilla_Firefox](https://user-images.githubusercontent.com/13395348/158692395-81cebe67-dcbc-4cc9-9a29-943b17834585.png)

**Comment by sadnub** [comment]
I just pushed a fix for this. Will be in the next release
