### ISSUE TITLE
Script run window stays spinning forever even when terminated

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1006]
I have scripts, when triggering that just stay with spinning forever. 

![2022-03-16_142529 - firefox_Tactical_RMM_—_Mozilla_Firefox](https://user-images.githubusercontent.com/13395348/158661104-8188e361-71cd-48ef-8051-7c565f58b5d8.png)

When I check history I see it ran/timed out/something. 

![2022-03-16_142503 - firefox_Tactical_RMM_—_Mozilla_Firefox](https://user-images.githubusercontent.com/13395348/158661145-e26e0711-b302-4e14-904d-e9ea7abf5fa0.png)

What can I do for troubleshooting this better?

**Comment by bc24fl** [comment]
I send my long scripts to email because the browser will naturally timeout but the agent shouldn't..

**Comment by silversword411** [comment]
Going to close, browser max script time is 5mins, will monitor
