### ISSUE TITLE
Feature Request - Date/Time Format

### ISSUE THREAD

**Issue by daygle** [amidaware/tacticalrmm#1007]
**Is your feature request related to a problem? Please describe.**
Ability to specify date/time format - for example 17 Mar 2022 06:00.

**Describe the solution you'd like**
A configuration setting to allow users to specify a date format.

**Describe alternatives you've considered**
No alternative, use current format.

**Comment by silversword411** [comment]
Where are you talking about? Screenshots welcome

**Comment by daygle** [comment]
Screenshot as requested:-

![image](https://user-images.githubusercontent.com/5925233/158700163-98876020-df17-4826-8cbc-994a045e46a9.png)

**Comment by silversword411** [comment]
So non-american aka logical date formats ;)

Sounds like a good add to the user preferences panel

**Comment by daygle** [comment]
Haha yup, sorry I am an Aussie. We like it formatted a little different here lol.

I am sure this would benefit many other users.

**Comment by sadnub** [comment]
This will be in the next release. Thanks!
