### ISSUE TITLE
Set mesh host port for chat connections

### ISSUE THREAD

**Issue by ninjamonkey198206** [amidaware/tacticalrmm#1009]
**Is your feature request related to a problem? Please describe.**
If using Tactical behind a reverse proxy such as HAProxy, the function to open a chat window to a client PC automatically appends the configured external port prior to the proxy, causing the connection to fail until the port is removed from the url or corrected.

I've tested everything else via mesh that I could think of and this seems to be the only function affected.

**Describe the solution you'd like**
An option to view, edit, and save the base URL used for the chat function would solve this issue.

**Comment by dinger1986** [comment]
Hello, this is a mesh issue, suggested to open a bug report with them.

**Comment by ninjamonkey198206** [comment]
Ah, ok.
I didn't know if it was info passed to mesh from tactical or not.
I'll send it their way.

**Comment by dinger1986** [comment]
Ah ok, I get you, leave it open here just incase one fit he devs thinks it could be tactical adding the port.

**Comment by ninjamonkey198206** [comment]
Yeah, I'll see if they have any ideas. I tried looking through the code here and it's like trying to read ancient Greek. Way out of my wheelhouse.

**Comment by ninjamonkey198206** [comment]
https://github.com/Ylianst/MeshCentral/issues/1046
After a lot of digging, I think this may solve the issue for HAProxy. Going to give it a test run. Looks like a second matching rule is needed.

**Comment by ninjamonkey198206** [comment]
Not yet, anyway. Looks like I need to be able to try setting the "AliasPort" setting in the meshcentral config.json, but that gets wiped each time the docker stack is brought down/up.

**Comment by ninjamonkey198206** [comment]
@dinger1986 Looks like this can't be addressed on docker installs without overriding the automatic config of the meshcentral config.json either via a docker env variable or direct manipulation of the file, which isn't currently an option.

**Comment by ninjamonkey198206** [comment]
Or an override of some sort for the link creation for the agent side. That's the only one affected.

**Comment by ninjamonkey198206** [comment]
As an example:

T-RMM proxy is configured to use port 4443 currently by default for the internal port in the docker compose file.

If using a reverse proxy such as HAProxy in front of it, it's likely not a good option to use 443 for the exposed port of the T-RMM proxy, so passing through 4443 would probably be typical.

HAProxy catches the default 443 and reroutes to port 4443, however, the links created for the agent side of a chat window include port 4443 in the URL.

The mesh guys fought with this a bit, and came up with a workaround, but I think the T-RMM proxy port may be being added into the agent URL.

Might be able to resolve that with another rule in HAProxy and an alias in the mesh config, but I can't test that currently.

**Comment by ninjamonkey198206** [comment]
I'm leaning towards it being a T-RMM thing because the tech side window doesn't include the 4443 port.

**Comment by ninjamonkey198206** [comment]
https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf
Section 15

Yep, AliasPort would likely solve the issue.

**Comment by ninjamonkey198206** [comment]
Updating the meshcentral entrypoint.sh file to this should solve it. 
```text
#!/usr/bin/env bash

set -e

: "${MESH_USER:=meshcentral}"
: "${MESH_PASS:=meshcentralpass}"
: "${MESH_ALIAS_PORT:=4443}"
: "${MONGODB_USER:=mongouser}"
: "${MONGODB_PASSWORD:=mongopass}"
: "${MONGODB_HOST:=tactical-mongodb}"
: "${MONGODB_PORT:=27017}"
: "${NGINX_HOST_IP:=172.20.0.20}"
: "${NGINX_HOST_PORT:=4443}"
: "${MESH_PERSISTENT_CONFIG:=0}"
: "${WS_MASK_OVERRIDE:=0}"
: "${SMTP_HOST:=smtp.example.com}"
: "${SMTP_PORT:=587}"
: "${SMTP_FROM:=mesh@example.com}"
: "${SMTP_USER:=mesh@example.com}"
: "${SMTP_PASS:=mesh-smtp-pass}"
: "${SMTP_TLS:=false}"

if [ ! -f "/home/node/app/meshcentral-data/config.json" ] || [[ "${MESH_PERSISTENT_CONFIG}" -eq 0 ]]; then

  encoded_uri=$(node -p "encodeURI('mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}')")

  mesh_config="$(cat << EOF
{
  "settings": {
    "mongodb": "${encoded_uri}",
    "Cert": "${MESH_HOST}",
    "TLSOffload": "${NGINX_HOST_IP}",
    "RedirPort": 8080,
    "WANonly": true,
    "Minify": 1,
    "Port": 4443,
    "AgentPort": 443,
	"AliasPort": "${MESH_ALIAS_PORT}",
    "AllowLoginToken": true,
    "AllowFraming": true,
    "_AgentPing": 60,
    "AgentPong": 300,
    "AllowHighQualityDesktop": true,
    "agentCoreDump": false,
    "Compression": true,
    "WsCompression": true,
    "AgentWsCompression": true,
    "MaxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 30
    }
  },
  "domains": {
    "": {
      "Title": "Tactical RMM",
      "Title2": "TacticalRMM",
      "NewAccounts": false,
      "mstsc": true,
      "GeoLocation": true,
      "CertUrl": "https://${NGINX_HOST_IP}:${NGINX_HOST_PORT}",
      "agentConfig": [ "webSocketMaskOverride=${WS_MASK_OVERRIDE}" ]
    }
  },
  "smtp": {
    "host": "${SMTP_HOST}",
    "port": ${SMTP_PORT},
    "from": "${SMTP_FROM}",
    "user": "${SMTP_USER}",
    "pass": "${SMTP_PASS}",
    "tls": ${SMTP_TLS}
  }
}
EOF
)"

  echo "${mesh_config}" > /home/node/app/meshcentral-data/config.json

else
  # replace persistent mesh configuration with new ports
  sed -i 's/"Port": 443/"Port": 4443/' /home/node/app/meshcentral-data/config.json
  sed -i 's/"RedirPort": 80/"RedirPort": 8080/' /home/node/app/meshcentral-data/config.json
  sed -i "s/\"CertUrl\": \".*\"/\"CertUrl\": \"https:\/\/${NGINX_HOST_IP}:${NGINX_HOST_PORT}\"/" /home/node/app/meshcentral-data/config.json

fi

node node_modules/meshcentral --createaccount ${MESH_USER} --pass ${MESH_PASS} --email example@example.com
node node_modules/meshcentral --adminaccount ${MESH_USER}

if [ ! -f "${TACTICAL_DIR}/tmp/mesh_token" ]; then
    mesh_token=$(node node_modules/meshcentral --logintokenkey)

    if [[ ${#mesh_token} -eq 160 ]]; then
      echo ${mesh_token} > /opt/tactical/tmp/mesh_token
    else
      echo "Failed to generate mesh token. Fix the error and restart the mesh container"
    fi
fi

# wait for nginx container
until (echo > /dev/tcp/"${NGINX_HOST_IP}"/${NGINX_HOST_PORT}) &> /dev/null; do
  echo "waiting for nginx to start..."
  sleep 5
done

# start mesh
node node_modules/meshcentral
```

@wh1te909 if you or someone else want to check this out and make sure I got it right. Never edited an entrypoint file before, but I am fairly familiar with bash scripting.

Changes are adding the env variable MESH_ALIAS_PORT with a default value that matches the standard port 4443, and the AliasPort config value in the config file output that uses the variable.

**Comment by sadnub** [comment]
Thanks for the heads up! I was able to resolve this issue in the docker install. This will be in the next release.
