### ISSUE TITLE
Script Named Wrong - TacticalRMM - Agent Rename

### ISSUE THREAD

**Issue by bionemesis** [amidaware/tacticalrmm#1011]
There are two instances of TacticalRMM - Agent Rename in the default scripts library and it appears the second one is supposed to be something for grabbing logs.

<img width="437" alt="CleanShot 2022-03-20 at 22 05 09@2x" src="https://user-images.githubusercontent.com/3002979/159203992-1e859274-5ae7-4e68-99f2-9b89fe6684e1.png">

**Comment by wh1te909** [comment]
thanks for the report, just pushed a fix to the script repo. you can run the following commands on your trmm server to apply the fix:
```bash
cd /opt/trmm-community-scripts/
git fetch && git pull
/rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py load_community_scripts
```
