### ISSUE TITLE
Additional SMS Alert Provider Option

### ISSUE THREAD

**Issue by asasin114** [amidaware/tacticalrmm#1014]
Would love to see Telnyx added as an SMS provider for SMS alerts. I asked for this implementation to be added to MeshCentral as I prefer Telnyx to Twilio and because it gives users more options to bring their own external services into Tactical.

Here's a link to the Telnyx API Messaging Documentation for reference: https://developers.telnyx.com/docs/api/v2/messaging/Messages

**Comment by wh1te909** [comment]
closing as now possible with webhooks
