### ISSUE TITLE
Docker docs

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1016]
Add to docs:

Clean install docker commands:

sudo docker-compose stop
(If TRMM is the only thing on this docker host you can use below commands)
sudo docker rm -f $(sudo docker ps -a -q)
sudo docker volume rm $(sudo docker volume ls -q)
sudo docker network prune

If you are running other things on the same host you will have to remove all the images and volumes manually. Once that is complete you can run sudo docker network prune to cleanup the networks no longer in use. (This will remove ALL docker networks no longer used, Not just TRMM networks)

Then following the guide TRMM will rebuild itself when you run
sudo docker-compose up -d (edited)

I botched a new install of the docker style and could not get it to come up due to a "Network" error untill i removed the docker networks and let them rebuild. The above removes all the existing docker containers and network and rebuilds it all. Might be helpful to others to ensure a clean start.

**Comment by ninjamonkey198206** [comment]
@silversword411 bump
Looking through old issues to see if any could be closed or resolved, found this

**Comment by silversword411** [comment]
Yeah, I think this was just for expanding docs, and a todo for those that wanted to try their hand at docs updating. 

You think what's up is enough? Docker now "unsupported" might just be able to forget

**Comment by ninjamonkey198206** [comment]
I mean, I have been meaning to add to them a bit, but we can probably get rid of the open issue.
