### ISSUE TITLE
Using Automation policies on non-windows agents cause checks to trigger 

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#1019]
TRMM v0.12.1

**Describe the bug**
When assigning an automation policy to a company, the checks for windows computers get applied to non-windows computers . The checks then turn red and which are false positives.

The checks in the screenshot below are inherited from the automation policy. They won't work because it's a linux agent.

There needs to be a way to use automation policies on multi-platform. It seems right now it's still single platform.

![image](https://user-images.githubusercontent.com/6364477/160042613-b61329a3-280a-46d4-9cdd-639685337207.png)

Please prioritize a mac agent before fixing this :)

**Comment by sadnub** [comment]
On the script used for the script checks, you need to set the supported platforms to just windows. That will tell the policies to not add that check to the linux agent.
