### ISSUE TITLE
Docker Install Failing - MeshCentral container not finalizing

### ISSUE THREAD

**Issue by Kuuchuu** [amidaware/tacticalrmm#1025]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser: Brave
 - RMM Version (as shown in top left of web UI): N/A - Latest

**Installation Method:**
  - [    ] Standard
  - [ X ] Docker

**Describe the bug**
When following the official install steps using Docker the MeshCentral container never finalizes, preventing setup from completing.
Log for MeshCentral container:
```
/entrypoint.sh: line 75: /home/node/app/meshcentral-data/config.json: Permission denied
/entrypoint.sh: line 75: /home/node/app/meshcentral-data/config.json: Permission denied
Installing archiver@4.0.2...
Installing node-rdpjs-2...
Installing mongodb@4.1.0...
Installing saslprep...
Installing nodemailer...
Installing otplib@10.2.3...
Resetting main indexes...
Resetting events indexes...
Resetting power events indexes...
Resetting server stats indexes...
Done.
Done.
waiting for nginx to start...
```
DNS records are working. All ports (80, 443, and 4222) are port forwarded properly. The docker-compose.yml is unmodified, only the .env was modified as stated in documentation. No other containers except for Portainer are set up on this server.

**To Reproduce**
1. Follow steps listed at [https://docs.tacticalrmm.com/install_docker/](https://docs.tacticalrmm.com/install_docker/)

**Comment by Kuuchuu** [comment]
I had the same error with the MeshCentral portion of the install on a completely different server at a different location.

**Comment by wh1te909** [comment]
please describe your environment in more detail. where is the vm running? in cloud, if so what provider? behind nat, if so what hypervisor?

standard and docker installs are tested before each release on hyper-v, esxi and proxmox behind NAT and on cloud providers Vultr, Digital Ocean, BuyVM and Hetzner. So must be something custom with your setup.

**Comment by Kuuchuu** [comment]
At this point I'm unsure what the MeshCentral issue was. I deleted the docker volumes and tried once again today and it got past that point.
