### ISSUE TITLE
I have my own Extended Code Sign Certificate

### ISSUE THREAD

**Issue by smartekIT** [amidaware/tacticalrmm#1027]
hi,
I have my own Extended code sign certificate, Can I use that to code sign agents?

**Comment by dinger1986** [comment]
In what context? If you have a cert you should be able to sign any executable

**Comment by smartekIT** [comment]
yes, I know, but for example meshcentral agent could adopt my certificate so any generated agent .exe will get signed. so with this project can we generate the agents then sign them then upload them back to the server, so when download happen it will be already code signed agents. ?

**Comment by smartekIT** [comment]
my understanding here that any agent in this project will be downloaded but not signed. unless we use your certificate process to let our server retrieve the agent singed at your servers. am i right?
so the question is, when we have our own certificate, how can we sign our server agents without having to reach to your servers or github to download a signed certificate from yours?

**Comment by dinger1986** [comment]
Sign the agent, upload it somewhere then use the powershell install (you will see where it grabs the executables from and replace those urls with your own) to install it on client computers.

That's how I would do it anyway

**Comment by smartekIT** [comment]
thanks, based on what you said we can't just adjust the files which work Using a deployment link agent . or even the Dynamically generated executable. the only option we have is powershell installation.

**Comment by silversword411** [comment]
Why are you trying to do your own code signing?

**Comment by smartekIT** [comment]
> Why are you trying to do your own code signing?

hi, simply because I already have my own certificate which I normally use with my other meshcentral.

**Comment by silversword411** [comment]
I don't see this being something that's going to be supported. Closing, can reopen if dev's want to re-visit
