### ISSUE TITLE
user perminssions, agent count and alerts listed for all sites and not only the ones the user has rights to

### ISSUE THREAD

**Issue by CrazyMacX** [amidaware/tacticalrmm#1028]
**Is your feature request related to a problem? Please describe.**
User permission to sites, the user still see all the agents in agents count and the user see alerts from all sites not only the ones they have permission to. In the top right corner.

**Describe the solution you'd like**
Make User only see alerts and sites count they have permission to. 

**Describe alternatives you've considered**
Just a suggestion :)

**Additional context**

**Comment by silversword411** [comment]
I haven't tested notifications, but agent counts in TRMM only show when you've granted permissions to clients/sites for a user. Are you sure you have the permissions set correctly?

**Comment by CrazyMacX** [comment]
You are right, my mistake about the alerts. That is possible to disable. What aboute the agent count, i mean if a user only has access to one site the agent count should show the number of agents that user has rights to manage.

**Comment by silversword411** [comment]
> What aboute the agent count,

What agent count, screenshot please.

**Comment by CrazyMacX** [comment]
Yeah, exactly. Its my english, sorry = )

**Comment by sadnub** [comment]
Nice catch! I just pushed a fix for this. Will be in the next release

**Comment by CrazyMacX** [comment]
Great! 😊

Mvh
//Marcus Andersson

AppIT AB
Skolgatan 31
831 45 Östersund
Sweden
Tel: +4663133171
mobil:+46705675465
mail: ***@***.******@***.***>
Web: www.appit.se<http://www.appit.se/>

Från: sadnub ***@***.***>
Skickat: den 16 april 2022 23:36
Till: amidaware/tacticalrmm ***@***.***>
Kopia: Marcus Andersson ***@***.***>; Author ***@***.***>
Ämne: Re: [amidaware/tacticalrmm] user perminssions, agent count and alerts listed for all sites and not only the ones the user has rights to (Issue #1028)


Nice catch! I just pushed a fix for this. Will be in the next release
