### ISSUE TITLE
Change MeshCentral URL

### ISSUE THREAD

**Issue by ccasalicchio** [amidaware/tacticalrmm#1029]
**Server Info:**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version: 0.12.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

How do I change the MeshCentral Url from the initial install? I can't find any related commands from here
https://docs.tacticalrmm.com/management_cmds/

**Expected behavior**
Initially I used the URL remote.mydomain.com but wanted to use remotermm.mydomain.com

**Comment by dinger1986** [comment]
you cant unfortunately, you need to reinstall

**Comment by ccasalicchio** [comment]
If I reinstall, won't I lose everything?

**Comment by dinger1986** [comment]
yes, how many agents do you have?

**Comment by ccasalicchio** [comment]
Not many, but didn't want to lose everything. :( 

Can it be changed manually in the Mesh and RMM configs ?

**Comment by dinger1986** [comment]
Im wondering if there could be another way to do it, but it might also break it and end up with a reinstall. also depends how comfortable you are with linux. Are you on discord?

**Comment by ccasalicchio** [comment]
I'm very comfortable with linux and configuring things. I can at least try. Do you have instructions? I'll join the discord and ping you

**Comment by dinger1986** [comment]
Cool catch you there.

But basically thinking you should be able to change the url in nginx, meshcentral config and then relink tactical

**Comment by dinger1986** [comment]
this didnt work, reinstall was done
