### ISSUE TITLE
Patch management - windows update Script timed out after 25000 seconds - windows not up to date

### ISSUE THREAD

**Issue by EnergieZ** [amidaware/tacticalrmm#1032]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome
 - RMM Version v0.12.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: v0.12.1
- Agent OS: Windows 10 Pro, 64 bit v21H2 (build 19044.1526) • Agent v2.0.1

**Describe the bug**

In the Automation Manager, I have create a task to update windows every day. 
I approve all updates : 
![image](https://user-images.githubusercontent.com/1869463/160563706-03523019-870d-4ba8-9ab4-acc18775ee25.png)

in the task, I have this : 
![image](https://user-images.githubusercontent.com/1869463/160563908-358c756d-97a4-45fa-b435-881edb686651.png)

but none off my client are up to date : 
![image](https://user-images.githubusercontent.com/1869463/160564082-00376170-8966-4e01-8300-8d1d376d7f34.png)

In history tab of a client, I can see that win 10 upgrade is launch ; 
![image](https://user-images.githubusercontent.com/1869463/160564406-ac19f731-6728-4633-993d-29840ca81e80.png)

Most of the time, output is timed out : 
![image](https://user-images.githubusercontent.com/1869463/160564501-92cd34d6-3648-4a78-a9e0-4c26bfa098e5.png)

and to day had this error : 
![image](https://user-images.githubusercontent.com/1869463/160564609-162d9018-bc65-4e69-b04e-ae5e206de70f.png)

first time I see this error.

NB : if I manually accept updates (right click, then approve on each patch of each client), update are installed. 

**Expected behavior**
Windows update should be auto accepted, and installed. 

How can I have this to work ? 

Best regards.

**Comment by sevenGroupFrance** [comment]
Any idea ?
