### ISSUE TITLE
Getting "Network Error" When trying to sign in

### ISSUE THREAD

**Issue by estoat** [amidaware/tacticalrmm#1038]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox
 - RMM Version" 0.10.5:

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: v1.7.2
- Agent OS: Windows 10

**Describe the bug**
When I try to sign in from a device not on my network I get "Network error" After hitting the login button. However I can sign in when using my internal network.

**To Reproduce**
1. Go to the login page
2. Try to login
3.  See error

**Expected behavior**
I would normally expect to sign in

**Screenshots**
![image](https://user-images.githubusercontent.com/64144455/161020734-299a1e4a-4381-428a-958d-a9802fb4a4e4.png)

**Comment by estoat** [comment]
> 

Yes I am using Nginx Proxy Pass, I am using 3, rmm, mesh and api. An example of them is below
server {

server_name mesh.mydomain;



location / {
proxy_pass http://192.168.0.46;
proxy_set_header Host $host;
}



listen 80;

}




server{
server_name mesh.mydomain;



location / {
proxy_pass https://192.168.0.46;
proxy_set_header Host $host;
}
listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/rmm.ostfray.cyou/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rmm.ostfray.cyou/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

**Comment by dinger1986** [comment]
ok, if it works internally but not externally through the proxy theres something wrong with your proxy config, this isnt supported configs, you can possibly get assistance on #unsupported on discord but closing on here
