### ISSUE TITLE
Help info for chocolatey install script gives incorrect parameter name

### ISSUE THREAD

**Issue by OWA-dbell** [amidaware/tacticalrmm#1046]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.12.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.0.1
- Agent OS: Server 2016

**Describe the bug**
When attempting to run the chocolatey install script, hovering over the i on the right gives an incorrect parameter name. It shows as "update" when it should be "upgrade"

**To Reproduce**
1. Right click on an agent
2. Select **Run Script**
3. Select the **Chocolatey - Install, Uninstall and Upgrade Software** script.
4. Hover over the **i** on the right.

**Expected behavior**
Should read [-mode {(install) | **upgrade** | uninstall}]

**Screenshots**
attached
![2022-04-03 01_01_35-Window](https://user-images.githubusercontent.com/66913584/161414247-2d056ce5-c0a0-4b1b-a888-b673135055f5.png)

**Comment by silversword411** [comment]
Fixed, thanks!
https://github.com/amidaware/community-scripts/commit/d87c15ab5c5c6f61116e7c621e989f9ded661d78

**Comment by silversword411** [comment]
You can do an `upgrade --force` to see the change
