### ISSUE TITLE
Many agents does not upgrade

### ISSUE THREAD

**Issue by guillaumebottollier** [amidaware/tacticalrmm#1047]
**Server Info (please complete the following information):**
 - OS: [ Debian 10]
 - Browser: [Any]
 - RMM Version (as shown in top left of web UI): 0.11.3

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): various (1.6.2, 1.7.0. 1.7.1)
- Agent OS: [windows10]

**Describe the bug**
Agents auto-update does not work on dozens of machines, what can i do ?
Task is endlessly re-scheduled, but never succeed, cf screenshot.
Thanks for you help

**Screenshots**
![image](https://user-images.githubusercontent.com/84961534/161509811-6680613e-665b-4942-9b82-7265e4567f36.png)
**Additional context**

**Comment by dinger1986** [comment]
manually update them, they are too far out of date.

use mesh background

```
if not exist C:\TEMP\TRMM md C:\TEMP\TRMM
powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted
powershell Add-MpPreference -ExclusionPath C:\TEMP\TRMM
powershell Add-MpPreference -ExclusionPath 'C:\Program Files\TacticalAgent\*'
powershell Add-MpPreference -ExclusionPath 'C:\Windows\Temp\winagent-v*.exe'
powershell Add-MpPreference -ExclusionPath 'C:\Program Files\Mesh Agent\*'
cd c:\temp\trmm
powershell Invoke-WebRequest "https://github.com/amidaware/rmmagent/releases/download/v2.0.1/winagent-v2.0.1.exe" -Outfile tactical.exe
tactical.exe /VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS
powershell Remove-MpPreference -ExclusionPath C:\TEMP\TRMM
```

**Comment by guillaumebottollier** [comment]
Thank you @dinger1986, this is working.
Any possibility to run it on multiple agents ?
Or at least, if i run this on all machines, and the agent is already up to date, will it break it ?

**Comment by dinger1986** [comment]
I wouldn't run it via tactical.

There is a script scheduler plugin for mesh you can setup, that would maybe be more efficient

**Comment by guillaumebottollier** [comment]
i can run it via GPO or intune script, question is, will this break an agent already up to date (i've run a test, and it seems not but i want to be sure..)

**Comment by dinger1986** [comment]
So I would do a check to see is NSSM is in place still, if it is then it's not on v2.0.0 if it is then it isn't.

If you need a hand with that let me know.

**Comment by wh1te909** [comment]
it will not break on anything already up to date, don't worry
while those agents are pretty old, they will still auto update from 1.6.2. in fact any agents newer than 1.3.0 will still auto update.
if they're not updating it's because your AV is preventing the updater from running
