### ISSUE TITLE
Postgres SSL mode for NATS should be configurable by the user

### ISSUE THREAD

**Issue by joeldeteves** [amidaware/tacticalrmm#1049]
**Server Info (please complete the following information):**
 - Docker / K8s
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): 0.12.1

**Installation Method:**
  - [ ] Standard
  - [X ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.1
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Windows 10

**Describe the bug**
Currently, NATS is hard coded to have SSL mode disabled for the Postgres connection. However, for some cloud providers e.g. Digital Ocean, SSL is a hard requirement which means the connection results in the following error:

```time="2022-04-05T03:36:48Z" level=fatal msg="pq: no pg_hba.conf entry for host \"<postgres-db-server-ip>\", user \"tacticalrmm\", database \"tacticalrmm\", SSL off"```

The line of code in question is here: https://github.com/amidaware/tacticalrmm/blob/develop/natsapi/utils.go#L44

**To Reproduce**
1. Run TRMM in docker
2. Try to connect to a Postgres instance that has SSL mode enforced

**Expected behavior**
Postgres SSL mode should be configurable by the user. Specifically, in Docker there should be an extra environment variable added with the default value being off.

**Additional context**
As a consequence, NATS can't connect to the database and doesn't stay running so agents are unable to connect

**Comment by wh1te909** [comment]
done you can now add `DB_SSL = "require"` or whatever the right string is to `local_settings.py` then `python manage.py create_natsapi_conf` to regenerate the config. make sure you have the latest `nats-api` binary which I just compiled and pushed to develop branch. `nats-api -version` should show `3.0.2`

**Comment by joeldeteves** [comment]
Thank you for the quick fix!
