### ISSUE TITLE
Disk usage of Microsoft Storage Pool virtual disks is not reported

### ISSUE THREAD

**Issue by Iryna28** [amidaware/tacticalrmm#1050]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version : 0.12.2

**Installation Method:**
  - [ ] Standard
  - [x ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.0.2
- Agent OS: Windows 10 Pro, 64 bit v21H2 (build 22000.556) (reported by the summary tab, it is actually Win11)

**Describe the bug**
Disk usage is not shown when using Microsoft Storage Pools

**To Reproduce**
1. Set up Microsoft Storage Pool, like mirroring
2. Install TRMM agent and wait for the device to be added in the web UI

**Expected behavior**
The remaining space of virtual disk should be shown like a physical disk

**Screenshots**
![Capture d’écran 2022-04-06 083244](https://user-images.githubusercontent.com/25416019/161910541-2eb1ed28-aae8-4819-8864-da10383a769d.jpg)

**Additional context**
I tried to register a VM with a single disk in the Web UI, all works fine. So I think that the problem is tied to the Microsoft Storage Pools functionality.

Thank you for helping !

**Comment by silversword411** [comment]
Probably related to https://github.com/amidaware/tacticalrmm/issues/828

Should we close and merge @wh1te909 ?

**Comment by Iryna28** [comment]
Indeed, after closing Google Drive and refresh device in WebUI, all drives are shown.
Thank you !

**Comment by tom-hooper** [comment]
Is there any plan to fix this issue? i would like google drive so be available and have this feature operate.

**Comment by silversword411** [comment]
> Is there any plan to fix this issue

Hopefully and this is being tracked in the other issue, not this one
