### ISSUE TITLE
Unable to upload external MeshCentral agents:  external Mesh still supported?

### ISSUE THREAD

**Issue by fts-tmassey** [amidaware/tacticalrmm#1051]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Any
 - RMM Version: 0.12.2

**Installation Method:**
  - [X] Standard

**Describe the bug**
The ability to upload MeshCentral agents from an external MeshCentral server seems to be missing.

**To Reproduce**
Settings/Global Settings/MeshCentral
The upload buttons are missing
**Expected behavior**
I expect to see upload buttons

**Additional context**
I just upgraded from 0.11.3 to 0.12.2.  I tried to install an RMM agent using a pre-upgrade URL, which told me the token was expired (though the link shows that the date is still in the future).  So I created a new URL and used it.  This time it starts to install, but gives me the error "Unable to download the mesh agent from the RMM."  So I tried to upload fresh agents and found that the buttons are missing.

I then spun up a new VM and installed TRMM from scratch.  The initial setup wizard no longer asks for MeshCentral clients, and the Global Settings screen still doesn't have them! :)  I looked around as best I could and can't find that capability anywhere.  However, the doc still refers to this:  https://docs.tacticalrmm.com/mesh_integration/

A brief examination of the code history shows that this code was removed in the "0.12.0" commit, but I don't see any breakdown that might point to a smaller commit that might describe why.  Is external Mesh no longer supported?

**Comment by wh1te909** [comment]
you don't need to upload mesh agents anymore they are dynamically generated behind the scenes by calling meshcentral's websocket api. this will still work even if using an external mesh instance (doesn't matter where mesh is hosted) you just need to make sure the information in Settings > Global Settings > MeshCentral is correct, especially the new "Device Group Name" setting. you should change that to match the device group name in your external mesh instance. After doing that you can run the following command to make sure mesh integration is working properly:

```
/rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py check_mesh
```

**Comment by fts-tmassey** [comment]
Nice improvement, thank you!  However, I seem to be doing something wrong.

The MeshCentral server is unchanged, and worked correctly when TRMM was at 0.11.3.  With a brand-new 0.12.2, I've added the following to Global Settings/MESHCENTRAL:

Username:  TacticalRMM (Same as before)
Mesh Site:  <Correct https:// URL> (Same as before)
Mesh Token:  <Correct token> (Same as before, confirmed by running node node_modules/meshcentral --logintokenkey  on external MeshCentral) 
Mesh Device Group Name: TRMM Devices (Confirmed on external MeshCentral)

I've logged into the external MeshCentral using the above Username, and can see the "TRMM Devices" group just fine.  Verified that I can download a Mesh agent:  I can.

I created a new agent deployment URL, downloaded the new installer and ran it.  Same error:  "Unable to download the mesh agent from the RMM."

I'm not sure what I'm doing wrong, or what I should try next.  I would appreciate any suggestions you might have.

**Comment by fts-tmassey** [comment]
Sorry, output of that command:

Mesh site: [Correct[
Mesh username: TacticalRMM
Mesh token: [Correct]
Mesh device group: TRMM Devices
Auth token ok: [Redacted]
Mesh url ok: [Redacted]
/control.ashx?auth=[redacted]
Error getting mesh device id:
received 1005 (no status code [internal]); then sent 1005 (no status code [internal])

**Comment by fts-tmassey** [comment]
I don't see anyplace that I've mentioned this:  my MeshCentral is at 1.02, as currently expected by TRMM.

**Comment by silversword411** [comment]
Someone else recently mentioned Error 1005, they were using docker, another was using firefox?

https://github.com/amidaware/rmmagent/issues/5

Are we having this troubleshooting in more than one place? Troubleshooting is better done on discord. Since this ticket was about trying to upload a mesh agent when that's not how it's done anymore going to close this ticket
