### ISSUE TITLE
Agent AutoUpdate does not work

### ISSUE THREAD

**Issue by guillaumebottollier** [amidaware/tacticalrmm#1053]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: [all]
 - RMM Version (as shown in top left of web UI): 0.12.2

**Installation Method:**
  - [x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.8.0
- Agent OS: Win 10

**Describe the bug**
I am sorry to reopen a thread regarding the update of agent but i can't manage to understand why it does not work.
all the exclusions have been made on Windows defender and there are nothing on the protection history

`Add-MpPreference -ExclusionPath C:\TEMP\TRMM`
`Add-MpPreference -ExclusionPath C:\Program Files\TacticalAgent\*`
`Add-MpPreference -ExclusionPath C:\Windows\Temp\winagent-v*.exe`
`Add-MpPreference -ExclusionPath C:\Program Files\Mesh Agent\*`

Agent v2.02 is dowloaded on the computer, and the update is started but never complete, see log : 

![image](https://user-images.githubusercontent.com/84961534/162381104-020c71cd-4661-4928-9546-99ca97c2361f.png)

> time="2022-04-08T08:42:17+02:00" level=info msg="Agent updating from 1.8.0 to 2.0.2"
time="2022-04-08T08:42:17+02:00" level=info msg="Downloading agent update from https://agents.tacticalrmm.com/api/v1/winagents/?version=2.0.2&arch=64&token=xxxxxxxxxxxxxxxxxxxxxxxxxx"
time="2022-04-08T08:42:24+02:00" level=info msg="RPC service started"

Manual update work running an elevated powershell
`Start-Process -FilePath ".\winagent-v2.0.2.exe" -ArgumentList ('/VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS') -Wait`

Please help me troubleshoot this !

**Comment by NiceGuyIT** [comment]
Hey @guillaumebottollier, you might want to redact the deployment URL since it contains your token.

> https://agents.tacticalrmm.com/api/v1/winagents/?version=2.0.2&arch=64&token=REDACTED"

**Comment by guillaumebottollier** [comment]
> Hey @guillaumebottollier, you might want to redact the deployment URL since it contains your token.
> 
> > https://agents.tacticalrmm.com/api/v1/winagents/?version=2.0.2&arch=64&token=REDACTED"

Thanks !

**Comment by silversword411** [comment]
Please use discord for troubleshooting your specific issue. Github issues is for bugs to fix, and enhancement requests.
