### ISSUE TITLE
No Login Fields

### ISSUE THREAD

**Issue by vaughngx4** [amidaware/tacticalrmm#1062]
**Server Info
 - OS: Alma Linux 8.4, Docker version 20.10.14
 - Browser: FireDragon, Vivaldi(Chromium), Firefox ESR
 - RMM Version (as shown in top left of web UI): v0.12.4

**Installation Method:**
  - [ ] Standard
  - [x] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.0.2
- Agent OS: Win 10 v2004

**Describe the bug**
Tactical RMM login page has no input fields. Greeted by "TacticalRMM" heading and a login button.

**To Reproduce**
1. Update from v0.12.2
2. Visit Tactical Web UI

**Expected behavior**
Fields should be shown to login.

**Screenshots**
![image](https://user-images.githubusercontent.com/72740493/163032038-217f1316-a11c-49cb-805c-7653f3455eab.png)

**Additional context**
Apologies if there is some configuration error on my end, I've attempted all I can aside from rolling back to v0.12.2.

**Comment by dinger1986** [comment]
Have you tried `update.sh --force`?

**Comment by vaughngx4** [comment]
> Have you tried `update.sh --force`?

This is a Docker install, is there something in the update script that I should know about in Docker?

Docker update shows to just download new docker-compose.yml

**Comment by dinger1986** [comment]
Ah sorry, I'll leave that to someone a bit more qualified

**Comment by vaughngx4** [comment]
> Ah sorry, I'll leave that to someone a bit more qualified

No worries.

However, I can confirm that rolling back to v0.12.2 fixes the issue.

**Comment by dinger1986** [comment]
That's good to know!

I'll ask on discord if any docker wizards can hit you up here.

**Comment by silversword411** [comment]
You followed this?
https://docs.tacticalrmm.com/update_docker/

Probably best to use discord for troubleshooting.

**Comment by vaughngx4** [comment]
> You followed this? https://docs.tacticalrmm.com/update_docker/
> 
> Probably best to use discord for troubleshooting.

Yes I did. Okay, thanks. Will drop by when I have some time.

**Comment by wh1te909** [comment]
related https://github.com/quasarframework/quasar/issues/13154

**Comment by daygle** [comment]
Same issue here...

**Comment by wh1te909** [comment]
I'll do a small release in a couple hours with a fix for this

**Comment by wh1te909** [comment]
I have reverted the latest stable docker version to `0.12.2` please change it in your `.env` file and downgrade if you have already updated

**Comment by daygle** [comment]
Not sure if this matters.

0.12.3 is working for me - only 0.12.4 has the issue.

**Comment by wh1te909** [comment]
0.12.4. is working now, you can change back to `latest`

**Comment by ninjamonkey198206** [comment]
@wh1te909 , I just updated a Docker install using the latest tag and it's not showing a login.
![Screenshot 2022-04-13 175935](https://user-images.githubusercontent.com/24654529/163283460-9944f05b-c9fd-4a0a-95c6-98bb42135831.png)
Looks like the same error as your image above.

**Comment by wh1te909** [comment]
@ninjamonkey198206 with devtools open, right click on the refresh button in chrome > Empty Cache and Hard Reload

**Comment by daygle** [comment]
0.12.4 is working for me know.

Thanks for your work on this one :)

**Comment by ninjamonkey198206** [comment]
@wh1te909 I'll give that a shot after I bump back up to 0.12.4

I rolled back to 0.12.2 after posting my comment and screencap.

**Comment by vaughngx4** [comment]
> 0.12.4. is working now, you can change back to `latest`

Can confirm login page is working again. Thanks!

**Comment by vaughngx4** [comment]
> @wh1te909 , I just updated a Docker install using the latest tag and it's not showing a login. ![Screenshot 2022-04-13 175935](https://user-images.githubusercontent.com/24654529/163283460-9944f05b-c9fd-4a0a-95c6-98bb42135831.png) Looks like the same error as your image above.

If you have been using the latest tag since install you may need to remove existing images before doing a docker pull. You can do this quickly using:
```
docker rmi $(docker images | grep -o 'tactical-[a-z]*')
docker rmi tactical
```

**Comment by ninjamonkey198206** [comment]
@vaughngx4 I always purge old images and unused volumes after updates, and check to ensure the current images are in use. Just part of the update process for me.

Just finished the update, will test.

**Comment by ninjamonkey198206** [comment]
No joy. Still showing the same error. Completely wiped browser cache for giggles, no change.
Verified new images in use, unused volumes removed. Checked docker-compose file, good.

Edit: Figured it out. Had to completely kill off the old containers and images, leaving the named volumes in place, then re-pull the new images and start it all up again.

**Comment by silversword411** [comment]
> Had to completely kill off the old containers and new images, leaving the named volumes in place, then re-pull the new images and start it all up again.

As a Docker noob, isn't that what you always have to do for updating docker?

**Comment by vaughngx4** [comment]
> > Had to completely kill off the old containers and new images, leaving the named volumes in place, then re-pull the new images and start it all up again.
> 
> As a Docker noob, isn't that what you always have to do for updating docker?

Yes. For anyone interested, here is my update script and unattended certificate update(certificates are handled elsewhere and copied to the server via scp).

update.sh
```
#!/bin/bash
mv docker-compose.yml docker-compose.yml.old
wget https://raw.githubusercontent.com/amidaware/tacticalrmm/master/docker/docker-compose.yml
## Make custom changes to yaml here (I have ports changed)
echo "[BRINGING TACTICAL DOWN...]"
docker-compose down
echo "[REMOVING OLD IMAGES...]"
docker rmi $(docker images | grep -o 'tactical-[a-z]*')
docker rmi tactical
echo "[PULLING NEW IMAGES...]"
cp .env.master .env
docker-compose pull
rm -f .env
echo "[BRINGING TACTICAL UP...]"
./certs.sh
```

certs.sh
```
#!/bin/bash
cp .env.master .env
echo "[UPDATING TACTICAL CERTIFICATES]"
docker-compose down
echo "CERT_PUB_KEY=$(base64 -w 0 ./tactical.fullchain)" >> .env
echo "CERT_PRIV_KEY=$(base64 -w 0 ./tactical.key)" >> .env
docker-compose up -d --remove-orphans
rm -f .env
```

Where .env.master is simply .env without certificates.

**Comment by ninjamonkey198206** [comment]
> 

Sort of.

I should probably clarify.

Docker-compose down brought things down, but that didn't fix the issue.

I had to manually stop the containers, remove the containers, remove ALL images related to tactical, then bring it back up.

Docker-compose down, the usual step, wasn't enough.

**Comment by ninjamonkey198206** [comment]
In other words, I had to manually purge the containers, networks, and images for some reason.

**Comment by vaughngx4** [comment]
> In other words, I had to manually purge the containers, networks, and images for some reason.

It's because 0.12.4 was re-released. There was a buggy version and there is now a fixed version. The tag is the same which is why you had to delete the images(my script above does this regardless).

**Comment by vaughngx4** [comment]
> > 
> 
> Sort of.
> 
> I should probably clarify.
> 
> Docker-compose down brought things down, but that didn't fix the issue.
> 
> I had to manually stop the containers, remove the containers, remove ALL images related to tactical, then bring it back up.
> 
> Docker-compose down, the usual step, wasn't enough.

`docker-compose down` should remove containers and networks. I think your issues was simply the re-tagged image.
