### ISSUE TITLE
ParrotOS with systemd not working

### ISSUE THREAD

**Issue by 4o3Gone** [amidaware/tacticalrmm#1063]
**Server Info (please complete the following information):**
 - OS: ParrotOS 5.0 (Electro Ara)

**Installation Method:**
  - [ ] Standard

**Describe the bug**
ParrotOS with systemd not supported. Shows "Supported versions: Ubuntu 20.04, Debian 10 and 11. Your system does not appear to be supported"

**To Reproduce**
1. Git clone the repository
2. [chmod +x install.sh] in the tacticalrmm folder
3. run [./install.sh]
4. See the error

**Expected behavior**
The tool should install itself and run normally.

**Screenshot** 
![error](https://user-images.githubusercontent.com/99973111/163037314-3b0d5939-29ed-4eae-974a-bd046cc5b9fe.png)

**Comment by dinger1986** [comment]
eh, parrotos isnt ubuntu 20.04 or debian, what does it identify as?

**Comment by silversword411** [comment]
So is this trying to install TRMM server

Or TRMM agent. 

TRMM server is only supported on 3 OS versions: https://docs.tacticalrmm.com/install_server/#hardware-os

**Comment by wh1te909** [comment]
it's debian based, but we officially only support ubuntu or debian, not parrot os or any other distros that are debian based
