### ISSUE TITLE
Add --no-progress to choco as global setting

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1070]
**Is your feature request related to a problem? Please describe.**
Please add `--no-progress` for `choco` actions. Looking at the pending actions log, one action was to install `git`. The resulting log was roughly 1.2MB in size. 99% of this is the progress indicator.

**Describe the solution you'd like**
I would like `--no-progress` added globally to all `choco` actions or added as a switch in the global settings. This will reduce the verbosity of `choco` commands.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
This is mostly about managing the database size and less about viewing the output. The output is viewable although you need to use the scroll bar to jump to the bottom. If `choco` installs programs on many computers, the database size could grow needlessly large.

**Comment by sadnub** [comment]
This is a great request! I added --no-progress to the choco args. [a2f9b047a882c886445f50e10f3d59f1afdfe87c](https://github.com/amidaware/rmmagent/commit/a2f9b047a882c886445f50e10f3d59f1afdfe87c)

Should be in the next release
