### ISSUE TITLE
Tacticalrmm Network Error while trying to login locally.

### ISSUE THREAD

**Issue by taufiqshk** [amidaware/tacticalrmm#1072]
Hi, I have installed tacticalrmm successfully it is working fine but when I try to log in locally its shows a network error. while from my subdomain its working.

**Comment by wh1te909** [comment]
invalid issue

**Comment by silversword411** [comment]
@taufiqshk This sounds like troubleshooting your individual install. Connect with us on Discord. See https://docs.tacticalrmm.com/#discuss
