### ISSUE TITLE
Tacticalrmm agent service is not installing but mesh agent services installed and start services properly.

### ISSUE THREAD

**Issue by taufiqshk** [amidaware/tacticalrmm#1073]
![Untitled](https://user-images.githubusercontent.com/89904131/163762165-9cf19d20-4af6-4fa1-87b2-60c7bd2239be.png)

**Comment by wh1te909** [comment]
invalid. follow the issue template or if you need help or have questions, join discord. github issues are for bug reports and feature requests only
