### ISSUE TITLE
Kludge Windows display to show Win11

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1075]
Even though Microsoft calls Windows 11 Windows 10 v21H2 build 22000 we need to kludge Windows 11 because 10 isn't 11 but it is, but isn't. #ThanksM!cr0s0ft

**Comment by dinger1986** [comment]
(Get-ComputerInfo).OSName reports this accurately

**Comment by djsvi** [comment]
This is much faster than Get-ComputerInfo:  (gwmi Win32_OperatingSystem).Caption

Funnily enough the agent **already** collects the correct OS display name under Assets > Operating System > Caption
