### ISSUE TITLE
When first loading the dashboard, no agents are shown in the list

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/tacticalrmm#1092]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome
 - RMM Version (as shown in top left of web UI): v.0.13.1

**Installation Method:**
  - [ ] Standard
  - [x] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.0.3
- Agent OS: Windows 10 Pro, 64 bit v20H2

**Describe the bug**
When first loading the dashboard, no agents are shown in the list. When clicking on "Workstations", "Servers", "Mixed", "All Clients" or a client, this list refreshes correctly.

**To Reproduce**
1. Go to 'rmm.DOMAIN.EXTENSION'
4. See that no agents are showing

**Expected behavior**
A correct list of agents being displayed.

**Comment by silversword411** [comment]
Are you sure that it's not just the server only tab being selected by default...and you have no servers?

You also have preferences about this:
https://docs.tacticalrmm.com/tipsntricks/#customize-user-interface

**Comment by JoachimVeulemans** [comment]
Yes, I have the mixed tab as default in my preferences. That was not the behaviour in v.1.13.1.

**Comment by wh1te909** [comment]
thanks, this is a bug I was able to replicate. will work on a fix

**Comment by sadnub** [comment]
I just pushed a fix for this. Will be in the next release

**Comment by wh1te909** [comment]
Released in 0.13.2
