### ISSUE TITLE
PERSISTENT_MESH_CONFIG=1 Appends 80 Onto Mesh Central RedirPort Causing Bad Port Errors

### ISSUE THREAD

**Issue by mswdev** [amidaware/tacticalrmm#1093]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10] Amazon Linux 2
 - Browser: [e.g. chrome, safari] N/A
 - RMM Version (as shown in top left of web UI): v0.13.1

**Installation Method:**
  - [ ] Standard
  - [X] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.0.3
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] Windows 10 Pro

**Describe the bug**
When you set PERSISTENT_MESH_CONFIG=1 to 1 in the .env file it seems to append 80 each time the mesh central docker container is restarted to the end of the "RedirPort" in the config.json file containing the mesh central configuration settings.

The persistent config seems to be working except for the fact that 80 is appended to the "RedirPort" configuration option upon each restart of the mesh central server docker container

![image](https://user-images.githubusercontent.com/11341771/165004113-9a87d40e-ad78-4d0e-81b8-dde7d632afcf.png)

I have a temporary fix working now. After setting PERSISTENT_MESH_CONFIG=1 in the .env file modify the mesh central daya config.json file and change "RedirPort" to 80. Then change your SMTP settings and any other configuration settings needed.

Then you can restart the mesh central server docker container and the bug will append 80 onto the "RedirPort" leaving you with 8080 and everything will run properly.

However, the caveat being that if you restart the mesh central server docker container for any reason in the future it will append another 80 onto "RedirPort" and you will have to do this fix again until this bug is resolved.

**Expected behavior**
The `"RedirPort"` should not be moodified from the default port 8080 when `PERSISTENT_MESH_CONFIG=1` env value is set to 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/11341771/165004303-167a2566-962c-4807-9a5a-ccd139b97477.png)

**Additional context**
Issue seems to be located here: https://discord.com/channels/736478043522072608/744282073870630912/967948631833469028

**Comment by wh1te909** [comment]
Fixed in release 0.13.3
