### ISSUE TITLE
Possibility to move database externally [Docker] - Adding a new environment variable POSTGRES_HOST

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/tacticalrmm#1094]
**Is your feature request related to a problem? Please describe.**
I would like to have an external database while using the Docker setup. It is difficult to use the database in a Docker container, I would much rather add it to our general database. Maintenance & backups would be much simpler.

**Describe the solution you'd like**
The possibility to provide a new environment variable with the Postgres IP address. Right now, the user and password are already passed on the init container like so:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
I would like to see a new option:
      POSTGRES_HOST: ${POSTGRES_HOST}

**Describe alternatives you've considered**
Alternatives are keeping the database in Docker or moving to a traditional install.

**Comment by sadnub** [comment]
The tactical docker image already supports a POSTGRES_HOST variable. You can edit your docker-compose.yml file and pass it in as an environment variable to the tactical-init service.

You will need to edit the docker-compose.yml file to remove the tactical-postgres service. 

I plan on eventually generating the docker-compose.yml file dynamically to better handle situations where services are optional or need special images.

**Comment by JoachimVeulemans** [comment]
I have tested adding the POSTGRES_HOST variable and removing any references to postgres in the docker-compose.yml file. This is working perfectly.

It would be nice to mention the possibility to do this in the installation documentation for the Docker install.

Issue can be closed for me.
