### ISSUE TITLE
Different times being shown in Automation Manager

### ISSUE THREAD

**Issue by subzdev** [amidaware/tacticalrmm#1096]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Any
 - RMM Version (as shown in top left of web UI): 0.13.3

**Installation Method:**
  - [ x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Latest
- Agent OS: Windows 10

**Describe the bug**
When editing a task script from an automation policy, the time (not month/year date) is different than what it shows in the table. Looks like it is 7 hours off, so if a script is set to run at 5PM, it would show 10AM in the edit screen.

**To Reproduce**
1. Create a task script in an Automation policy
2. Edit that task script
3. Times will be different when compared to the task script table for the automation policy and when editing it

**Expected behavior**
Times should be consistent

**Comment by sadnub** [comment]
This will be fixed in the next release. Thanks!
