### ISSUE TITLE
Task Run does not show name in Script/Command column under History tab

### ISSUE THREAD

**Issue by subzdev** [amidaware/tacticalrmm#1097]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Any
 - RMM Version (as shown in top left of web UI): 0.13.3

**Installation Method:**
  - [ x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.0.3
- Agent OS: Windows 10

**Describe the bug**
In the History tab of an agent, when the action is a Task Run initiated by system, the Script/Command column is not populated with the script name or command ran.

**To Reproduce**
1. Create automation policy with a task script
2. Apply automation policy to agent
3. Let it run the task script

**Expected behavior**
Script/Command column should populate with the script name.

**Comment by silversword411** [comment]
I swear this was a previous issue, and was closed as fixed. You're talking this, for auto-scheduled items run as system being blank?

![2022-04-26_145706 - firefox_Tactical_RMM_—_Mozilla_Firefox](https://user-images.githubusercontent.com/13395348/165372507-f634e83b-ea94-46e6-90a7-fc4220396377.png)

**Comment by subzdev** [comment]
You are correct sir.

Original issue here: https://github.com/amidaware/tacticalrmm/issues/1000
