### ISSUE TITLE
Help Installer token has expired. Please generate a new one RMM

### ISSUE THREAD

**Issue by lpoiie** [amidaware/tacticalrmm#1099]
### Discussed in https://github.com/amidaware/tacticalrmm/discussions/1098

<div type='discussions-op-text'>

<sup>Originally posted by **lpoiie** April 26, 2022</sup>
Hello
I need help please
When I want install Tactical  RMM client on computer that message appear : Installer token has expired. Please generate a new one

How can resolve  this problem ?
Tanks for your help.
![278795992_2689139291219112_8632880254257473791_n](https://user-images.githubusercontent.com/104449614/165357074-2d994a17-4571-4145-a51d-aab454f71b88.jpg)
</div>

**Comment by silversword411** [comment]
Invalid issue
