### ISSUE TITLE
Reminder to push nats websocket support

### ISSUE THREAD

**Issue by ninjamonkey198206** [amidaware/tacticalrmm#1101]
**Is your feature request related to a problem? Please describe.**
Enabling nats websockets makes it play nice with proxies.

**Describe the solution you'd like**
@wh1te909 has it figured out.

**Describe alternatives you've considered**
Permanent indentation on my forehead earned while attempting TCP reverse proxy for nats

**Additional context**
Literally typing this up because @wh1te909 said he forgot and needed a reminder.

**Comment by ninjamonkey198206** [comment]
Leaving this open until you're sure all the links have been worked out?

**Comment by wh1te909** [comment]
nah forgot to close this one, thanks!
