### ISSUE TITLE
Quirks with clicking links in notifications

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1110]
**Server Info (please complete the following information):**
 - RMM Version (as shown in top left of web UI): 0.14.3

After clicking link in notification:
- You can't click another link in notification (without clicking the "back to dashboard top left"). Would be nice to be able to go from notification to notification
- Tasks for windows agents give "Only supported for Windows agents at this time"...but they're windows agents.

![2022-05-02_101847 - winagent from notification](https://user-images.githubusercontent.com/13395348/166249867-b78e39c5-67f3-49e3-83fe-9c848edd2843.png)

**Comment by wh1te909** [comment]
fixed the tabs in 4787be2db09b68b3f511bb8bb1301ae05cc7d549 still looking into why the link isn't working once already inside the new view
