### ISSUE TITLE
Downloading Linux Agent without Code Signing

### ISSUE THREAD

**Issue by truejp** [amidaware/tacticalrmm#1115]
**Server Info (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: vivaldi (chromium)
 - RMM Version 0.13.3

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: 2.0.3

**Describe the bug**
Whenever I try to download any linux agent over the top bar menu, I get a small red error notification in the top middle (Missing code signing token - 400: Bad Request). Since permanent links are just usable for windows, I am not able to get any deployment link at all. I have tried all combinations of server and architecture. 

**To Reproduce**
1. Go to dashboard
2. Click on Agents (top bar)
3. Click on Install Agent
4. Select any Linux based configuration, any Client/Site Combination, expiration, server/workstation....
5. Click on Download Linux Install Script
6. See the error

**Expected behavior**
I expected the linux install script to download just as the windows installer which works perfectly fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/80537345/166639892-909d8d9e-6a48-4671-9801-c717225ae554.png)

**Additional context**

**Comment by dinger1986** [comment]
That is expected behaviour.l please see below:

https://docs.tacticalrmm.com/faq/#linux-agent

If you check discussions or our discord this questions been answered afew times.

**Comment by wh1te909** [comment]
https://github.com/amidaware/tacticalrmm/discussions/1112
