### ISSUE TITLE
Custom Fields tab on agent info panel

### ISSUE THREAD

**Issue by troubleshootme** [amidaware/tacticalrmm#1119]
**Is your feature request related to a problem? Please describe.**
Would like to see custom field data without edit agent dialog

**Describe the solution you'd like**
A new tab on the agent dashboard info panel, possibly to the right of notes

**Describe alternatives you've considered**
Nothing that seems as great as the solution above.

**Additional context**

**Comment by Vedeneb** [comment]
I would love to see this as well. Also it would be great if specific custom fields could not only be displayed in a specific tab, but also directly in the agent list. E.g. if I have a custom field containing the clients IP Address I'd like to see it in a new column in the list of agents.

Actually that's what I thought the "Hide in Dashboard" switch is for, however that just shows it on the Edit Agent Dialog, not on the dashboard. Maybe that switch should be renamed.

**Comment by wh1te909** [comment]
this has just been added in release 0.15.9
