### ISSUE TITLE
Cannot login after setup : Error message banner "0:"

### ISSUE THREAD

**Issue by tekosnextgen** [amidaware/tacticalrmm#1136]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10] Debian 11
 - Browser: [e.g. chrome, safari] Firefox, Chrome, Safari
 - RMM Version (as shown in top left of web UI): Latest

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): NA
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] NA

**Describe the bug**
A clear and concise description of what the bug is : After the installer script finished the setup without any error, I try to login with the user created during setup and a red banner appears with the message '0:'  - Tried on different fresh Debian 11 install - Same issue

**Expected behavior**

**Screenshots**

**Additional context**
![CleanShot 2022-05-16 at 12 53 59](https://user-images.githubusercontent.com/9717145/168577730-1b061671-ab52-4d7b-ba09-ebacaaad8799.png)

**Comment by tekosnextgen** [comment]
As an additional info, I already tried to force an update with the command "./update.sh --force" - Again no issues reported but the login is still not working - I also tried to reset the user account with the command "/rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py reset_password <username>" - Same issue : 
Starting nats service
Starting nats-api service
Starting rmm service
Starting daphne service
Starting celery service
Starting celerybeat service
Starting nginx service
Updating meshcentral from 1.0.22 to 1.0.22

added 163 packages, and audited 164 packages in 7s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Update finished!
tactical@rmm:~$

**Comment by silversword411** [comment]
Are you getting the 2FA code as well? Check the clock, for TOTP to work, the clocks need to be correct

**Comment by wh1te909** [comment]
open browser console and paste screenshot of error

**Comment by silversword411** [comment]
Don't leave us in suspense, what was the problem?

**Comment by Upellift99** [comment]
Hello @tekosnextgen, have you checked that you have a valid SSL certificate? I got a similar issue after my Let's Encrypt certificate expired.

**Comment by wh1te909** [comment]
yea this error either means cert expired, or DNS issue (not resolving, not pointing to correct ip, NAT issues etc)

**Comment by tekosnextgen** [comment]
Hello,

Sorry for the delay, it was a stupid API DNS record issue.

**Comment by dinger1986** [comment]
> Hello,
> 
> Sorry for the delay, it was a stupid API DNS record issue.

its always dns :)

**Comment by iammrdivine** [comment]
Can you specify how you fixed the API DNS record issue? Im having similar issues.

**Comment by iammrdivine** [comment]
> Hello,
> 
> Sorry for the delay, it was a stupid API DNS record issue.

Can you specify how you fixed the API DNS record issue? Im having similar issues.

**Comment by silversword411** [comment]
Use troubleshooting to see what your current DNS status is between agent and server.

You have something not implemented right
 
https://docs.tacticalrmm.com/troubleshooting/#testing-network-connectivity-between-agent-and-server

**Comment by iammrdivine** [comment]
Its actually logging into the server for the first time since installing tactical rmm. Im getting the same 0 error at the login. I went through all the installation steps and all checked fine.

**Comment by silversword411** [comment]
Discord is the best way to troubleshoot.

I'm pretty sure you've deviated from the install instructions or made a mistake somewhere.

You can also email help@amidaware.com for paid support if that's preferred.

**Comment by iammrdivine** [comment]
Found out that it doesn't like being behind my NginX proxy manager. Have to figure that one out.

**Comment by wh1te909** [comment]
@iammrdivine the install script already installs nginx for you so you have nginx in front of nginx, doesn't make sense.
