### ISSUE TITLE
Cannot install on 1 core 1gb memory Oracle cloud VM

### ISSUE THREAD

**Issue by tamerlein** [amidaware/tacticalrmm#1141]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: NA
 - RMM Version (as shown in top left of web UI): NA
 - `install.sh` version 63

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): NA
- Agent OS: NA

**Describe the bug**
While installing on a 1 core 1gb AMD flexible VM on Oracle cloud, the `install.sh` script is stuck in this phase:

```
 App •  WAIT  • Compiling of "UI" in progress...

 • Compiling:
 └── UI ███                  10% building 0/1 entries 37/56 dependencies 2/28 modules
```

**To Reproduce**
- Oracle Cloud's always free VM. install using traditional install
- Tried higher tier VM (more memory and cpu) and installs with no issues

**Expected behavior**
**- Install manual says install works with < 1gb ram and 1 core if less than 200 agents. This needs to be amended potentially if installation script cannot run due to insufficient resources.**

**Screenshots**
![image](https://user-images.githubusercontent.com/50601508/168711684-5e8bf037-5fdd-493d-85d2-a166d83cc23b.png)

**Additional context**

**Comment by wh1te909** [comment]
Can you link to where it says 1GB ram? Can't find it in docs

**Comment by BenNottelling** [comment]
That's because it doesn't say that anywhere
![Screenshot_20220516-193543_Chrome.jpg](https://user-images.githubusercontent.com/17304943/168716781-15137758-fbb9-4d4b-bbbf-46891ccfd4a5.jpg)

**Comment by tamerlein** [comment]
mb. read that as 1 core, 1gb.

**Comment by wh1te909** [comment]
Thanks thought I was blind lol. Yea you need min 2gb. If you can't get a vm with more ram just create a swapfile and enable swap
