### ISSUE TITLE
Run script after patching

### ISSUE THREAD

**Issue by mrapoc** [amidaware/tacticalrmm#1143]
**Is your feature request related to a problem? Please describe.**
I'd specifically like to run a script after patching to prompt a reboot using a toast popup. It could open doors for other uses
**Describe the solution you'd like**
Option to run a script after patching is finished
**Describe alternatives you've considered**
Perhaps run the same script if a reboot required is detected. 
**Additional context**
n.a

**Comment by mrapoc** [comment]
I will personally use the burnt toast script by cyberdrain to ask for a reboot but allow snooze until convenient.
________________________________

**Comment by silversword411** [comment]
Ticket Consolidation: Combining into https://github.com/amidaware/tacticalrmm/issues/1188
