### ISSUE TITLE
Monitor/Script output/return information

### ISSUE THREAD

**Issue by mrinc** [amidaware/tacticalrmm#1144]
**Is your feature request related to a problem? Please describe.**
Not a problem, and I cannot find any docs on it, so if it doesn't exist - it will be a really awesome feature to make flexible scripts/monitors.

**Describe the solution you'd like**
When a monitor/script is run on a device, there should be some sort of way to return data back to Tactical.

**Describe alternatives you've considered**
N/A

**Additional context**
An example would be reading the output of the script and just parsing the response lines.

And example of this would be:  
```bash  
echo "##tactical[<messageName> 'value']"  
```  
```powershell  
Write-Host "##tactical[<messageName> 'value']"  
```

The use case could be as simple as reporting internet speed test information or latency to a server.  

/pings or does speed test to server/  
```bash  
echo "##tactical[SPEEDTEST_DOWN '10']"  
echo "##tactical[SPEEDTEST_UP '10']"  
echo "##tactical[SPEEDTEST_LAT '1']"  
```

That could then set variables/attributes on the device on tactical (https://docs.tacticalrmm.com/script_variables/) 
So create a variable in tactical of type writable (so the scripts/monitors) could output the information back to tactical - but other variables would not be able to overwrite them - also means minimal additional development.  

And if you have a monitor, could trigger based on when the variable goes out of spec.  

Datto does it with `NAME=VALUE` (https://rmm.datto.com/help/en/Content/4WEBPORTAL/Monitor/CustomComponentMonitor.htm)

**Comment by mrinc** [comment]
@silversword411 Got an example to set variables? since `Write-Output` just outputs data

**Comment by silversword411** [comment]
Maybe I'm not understanding what you're asking. 

If you want to return data from a powershell script use `Write-Output "Some text"`. If you want to output data from a script it's `Write-Output $variable` or `Write-Output "Variable: $variable"`

https://github.com/amidaware/community-scripts/blob/main/scripts/Win_Hardware_RAM_Status.ps1

![2022-05-18_103318 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/169067277-894ef0de-5dd6-47e1-8de8-fed58379ee15.png)

**Comment by silversword411** [comment]
Sometimes you need to escape...so it's `"Write-Output "Error with Code $($code)!"`

**Comment by mrinc** [comment]
@silversword411 Shot

Okay so the docs need to just be updated with some more info :) 

Awesome! 

Nice and simple like Datto sweet

**Comment by silversword411** [comment]
@mrinc Where did you look in the docs for that info, so I can put it there :)

**Comment by wh1te909** [comment]
use a collector task with custom fields, see https://docs.tacticalrmm.com/functions/custom_fields/ (video walkthru at bottom of page)
