### ISSUE TITLE
Limited User can See "Policy Overview" from all Clients/Sites

### ISSUE THREAD

**Issue by JSuenram** [amidaware/tacticalrmm#1145]
Limit User which should only manage a specific client can see to much information.
![image](https://user-images.githubusercontent.com/68963439/169229651-70f64890-1df7-460f-b430-c450183234e3.png)

It is not a security-issue but a lack of information which should not viewable for limited users/customers.
![image](https://user-images.githubusercontent.com/68963439/169229964-7a717d2e-0e11-4050-ba61-9fb28889d0f3.png)

**Comment by sadnub** [comment]
I just pushed a fix for this. Will be in the next release. Thanks!
