### ISSUE TITLE
Send Alarms via Matrix-Server

### ISSUE THREAD

**Issue by tommyknocker1077** [amidaware/tacticalrmm#1152]
Is it possible to use [Matrix](matrix.org) servers for alerting? 
This would be a nice alternative for those who use opensource software anyway and run their own matrix server like we do, to be informed about the server states.
Since Matrix has a [Rest-API](https://spec.matrix.org/latest/client-server-api/), this should be feasible.
But I have never dealt with APIs myself....

**Comment by wh1te909** [comment]
this is now possible in release 0.19.0 with alerting to webhooks
