### ISSUE TITLE
Share your TRMM Benchmarks

### ISSUE THREAD

**Issue by wh1te909** [amidaware/tacticalrmm#1158]
Share your [load testing benchmarks](https://docs.tacticalrmm.com/tuning_for_scale/) here

**Comment by xrsxj** [comment]
Requests      [total, rate, throughput]         2632, 526.29, 506.34
Duration      [total, attack, wait]             5.198s, 5.001s, 197.003ms
Latencies     [min, mean, 50, 90, 95, 99, max]  97.18ms, 193.547ms, 189.478ms, 244.337ms, 279.647ms, 364.857ms, 433.898ms
Bytes In      [total, mean]                     23688, 9.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      200:2632

20 core 64 gig ram 1tb ssd (e7-8870 v4) 
6 processes / 12 threads  (anything above 8 processes had higher rps but bad UI performance)
790 agents

**Comment by wh1te909** [comment]
no longer needed, uwsgi workers auto scale now based on load as of v0.14.0
