### ISSUE TITLE
Blank space at the bottom of the page

### ISSUE THREAD

**Issue by xrsxj** [amidaware/tacticalrmm#1159]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome and Edge
 - RMM Version (as shown in top left of web UI): 0.13.4

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
When viewing the UI a persistent "bar" of empty space is at the bottom of the screen.

**To Reproduce**
1. Open RMM

**Expected behavior**
Content should fill the full screen

**Screenshots**

**Additional context**
![Capture](https://user-images.githubusercontent.com/10294996/171321674-8351f54f-1c75-4aac-9902-82fe47df5c58.png)

**Comment by dinger1986** [comment]
What resolution are you running?

Daniel

**Comment by xrsxj** [comment]
2560 x 1440 and 1280 x 1440 (half screen spilt)

**Comment by dinger1986** [comment]
I'll let the devs comment, I'm running mine one 1920*1080 and works fine.

I would assume it's optimised for a resolution but not sure what one.

**Comment by xrsxj** [comment]
I don't use the half screen too often but even at full for 2560 x 1440 it
happens. You can see a hint of it at 1920 x 1080 but it's not obvious.

**Comment by silversword411** [comment]
Sorry, I was thinking something different. Actually...I see it at 1920 too...it's blank space on the client/site list. Don't think it affects the right pane

![2022-06-01_133941 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/171468564-4dfdecb5-a890-42da-b7d4-679c9b1098e8.png)

**Comment by xrsxj** [comment]
It hits both on my instance, you can test in the wmi data

**Comment by silversword411** [comment]
Fixed https://github.com/amidaware/tacticalrmm-web/commit/89966dd00681007f480ef3fea75358406aa1249a

**Comment by wh1te909** [comment]
released in 0.16.4
