### ISSUE TITLE
hardware monitoring

### ISSUE THREAD

**Issue by dwn419** [amidaware/tacticalrmm#1162]
I think it would be helpful to monitor the hardware to check servers raid controller or system fan status.
Is that possible or is it planned in the future ?

**Comment by dinger1986** [comment]
we looked at this, a script can monitor it, biggest issue is it needs to have relevant software installed for monitoring

**Comment by dwn419** [comment]
okay, is there a document for that ?
Or how can i do that ?

**Comment by wh1te909** [comment]
look here https://github.com/amidaware/community-scripts there might be something there already or in the WIP folder. if not, you can try writing a script that does what you need and then make a pull request on that repo to get it added into TRMM

**Comment by dinger1986** [comment]
This could be closed as a script will easily cover it
