### ISSUE TITLE
Upload Linux agent webUI

### ISSUE THREAD

**Issue by EvolpsTI** [amidaware/tacticalrmm#1164]
I would like to import the linux agent, but I don't find this option in the UI, the executables for Windows are in the /rmm/api/tacticalrmm/tacticalrmm/private/exe folder.

What is the correct way to upload?

**Comment by dinger1986** [comment]
There is no way to upload the linux agent.

You can upload it to other hosting

**Comment by EvolpsTI** [comment]
![image](https://user-images.githubusercontent.com/71237408/171920206-7747c6cd-b6eb-4787-be6d-d566a7549602.png)

Here's the print of the error, the idea of ​​uploading is to solve this problem.

> There is no way to upload the linux agent.
> 
> You can upload it to other hosting

I couldn't understand the solution.

**Comment by dinger1986** [comment]
There is no solution other than code signing at the moment.

Please read docs

https://docs.tacticalrmm.com/faq/
