### ISSUE TITLE
Pass information securely to scripts

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1169]
**Is your feature request related to a problem? Please describe.**
I would like to pass information securely to scripts across all platforms. On Linux, the general consensus is to use environmental variables to pass secrets from the parent to the child process. I believe this holds true for Mac. Environmental variables may also work on Windows but I don't know if that is generally accepted.

**Describe the solution you'd like**
I would like to pass information securely to an executable on all platforms. It would be nice if TRMM can pass information via environmental variables to the script, rather than embedding the info in the script or as a command line parameter to the script.

**Describe alternatives you've considered**
Currently, I'm thinking of passing an encryption key to the script (embedded, not as an argument), set an environmental variable and then run a binary.

**Additional context**
I would like to use this for backups. URLs, encryption keys for storage and API keys are some of the information I'd like to keep private between TRMM and the backup process.

**Comment by wh1te909** [comment]
added in 0.15.4
