### ISSUE TITLE
Policies marked as linux applying to windows when they're checks

### ISSUE THREAD

**Issue by Vedeneb** [amidaware/tacticalrmm#1171]
**Server Info (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - RMM Version v0.13.4

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.0.4
- Agent OS: Windows 10 Pro, 64 bit v21H1 (build 19043.1706)

**Describe the bug**
When a policy is marked as linux (for example a script is used where the platform is set to Linux) it still get's executed on windows agents as well.

**To Reproduce**
1. Create a script, set the platform to linux
2. Create an automation policy, add the linux-script as check
3. Apply the Automation policy to a set of agents or to a whole client/site
4. The script-check will also be executed on Windows agents

**Expected behavior**
The script-check should be executed on all linux agents, but not on windows agents

**Screenshots**
![image](https://user-images.githubusercontent.com/39202639/173689472-7da0dee0-9004-46c5-8349-b51dca6535c5.png)
![image](https://user-images.githubusercontent.com/39202639/173689510-3e8ce1a7-4c41-44a9-b5b1-8a5ab32b051c.png)
![image](https://user-images.githubusercontent.com/39202639/173689532-c3dc1cfd-7ae9-4676-b681-52927dc2a64c.png)
![image](https://user-images.githubusercontent.com/39202639/173689554-6d77cf5f-e982-48cb-8a45-084bf7014fc8.png)

**Additional context**
This was discussed with and confirmed by @silversword411 on discord

**Comment by sadnub** [comment]
Can you browse to the summary tab for this agent and see what the platform text is? I'm not able to replicate this.

**Comment by Vedeneb** [comment]
Has this possibly been addressed already? Just tried it again and could not reproduce it myself (now running TRMM version `0.14.6` and agent version `2.3.0`).

Maybe @silversword411 could try if it's still reproducible for him? Otherwise I think the issue can be closed.

**Comment by sadnub** [comment]
I actually patched up a couple issues that could make this happen intermittently. It will be in the next release. Thanks!
