### ISSUE TITLE
All checks for a Client disappear

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#1177]
**Server Info (please complete the following information):**
 - OS: deb 11
 - Browser: edge
 - RMM Version 13.4

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
This has happened twice now, both times for the same Client.  All Agent "Checks" (server and workstation) disappear for a client. The problem can be resolved by removing the automation policy and then re-applying it. The tasks never vanish, only the checks.

No changes to policies were made recently. This has happened twice in the past week to one particular client. No other client have shown this behavior. 

**To Reproduce**
Not sure how to reproduce it yet.

**Expected behavior**
Checks stay like good boi.

**Comment by silversword411** [comment]
If automation policies are applied, and they don't apply to the os, I've seen times where the policy will be there initially, and after an initial agent sync, policies will disappear when not applicable to the os. Maybe there's 1st run policy checks that will hide policies?

**Comment by wh1te909** [comment]
this is a bug with the cache. next time it happens from web UI do Tools > Clear Cache and then checks will re-appear

**Comment by Zebble** [comment]
We were having the same issue happen at a site level.  I can confirm that using Tools -> Clear Cache fixes the issue.  Thanks @wh1te909 !

**Comment by sadnub** [comment]
I just made some changes today, so check this out on the next release.
