### ISSUE TITLE
Add wake to TRMM interface

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1180]
Wake aka WOL is only in mesh atm, add it to TRMM somewhere.

![2022-06-21_155907 - TacticalRMM_-_wake](https://user-images.githubusercontent.com/13395348/174887183-f6c909ed-d5bd-48aa-a90d-9b27fb37420d.png)

Button in Summary screen and/or agent menu.

**Comment by elektr0nisch** [comment]
I'd probably be also very useful if waking up multiple clients at once (e.g. via an automation) would possible. I'm thinking of weekly automated updates (turn on pc, do updates, shutdown pc)

**Comment by wh1te909** [comment]
added to agent menu, will be in next release
