### ISSUE TITLE
Stuck at Mesh Central not ready yet

### ISSUE THREAD

**Issue by Aghiad90** [amidaware/tacticalrmm#1182]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): Fresh install (Latest Version)

**Installation Method:**
  - Standard
  
**Describe the bug**
Fresh install stuck at Mesh Central not ready yet

**Screenshots**
![image](https://user-images.githubusercontent.com/23388761/175101772-03a23d24-03de-42c8-ad92-f43275410f3a.png)

**Additional context**
I searched and most of case they said not enough ram . my server has 16gb of ram and 500gb of storage 

Any idea what i could try ?

**Comment by dinger1986** [comment]
What drives are in your machin are they majorly slow? Can we make this a discussion please as it's to do with your setup (I can't do it as in my phone).

**Comment by Aghiad90** [comment]
Hi @dinger1986  i did create a discussions 
i will delete this issue sorry about that 
also my drive is not slow and i am using virtual machine in proxmox environment 
https://github.com/amidaware/tacticalrmm/discussions/1183

**Comment by Aghiad90** [comment]
https://github.com/amidaware/tacticalrmm/discussions/1183
