### ISSUE TITLE
Timezone is not consistent when editing tasks

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1189]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome
 - RMM Version (as shown in top left of web UI): v0.13.4

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.0.4
- Agent OS: Windows 10 Pro, 64 bit v21H1 (build 19043.1526)

**Describe the bug**
When editing a task in an automation policy, the time entered is taken as your current time zone (or maybe PostgreSQL's timezone?), converted to UTC and saved in the database as UTC. Then when you edit the task again, it's showing the time from the database (UTC) without converting it to your local time. The result is the time shifts between saves depending on your timezone.

**To Reproduce**
1. Go to the automation manager and create a task. The time is irrelevant.
2. Edit the task and set the time for 09:00 PM. The date is irrelevant.
3. The database will save it as 09:00 PM UTC.
4. Edit the task again. My timezone is UTC-0400 and the time is showing 05:00 PM.
5. Edit the task again and don't change the time. The time will be set back according to the timezone. In my case, the time showing is now 01:00 PM.

**Expected behavior**
I expect the time to be consistent across saves. I.e. the frontend should convert the server/database time in UTC to local time.

**Screenshots**

**Additional context**
PostgreSQL configuration has "`timezone = 'US/Eastern'`". Not sure if that matters.

**Comment by NiceGuyIT** [comment]
This is a frontend issue.

Changing the PostgreSQL `timezone` does not change anything. The scheduled time on the agent is correct according to the time entered. The problem is when editing an existing task, the time needs to be adjusted back to what it was. For example, if you create a task to run at 9:00 PM every night, it will schedule the task correctly. If you go back in to edit the task, the time will not show correctly and you need to change it back to 9:00 PM.

**Comment by mctaguma** [comment]
We're seeing this issue too, it appears to be the frontend sending the POST with run_time_date having the Zulu timezone, instead of default_time_zone from core_coresettings.

![image](https://user-images.githubusercontent.com/2499576/179441516-da28bd88-4d32-4a08-a348-71245e9c98a2.png)

**Comment by wh1te909** [comment]
fixed in https://github.com/amidaware/tacticalrmm-web/commit/6ee3df7e4e44e7e8f0c852ffe37bf614161d3fcd
