### ISSUE TITLE
Easy Run as logged in user checkbox for scripts

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1190]
Have an easier way to run as currently logged in user for scripts. 

Mainly this would be for script output so you don't have to jump thru hoops for getting script return data.

**Comment by wh1te909** [comment]
https://github.com/amidaware/tacticalrmm/commit/febc9aed11edcc57a2c39420b1ab2099ee425351

**Comment by silversword411** [comment]
...you glorious bastard. 😆
