### ISSUE TITLE
Global automation polices aren't applied to Linux agents

### ISSUE THREAD

**Issue by ddkooker2** [amidaware/tacticalrmm#1191]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): v0.13.4

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.1.0-dev
- Agent OS: Ubuntu 20.04 LTS

**Describe the bug**
I've assigned some Global Polices for Servers/Workstations under settings -> Global Settings 
I've made some monitoring Scripts for windows and for Linux, both are added in the automation policy which is configured under Global Settings, under Windows all checks and tasks are assigned correctly and are showing only Windows Scripts (configured in script manager as platform. However the Linux agents aren't getting any policies from the Global configuration. 

I've tested this in 2 different environments (both use the same operating systems as given aboven) and both have the same behavior as described here. 

**To Reproduce**
1. Configure a Policy with Check scripts for Windows and for Linux
![image](https://user-images.githubusercontent.com/90603166/175784275-ac4d7477-b8a8-4cbd-8cb7-bfddec535cab.png)
2. Go to Settings -> Global Setting and configure the policy created in step 1
3. Check under your agents if the checks become available
3.1. Under a Windows agent:
![image](https://user-images.githubusercontent.com/90603166/175784312-7f35a8c8-f00c-4884-8fca-34115a44ddde.png)
3.2. Under a Linux agent:
![image](https://user-images.githubusercontent.com/90603166/175784329-a0de1ef2-d882-4091-88ee-31deef511550.png)

**Expected behavior**
What I expect to happen is that the available Linux scripts would be applied on the Linux Agents. 
When i manually assign the same Automation Policy to the agent the Linux check scripts show up and are working. 
![image](https://user-images.githubusercontent.com/90603166/175784410-78cb4e15-1536-43b9-b771-bd84fa221030.png)
![image](https://user-images.githubusercontent.com/90603166/175784424-16c6b641-08b8-480d-b5b6-2935d02c228b.png)

**Comment by Zebble** [comment]
To add to this...

Something changed in at least 0.14.6.

Now none of my Linux agents have any checks applied by a policy listed (I haven't tried manually adding directly to an agent), whether they were added before or after the upgrade.

I also tried the "Clear Cache" trick that worked before for policy issues.

**Comment by wh1te909** [comment]
the policy stuff hasn't really been reworked yet for multi OS support so for now the workaround is to just use add the checks individually on each linux agent, or create a new site just for linux and apply policy there

**Comment by sadnub** [comment]
You need to make sure the supported platform for those scripts is set to ALL or linux for script checks to apply to Linux agents. Only script checks and ping checks are supported at this time.

**Comment by sadnub** [comment]
I actually was able to track down the issue. This will be in the next release.

Thanks!
