### ISSUE TITLE
[Feature] Battery Health

### ISSUE THREAD

**Issue by johnnyq** [amidaware/tacticalrmm#1200]
**Is your feature request related to a problem? Please describe.**
Some Clients complain of laptop battery not holding a charge it would be nice to have a battery health check

**Describe the solution you'd like**
Check Battery Health

**Describe alternatives you've considered**

**Additional context**

**Comment by bradhawkins85** [comment]
You could use the following in a script/check: Get-CimInstance -ClassName Win32_Battery
This will give you a range of battery information. Below is the script I use to get the battery level.

```
$charge = Get-CimInstance -ClassName Win32_Battery
if (!$charge.EstimatedChargeRemaining) { 
    write-output "No Battery"
    Exit 0
} else { 
    Write-Output $charge.EstimatedChargeRemaining
    Exit $charge.EstimatedChargeRemaining 
}
```

This is the check I have set up against all machines
![image](https://user-images.githubusercontent.com/15325110/177667178-16f6bc12-e5cd-462f-9da9-585b1cebc377.png)

While it is not ideal it works and you may be able to adapt something better. 
This is the output from the check results:
![image](https://user-images.githubusercontent.com/15325110/177667286-08211b80-89dc-4d95-8a5a-f0990d37a868.png)
The results show as failing in the history but show as a blue informational result against the device.

**Comment by wh1te909** [comment]
thank you @bradhawkins85. @johnnyq for future requests like this please open them in the [community-scripts](https://github.com/amidaware/community-scripts) repo
