### ISSUE TITLE
Get list all installed software.

### ISSUE THREAD

**Issue by Nzrvynnyk** [amidaware/tacticalrmm#1201]
Hello! I think it would be great to be able to create a separate report to check installed software. this applies not only to installed programs but also to the kernel and operating system.
And for bulk scenarios, save the results in some custom files. or send the results by mail.

**Comment by BMTTeam** [comment]
I needed that last week. At the end I did it manually for 200. Exporting CSV file for each device.
If there is a hint or example how to use the API would be great.

**Comment by Nzrvynnyk** [comment]
Oh, yep and I need this, I have over 800+ agents and I think it would be great to have options for creating some kinds of reports.

**Comment by wh1te909** [comment]
reporting feature is still a WIP
I can provide an example of how to do this via API in a bit, working on a new release atm

**Comment by Nzrvynnyk** [comment]
It would be great to have examples for API. 
Like: hostname and software list.

**Comment by silversword411** [comment]
There is a management command for listing software that matches x

https://docs.tacticalrmm.com/management_cmds/#find-all-agents-that-have-x-software-installed

I'm looking for lots of API examples to add to the docs. Please post/share anything you come up with.

**Comment by wh1te909** [comment]
example of how to do it in python:

```python
import requests

API = "https://api.example.com"
HEADERS = {
    "Content-Type": "application/json",
    "X-API-KEY": "9SI43IFUMPEVRWOZR4NC8PGP4ZLA9PYX",
}


def get_software():
    agents = requests.get(f"{API}/agents/?detail=false", headers=HEADERS)  # get a list of all agents
    for agent in agents.json():  # loop thru all agents and print list of installed software
        r = requests.get(f"{API}/software/{agent['agent_id']}/", headers=HEADERS)
        print(r.json())

if __name__ == "__main__":
    get_software()
```

**Comment by Nzrvynnyk** [comment]
Thank you )
