### ISSUE TITLE
Script Check: Antivirus - Verify Status - Get-CimInstance : Invalid namespace

### ISSUE THREAD

**Issue by JoachimVeulemans** [amidaware/tacticalrmm#1202]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): v.0.13.4

**Installation Method:**
  - [ ] Standard
  - [X] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v.2.0.4
- Agent OS: Windows Server 2019 Standard, 64 bit v1809 (build 17763.2989)

**Describe the bug**
I am getting an error when executing the standard Antivirus check.
```
Get-CimInstance : Invalid namespace 
At C:\Windows\TEMP\trmm\3002544211.ps1:104 char:11
+ $return = Get-CimInstance -Namespace root/SecurityCenter2 -className  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root/SecurityCenter2:AntivirusProduct:String) [Get-CimInstance], CimExce 
   ption
    + FullyQualifiedErrorId : HRESULT 0x8004100e,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
 
Get-CimInstance : Invalid namespace 
At C:\Windows\TEMP\trmm\3002544211.ps1:117 char:3
+   Get-CimInstance -Namespace root/SecurityCenter2 -className Antiviru ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root/SecurityCenter2:AntivirusProduct:String) [Get-CimInstance], CimExce 
   ption
    + FullyQualifiedErrorId : HRESULT 0x8004100e,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

**To Reproduce**
1. Go to a Windows Server 2019 Standard
2. Run "Script check - Antivirus - Verify Status".
3. See error

**Expected behavior**
Should return an expected status code. Success or failed.

**Comment by dinger1986** [comment]
these are community scripts, please convert this to a discussion or discuss on the scripts channel on discord

**Comment by silversword411** [comment]
......and you're running this on server. This script has only been tested against workstations

**Comment by wh1te909** [comment]
Yea that namespace is not available on server skus, only workstations its on MS docs somewhere
