### ISSUE TITLE
webhooks as an alert option

### ISSUE THREAD

**Issue by testaccountiswhatimdoing** [amidaware/tacticalrmm#1222]
Add webhooks as an alert option in addition to SMS, Email and dashboard  so we can push alerts to Slack, teams or whatever we want

**Comment by Zebble** [comment]
This can be done through a script in the alert profile.  Granted, a direct webhook option would be simpler.

**Comment by wh1te909** [comment]
added to official roadmap https://docs.tacticalrmm.com/roadmap/

**Comment by compgeniuses** [comment]
wow, what a wonderful new feature

**Comment by unplugged216** [comment]
Hey @wh1te909 , 

Just checking on this. I dont want to duplicate work but is there progress on this or can we contribute this?

**Comment by wh1te909** [comment]
PR was just merged into develop last week and feature is complete. expect a release this week.

**Comment by wh1te909** [comment]
Released in 0.19.0
