### ISSUE TITLE
Request: Register all repos with OpenHub and Coverity Scan

### ISSUE THREAD

**Issue by UranusBytes** [amidaware/tacticalrmm#1229]
Tactical RMM is already registered with OpenHub - https://www.openhub.net/p/tacticalrmm

It would be great for the project (and visibility) to register all the repos associated with Tactical RMM (core, agent, web) with both OpenHub and Coverity Scan - https://scan.coverity.com/ - a static analysis tool that is free for open source projects.

**Comment by silversword411** [comment]
I tried to register the repo with Coverity...but didn't have much success. I'll close this for now
