### ISSUE TITLE
Allow for generating agents without dependence on Amidaware infrastructure

### ISSUE THREAD

**Issue by Reinitialized** [amidaware/tacticalrmm#1235]
**Is your feature request related to a problem? Please describe.**
As it stands, any and all generated agent installs are dependent on Amidaware Infrastructure and prevent TacticalRMM from being used in an environment disconnected from the Internet.

**Describe the solution you'd like**
Generate agents locally within TacticalRMM instead of depending on Amidaware. Code Signing can still be dependent on Amidaware since I am aware it is your main source of revenue for now until you have more long term plans in place.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dinger1986** [comment]
You can do this already with the powershell option and have download the exe from GitHub and store it somewhere on your network.

Or am I missing something?

**Comment by Reinitialized** [comment]
> You can do this already with the powershell option and have download the exe from GitHub and store it somewhere on your network.

I haven't had a real need to do mass deployment with PowerShell since this is within a lab environment and have been using the "Dynamically generated exe" option. This will suffice as a workaround, however I am referencing the ability to dynamically generate agents without additional preparation in place.
![image](https://user-images.githubusercontent.com/20674500/182612789-c5829392-8f7c-47cd-a5a7-496acd7e809a.png)

**Comment by dinger1986** [comment]
why not use a deployment? I assume the server is connected to the internet but the machines arent?

**Comment by Reinitialized** [comment]
Simple answer being my homelab/homeprod hasn't been big enough to warrant for such, and dynamically generating agents have been satisfactory. However, while testing around in a isolated portion of my environment which has no Internet access on a separate install of TacticalRMM, I noted the dynamic generation function was not working due to not having access to Internet resources. I will have to provide the exact error in question when I have a moment to hop into that environment again.

**Comment by dinger1986** [comment]
the deployment url is built in and available anyway

**Comment by wh1te909** [comment]
The generated exe is simply a convenience wrapper around the manual install method. It's the same exact thing as the powershell method except it ends in `.exe` instead of `.ps1`. The dynamic exe generation is hosted on the code signing servers and uses the same implementation so obviously that cannot be self hosted. If you would like to implement your own dynamic exe method you are welcome to do that, but if you want the convenience of Amidaware doing it for you then you have to use Amidaware infrastructure.
