### ISSUE TITLE
Swagger API doesn't reflect API capabilities

### ISSUE THREAD

**Issue by redanthrax** [amidaware/tacticalrmm#1236]
**Server Info (please complete the following information):**
 - OS: Arch btw
 - Browser: Brave
 - RMM Version (as shown in top left of web UI): v0.14.5

**Installation Method:**
  - [ ] Standard
  - [x] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): n/a
- Agent OS: n/a

**Describe the bug**
Swagger does not show the full capabilities of the API.
Example: POST /core/customfields/ accepts a json body but doesn't show in swagger.

**To Reproduce**
1. Enable swagger.
2. Browse any of the api methods that accept data.
3. They are all blank.

**Expected behavior**
Show examples of what the different endpoints accept.

**Screenshots**
![image](https://user-images.githubusercontent.com/1581645/182670080-ad348f1f-1dde-403a-83b0-9ef316133b58.png)

![image](https://user-images.githubusercontent.com/1581645/182670512-3d2fc2c5-18ff-4567-bf10-7dd7f7a66a3d.png)

^missing swagger decorators.

**Comment by wh1te909** [comment]
thx yea the swagger stuff is still a WIP, most of the serializers are going to be re-written to be simplified and align more with REST so we can auto generate the docs with the proper payload, they're not really designed for that atm

**Comment by wh1te909** [comment]
gonna close this cuz u already started to implement this with new api
