### ISSUE TITLE
Feature Request: Make multi-select custom fields easier to use

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1237]
**Is your feature request related to a problem? Please describe.**
Using a collector script to populating multiple items in a multi-select fields is very restrictive. It accepts only a comma separated list of values on one line.

**Describe the solution you'd like**
It would be nice if it also accepted a list of values separated by newlines. For example, one value per line. Another option, albeit a little more intense, is to use JSON to represent the multiple values.

**Describe alternatives you've considered**
N/A

**Additional context**
It took a while to figure out how to set multiple values in a multi-select custom field.

**Comment by sadnub** [comment]
I believe this is a restriction with Postgres arrayfield. That is how it stores them in the database. In the django app, it will convert the returned values into an array which makes it really easy to use. But using scripts this conversion needs to happen client side.

**Comment by silversword411** [comment]
We'll close as a won't fix unless someone has a better idea.
