### ISSUE TITLE
Capture output of bulk commands

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1240]
**Is your feature request related to a problem? Please describe.**
Bulk Command and Bulk Script do not have a way to capture the output.

**Describe the solution you'd like**
Ideally, there should be a way to capture the output of the Bulk commands. Bulk Command is useful to gather ad-hoc information. It would be nice if the information could be displayed in a table, or at the very least, email the results.

Bulk Script is useful to take action on a group of machines. Most scripts output something. It would be nice if the information could be displayed in a table, or at the very lest, email the results.

**Describe alternatives you've considered**
N/A

**Additional context**
Other users have mentioned the same on Discord.

**Comment by wh1te909** [comment]
the output of bulk command/script is already captured and saved to the db, you can view it from web UI in the History tab on the agent, or thru the api from the `/agents/history/` endpoint

**Comment by NiceGuyIT** [comment]
Thanks! Then this is a docs issue. Ultimately this probably be exposed in the reporting.
