### ISSUE TITLE
Feature Request: User Consent controlled by User, not by Admin

### ISSUE THREAD

**Issue by eXifreXi** [amidaware/tacticalrmm#1241]
Hello there,

we noticed that User Consent is set up in the mesh settings by Admins. Which means the Admin can just undo the User Consent requirement without the actual User knowing about it, right? I fail to see where that qualifies as User Consent, as it doesn't really add much trust to the whole setup. Our Users should always know when we are on their device or want to get into it, and that shouldn't really be in our control. There is always the option to disable and spy, which is really bad.

The Mesh Agent on the Client's PC should allow enabling and disabling the Consent Settings. We don't need them for our Servers, but we do need them for our remote employees. Additionally, for emergency cases, there should be a way to get into each device without Consent, but with all sorts of visual feedback for the user that the device got taken over.

There isn't really an alternative, despite the User just disabling the Mesh Agent on their end to block this whole feature.

Cheers,
Cedric

**Comment by dinger1986** [comment]
This is a feature request for meshcentral please open on their GitHub repo as TRMM does not control this.

**Comment by eXifreXi** [comment]
Right, my bad. Will move it!
