### ISSUE TITLE
Remote Wake-On LAN

### ISSUE THREAD

**Issue by GMaster5o5** [amidaware/tacticalrmm#1243]
**Is your feature request related to a problem? Please describe.**
Not able to wake remote computers when I need to do maintenance.

**Describe the solution you'd like**
It would be great if you guys could add a Wake-On LAN button in the Device Action menu, that would same a lot of time login into other platforms to Wake Computers.

**Comment by bbrendon** [comment]
Am I missing something. It's already there.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/6364477/184806281-1d3dce13-a9bf-44ca-8974-51c592b30813.png">

**Comment by wh1te909** [comment]
thanks @bbrendon yep it's already there
