### ISSUE TITLE
Add "Copy to clipboard

### ISSUE THREAD

**Issue by stavros-k** [amidaware/tacticalrmm#1245]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bbrendon** [comment]
You can open an issue here regarding mesh central . https://github.com/Ylianst/MeshCentral

**Comment by dinger1986** [comment]
It's not mesh.

**Comment by stavros-k** [comment]
> You can open an issue here regarding mesh central . https://github.com/Ylianst/MeshCentral

Crap, I probably hit Control + Enter and submitted half isue here, and the rest on the #1246
