### ISSUE TITLE
Add "Copy to clipboard" when clicked, on blueboxes under assets

### ISSUE THREAD

**Issue by stavros-k** [amidaware/tacticalrmm#1246]
**Is your feature request related to a problem? Please describe.**

Currently is a bit hard to copy paste values from assets, at least on dark mode you can't even see what's selected.

**Describe the solution you'd like**

- Highlight on what's selected
- Copy to clipboard function. Either on the blue "box" or an extra icon next to it.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/47820033/185153232-2bb8bd0c-b8bd-4269-a28c-9bb81c0bd0a9.png)

**Comment by dinger1986** [comment]
can you not right click copy? works fine for me with chrome, maybe its your browser?

**Comment by stavros-k** [comment]
> can you not right click copy? works fine for me with chrome, maybe its your browser?

![image](https://user-images.githubusercontent.com/47820033/185165207-06b2240b-fbc2-4f6e-a1c8-f5e95ff319e2.png)

Right click on the blue box on Chrome

**Comment by wh1te909** [comment]
https://user-images.githubusercontent.com/7434746/185206208-d04f204b-bb31-48c3-9900-037dd8c6d334.mp4

**Comment by wh1te909** [comment]
done will be in next release

**Comment by stavros-k** [comment]
> copy_clip.mp4

Thanks! Looks great!
