### ISSUE TITLE
Feature Request - Notify End User that Remote User is Connected

### ISSUE THREAD

**Issue by pcwizrd** [amidaware/tacticalrmm#1261]
Is there a way to display to an end user that a remote user is connecting through TRMM? I like to notify my clients when I am on their systems so they know to leave it alone.

Additionally, option to disable end user local input while remote user is connected?

**Comment by dinger1986** [comment]
https://docs.tacticalrmm.com/tipsntricks/#meshcentral covers the majority of that.

If you search google for meshcentral disable user input you will find that also

**Comment by pcwizrd** [comment]
Thanks, just what I was looking for. 

Any idea how to change it to say something other than -

Sharing desktop with: TacticalRMM 

I tried renaming the group in MeshCentral but it still shows TacticalRMM when connecting.

**Comment by dinger1986** [comment]
Yes, change the name or add a name in "my account" nickname to whatever you want and then it should show that.

**Comment by pcwizrd** [comment]
> Yes, change the name or add a name in "my account" nickname to whatever you want and then it should show that.

Do you mean in MeshCentral or TRMM?
When I tried to change the account details in MC the Real Name is read only. I can change some features like User Consent and Admin Realms but not the name.

**Comment by dinger1986** [comment]
Yes in meshcentral in the same place where you added the user consent

**Comment by pcwizrd** [comment]
No good. When I try to edit, no options are available.
![2022-08-23 16_15_16-Tactical RMM — Mozilla Firefox](https://user-images.githubusercontent.com/10390150/186246987-08416861-ba17-4b3b-a052-0a33a356099b.png)

**Comment by pcwizrd** [comment]
Figured it out. The Dark Theme in FireFox makes the edit icon almost invisible.

**Comment by dinger1986** [comment]
Ah sorry it's Real Name, I was going from memory

**Comment by eddyz1122** [comment]
It seems that it is not possible to use the logged in user from Tactical RMM name that would be displayed to the end user?

For a team of staff using TRMM it isn't transparent to the user who in particular is remotely connecting to their PC.
