### ISSUE TITLE
FEATURE REQUEST: Select preferred NIC for direct RDP connections

### ISSUE THREAD

**Issue by nativeit** [amidaware/tacticalrmm#1267]
**Is your feature request related to a problem? Please describe.**
I make use of always-connected VPN's on my managed networks and/or endpoints to provide for safely connecting to them via vanilla MS RDP. While I must admit that MeshCommander's implementation of RDP is impressively effective and responsive when connecting through the public internet, I still prefer to connect directly through the VPN whenever possible. 

**Describe the solution you'd like**
To accomplish this, I would only need to be able to specify which NIC and/or IP address to use with the existing Take Control option for "RDP Connect". My VPN's subnet and NIC is visible in the device's details.

**Describe alternatives you've considered**
I have so far just continued to use TacticalRMM primarily for monitors and scripts. For remote access, unless I am away from my usual workstation, I use Devolution's Remote Desktop Manager to open RDP sessions using native MS RDP. I am currently looking at MeshCommander's front-end and console for a method of setting the preferred NIC/IP address for communicating with the agents. If it exists, I would imagine there would be an associated API call that could be used with TacticalRMM to provide for a widget that selects the desired NIC/IP address. If it turns out that this is not possible with either MeshCommander's API, or with something in the way MC and the RMM function together, then my next best solution will be to explore ways that I can integrate Tactical RMM into Remote Desktop Manager, as a simple browser tab embedded into RDM's interface, if nothing else. But RDM accepts a huge number of custom metadata fields and functions, so there may be some interesting options for a more elegant integration with data and dynamic links. 

**Additional context**

### Screenshot of RDP Connect
![Screen Shot 2022-08-27 at 6 55 23 PM](https://user-images.githubusercontent.com/68449281/187050941-9979d4f7-6fbf-48d7-b771-0a7f891e354a.png)

---
### Screenshot of NIC details in MeshCommander
![details](https://user-images.githubusercontent.com/68449281/187051010-76bb17f5-587a-4e8a-abf6-2b6da25992f1.jpg)

---

Please feel free to close this out if this idea is either not feasible. If it can be done, but is not worth the time/manpower of existing devs, I am somewhat capable of writing very basic code, but proficient enough to setup an API call and a few fields in a modular form. I'd be happy to work on this myself, but would love to have an opinion from someone familiar with Tactical RMM and/or MeshCommander as to whether it's even possible. 

**Thanks for everything you have done so far, and I am enthusiastically looking forward to what's yet to come!**

**Comment by bbrendon** [comment]
What you're asking isn't part of Tactical. That is Meshcentral. You'll need to ask them.
https://github.com/Ylianst/MeshCentral

Tactical just shows the mesh interface as an iframe.

**Comment by wh1te909** [comment]
thanks @bbrendon yes this would need to be implemented in Meshcentral which is a separate product so i'll close this ticket and you can open the request there.
