### ISSUE TITLE
Tactical not following permission settings.

### ISSUE THREAD

**Issue by technoicon** [amidaware/tacticalrmm#1268]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): 0.14.6

**Installation Method:**
  - [x ] Docker

**Describe the bug**
APermissions don't apply to Tactical Users.
As a user with no permission to user accounts, I can still create and delete them.  It doesn't seem to block sites, even though I have access.
Tried with new user, using incognito mode.

Super User can be ticked but other items can be unticket, I would have thought this would get unticked, when another tick box removes "super user" type permission.

**Expected behavior**
Follow permission settings.

Will update with more infomation and screenshot as I can.

**Comment by technoicon** [comment]
This seems to be a problem with users created before permissions were implemented.

**Comment by wh1te909** [comment]
You can either recreate those users or use the django admin to edit them and remove the built in django "super user" property of them (before perms were added all users were super users)
