### ISSUE TITLE
Uninstall Software via Tactical RMM

### ISSUE THREAD

**Issue by michaelortnersanube** [amidaware/tacticalrmm#1276]
**Is your feature request related to a problem? Please describe.**
My problem is not related to a problem, it would be great if you can go to the client under the software tab and can select software what you like to uninstall.

**Describe the solution you'd like**
Maybe a uninstall button, or if you right click on the software that you can select uninstall. The the software will be removed from the computer.

**Describe alternatives you've considered**
-

**Additional context**
I'am not sure if it works but it would a great feature.

**Comment by silversword411** [comment]
See https://github.com/amidaware/community-scripts/blob/main/scripts/Win_Software_Uninstall.ps1

Which is in your Community Script Library
