### ISSUE TITLE
Windows Service Check - return wrong status when "Restart Service if it's stopped" got ticked

### ISSUE THREAD

**Issue by wangshiok** [amidaware/tacticalrmm#1278]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: [Edge]
 - RMM Version (14.6)

**Installation Method:**
  - [ ] Standard

**Agent Info (please complete the following information):**
- Agent version (14.6):
- Agent OS: [Server 2019]

**Describe the bug**
If you tick the option of "Restart Service if it's stopped" when setup a Windows Service Check, the service check will always return as running even the service is actually stopped.

**To Reproduce**
1. Pick an Agent
2. Click on 'Checks' > 'New' > 'Windows Service Check'
3. pick any windows service that you want to check and tick the box of "Restart Service if it's stopped" 
4. Do NOT disable the service but make service unable to start (say you change the config file of that service)
5. run the check, the check will try to start the service as expected and return with status 'RUNNING' even the service failed to start and is actually in 'STOPPED' status

**Expected behavior**
Windows Service Check should return the true running status of a windows service

**Screenshots**

**Additional context**
The service I am checking comes with third party program, it links to an .exe and .exe.config file, if I just remove the exe so the service won't start, Check Service return with correct status, but if I just modify the exe.config file so the service won't start, Check Service return with wrong status - "RUNNING"

**Comment by silversword411** [comment]
Screenshots of service status in services list please.

**Comment by silversword411** [comment]
Not enough details to replicate. Closing
