### ISSUE TITLE
Bug with Block Policy Inhiretance from Agent

### ISSUE THREAD

**Issue by ssteeltm** [amidaware/tacticalrmm#1283]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: edge
 - RMM Version 14.8

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version: Agent v2.3.1
- Agent OS: Windows 10 Pro, 64 bit v21H2

**Describe the bug**
right click an agent, assign automation policy , Tick the box to Block policy inheritance. it wont apply

**Expected behavior**
it should apply and block all the inherinted policies

**Comment by wh1te909** [comment]
thanks, fixed in https://github.com/amidaware/tacticalrmm/commit/548250029dcf2d977b8a91154656b3951df3944f you can manually apply the change for now and restart the `rmm.service` for changes to take effect, rather than waiting for the next release
