### ISSUE TITLE
Change the run as user built in check box to allow the status to be info instead of fail.

### ISSUE THREAD

**Issue by meuchels** [amidaware/tacticalrmm#1285]
**Is your feature request related to a problem? Please describe.**
Run as user script checks fail when user is not logged in.

**Describe the solution you'd like**
Give the option to set as informational instead of fail

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by meuchels** [comment]
was going through some stuff today and realized the check comes back with code 66 so I set that as an informational return code and the check went blue.  Maybe no need to change anything rather just add to the docs?

**Comment by wh1te909** [comment]
as of 0.16.2 the default behavior changed to continue with the script if no user is logged in, instead of failing right away
