### ISSUE TITLE
No Windows 10 Feature updates in TRMM

### ISSUE THREAD

**Issue by honzamuzzy** [amidaware/tacticalrmm#1299]
**Server Info (please complete the following information):**
 - OS: Debian 11
 - RMM Version: v0.15.0

**Installation Method:**
  - Standard

**Agent Info (please complete the following information):**
- Agent version: 2.40
- Agent OS: Win 10

**Describe the bug**
Windows Features updates not seen in TRMM

**Additional context**
I don't see Feature updates between versions (from 20H2 to 21H1, from 21H1 to 21H2) in TRMM. I can see them in Windows Update on my computer, but they won't install because I can't approve them. TRMM offers me the standard bug fixing updates, but not these feature updates.
Thanks in advance for your help

**Comment by emtek-at** [comment]
Driver Updates are also not visible in Tactical, but with PSWindowsUpdate they are available.

**Comment by wh1te909** [comment]
feature updates and driver updates are not included in WUA query, so this would be a feature request. the TRMM windows update is getting a major rework, and there is already an epic ticket to track this in https://github.com/amidaware/tacticalrmm/issues/1188 so I will link this request to that and include it in the rework
