### ISSUE TITLE
URL color for the Microsoft Update KB link when in dark mode is very hard to read.

### ISSUE THREAD

**Issue by EdwardSoaresJr** [amidaware/tacticalrmm#1314]
**Server Info (please complete the following information):**
 - OS: [Debian 11]
 - Browser: [All]
 - RMM Version (0.15.0):

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (v2.4.0):
- Agent OS: [Windows]

**Describe the bug**
When viewing the "More Info" link on the Patches tab the "Support URLs" link is unreadable due to the links color.

**To Reproduce**
1. Click on an agent
2. Click Patches
3. Click on a More Info link
4. See issue

**Expected behavior**
Readable color for the link in dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/10336569/195263386-7d3d0a64-d565-4360-bc43-6140ce8012c4.png)

**Additional context**
Not a priority but a simple fix.

**Comment by wh1te909** [comment]
thanks, fixed in https://github.com/amidaware/tacticalrmm-web/commit/9729492d1cf19511e4f27ec27f2cb5e1dc8da91f will be in next release
