### ISSUE TITLE
Add option to "Run action from Tactical Server" in Alert MAnager -> Alert Failure/Resolved Settings

### ISSUE THREAD

**Issue by Zebble** [amidaware/tacticalrmm#1316]
We use the Alert Failure/Resolved action to run a script that opens/closes a ticket in our ticketing system (ConnectWise).  If a check/task fails and for some reason the Alert Failure/Resolved action can't run on the device itself, the system either won't open a ticket or can't close an existing ticket.

If the Failure and Resolved actions could have an option to "Run action from Tactical Server", this should address this problem.

This could also solve a potential security problem where Tactical may try to run the Failure/Resolved actions from a device on another customer's network if it can't run it on the main device.

**Comment by Zebble** [comment]
Just bumping this one up.  Is this feature on the roadmap?

**Comment by silversword411** [comment]
Everything in github issues is on the TODO list. We keep issues cleaned of redundant stuff

**Comment by wh1te909** [comment]
added to official roadmap https://docs.tacticalrmm.com/roadmap/

**Comment by P6g9YHK6** [comment]
> added to official roadmap https://docs.tacticalrmm.com/roadmap/

When a script will be run on the server will it have all the variables of the agent available?
and i suppose that it will have to be python or bash?

**Comment by P6g9YHK6** [comment]
Also is it possible to have this as an action for conditional check/tasks output

**Comment by wh1te909** [comment]
@P6g9YHK6 it will have all the variables of the alert which will also have a reference to the agent so you can access all the agent fields. 

It can be written in any language that is installed on the trmm server, not just python and bash. So node, perl, even powershell if you want (but you'll need to install powershell core on the trmm server). The interpreter will be set at the top of the script with a shebang, same way scripts on linux agents work now.

At the moment it will only be implemented for alert failure/resolved actions.

**Comment by xrsxj** [comment]
Hey @wh1te909 if you are writing this up, i'd say adding the ability to store the "ticket number" or even adding custom fields in alerts would be awesome and would make things way more extensible for future integration ideas and frameworks.

**Comment by wh1te909** [comment]
Released in 0.19.0
