### ISSUE TITLE
Linux agent no error message if no connected to internet

### ISSUE THREAD

**Issue by rebootit** [amidaware/tacticalrmm#1317]
If you have no DNS resolution the script output look like it worked:

Downloading tactical agent...
Downloading and installing mesh agent...
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
Getting mesh node id...
Created symlink /etc/systemd/system/multi-user.target.wants/tacticalagent.service → /etc/systemd/system/tacticalagent.service.

Of course it does not install the agent.

**Comment by wh1te909** [comment]
thanks, fixed in https://github.com/amidaware/tacticalrmm/commit/a50bf901d33636c2ea3a88d93d6b87c4cebc7d49
