### ISSUE TITLE
Tasks won't be recreated

### ISSUE THREAD

**Issue by emtek-at** [amidaware/tacticalrmm#1319]
**Server Info:**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version: v0.15.0

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info:**
- Agent version: v2.4.0
- Agent OS: Win 10 v21H2

**Describe the bug**
Tasks from Automation Policies won't be recreated if the Policy changes and later get switched back.

**To Reproduce**
1. Create a Automation Policy with one task
2. Assign this Policy to a client or site
3. The Task is getting created on the Agents
4. Right Click on one Agent ->Assign Automation Policy and activate "Block policy inheritance" -> Submit
5. The Task is now deleted from the Web UI
6. Select from the Menue Tools -> Server Maintenance -> Remove Orphaned Tasks. The Task is now deleted from the Client
7. Right Click on one Agent ->Assign Automation Policy and deactivate "Block policy inheritance" -> Submit
8. The Task is now in Sync Status "Synced with agent" but it is not created on the Client. The Windows Scheduled Tasks UI doesn't show the Task

**Expected behavior**
After Step 7 the Task should be recreated on the Client.
I think the "Remove Orphand Tasks" Function does not reset the Status of the Task in the Database.

**Additional context**
Maybe the Agent should whenever the Tasks get modified check if all Tasks are properly created.

**Comment by wangshiok** [comment]
can someone get this bug fixed?

**Comment by herzkerl** [comment]
Worked for me after running ‚Server Maintenance > Remove Orphaned Tasks‘.

**Comment by silversword411** [comment]
Closing, post if it's still a problem
