### ISSUE TITLE
Request to assign separate alert templates per device type (Workstation vs Server) 

### ISSUE THREAD

**Issue by kmhadmin** [amidaware/tacticalrmm#1320]
**Is your feature request related to a problem? Please describe. **
Nope

**Describe the solution you'd like**
We would like the ability to create/assign a separate workstation and server alert templates. As it is now, we can only assign one alert template that covers both Servers and Workstations. This causes an issue for our use case as we have different requirements for alerts notifications for workstations vs servers. For example, we do not want or need alerts for workstations that are offline. Also, we need to assign specific alert conditions to Servers that don't apply to workstations and would cause a lot of false alerts from the workstations.

**Describe alternatives you've considered**
Possible option we found was to remove all sites under each client and then create only two sites, one for workstations and one for servers which would allow us to then apply separate alert templates to each device type, but in doing this. We lose the asset organization and location tracking for each client letting us know which office/location the system is located at which now creates another issue for us. 

**Additional context**

**Comment by dinger1986** [comment]
You can do that.

Right click on the client and choose automation policy then assign your server policy and workstation policy

**Comment by kmhadmin** [comment]
This is not the automation policies but the alert templates.

**Comment by wh1te909** [comment]
create the automation policy, create the alert template, then from Automation Manager find your policy and click "Assign Alert Template"

**Comment by wh1te909** [comment]
@kmhadmin yes I agree, we do have planned a rework of policies and alerts and one of the things was to have alert templates not related to policies so you could assign then to just severs or workstations without relying on a policy. Atm the above comment is the only way to do it now until the rework. Hope that helps.

**Comment by kmhadmin** [comment]
@wh1te909 Thanks for the reply. I had someone that wasn't sleep deprived look over everything and we have worked out a way using alert templates attached Automation Policies that will allow us to achieve what we wanted so we should be good to go now.
