### ISSUE TITLE
Integration of Telegram or Discord for alerts

### ISSUE THREAD

**Issue by scoopdreams** [amidaware/tacticalrmm#1321]
We have moved lots of our servers' notifications via Grafana to Telegram/Discord, in order to avoid email clutter as well as improve visibility.

Could you all consider adding an alert route towards those two platforms?  Thanks!

**Comment by joeldeteves** [comment]
You can do this using the TacticalRMM API and an integration such as Zapier, N8N, etc.

Have you considered looking into any of these options?

IMO the platform shouldn't be bloated with integrations for various alert platforms - it already supports SMS and email as well as an API which covers virtually all use cases (you can use it with any alert platform you want).

**Comment by bradhawkins85** [comment]
You can use the script below for Discord alerts:

```
param (
  [string] $alerttime="",
  [string] $alertmessage="Device Offline",
  [string] $alertseverity="Critical",
  [string] $alertstatus
)

$hookUrl = 'https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

$content = @"

$alertstatus - $alertmessage
  
"@

$payload = [PSCustomObject]@{

    content = $content

}

Invoke-RestMethod -Uri $hookUrl -Method Post -Body ($payload | ConvertTo-Json) -ContentType 'Application/Json'
```

Use the script arguments below to change the content of the notification:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/15325110/197651309-a4081867-1bc8-4688-b7d0-266451d785a5.png">

**Comment by scoopdreams** [comment]
Thanks for this! Ah yes I did not realise Tactical allows for custom direct API calls. That will work very well for notifications via almost any platform. Appreciate the assistance and will close this feature request.
