### ISSUE TITLE
Add WireGuard to TRMM so servers can be hosted anywhere without any port forwarding.

### ISSUE THREAD

**Issue by applebyp** [amidaware/tacticalrmm#1329]
I'm testing TRMM behind a Zerotier SDN. It's working ok but tricky to route LAN to the SDWAN.

If TRMM server and agents had WireGuard baked in there would be a big jump in security.

**Comment by silversword411** [comment]
Currently WireGuard is outside TRMM core scope, and is a separate service you can add yourself.

At the current time, I think this would be outside scope. 

FYI, you are still going to have to forward the Wireguard port.

**Comment by NiceGuyIT** [comment]
I use Nebula which doesn't have routing like a traditional VPN. Routing is determined by the address you request. If DNS returns the SDWAN IP, routing uses the SDWAN. If DNS returns the WAN IP, routing uses the WAN. DNS is part of the implementation.

When setup like this, I don't need to have WireGuard in the agent, or ZeroTier for that matter. I just need control of the DNS for the domain hosting TRMM to tell the agents to use the SDWAN IP.

**Comment by wh1te909** [comment]
yea wireguard or any vpn technology doesn't have anything to do with the actual trmm software functionality. you can deploy trmm however you want, behind whatever network or proxy you want. so definitely outside the scope of a feature request
