### ISSUE TITLE
Hostnames sometimes change to wrong name unexpectedly

### ISSUE THREAD

**Issue by cxgl** [amidaware/tacticalrmm#1338]
I seem to have an issue with hostnames being incorrect in some instances. We have a Client called '0_UNASSIGNED' that we initially install agents from. When the agent first checks in, we move it to the correct client. What I'm seeing is the hostnames in our 'All Clients' view getting overwritten by the hostnames from 0_UNASSIGNED.

Ostensible STR:
- Create a Client called '0_UNASSIGNED' and a site called 'ASSIGN_ME'
- Create one workstation agent for deployment using said client and site.
- Install said agent on N machines. Make note of the hostnames. I'm not sure if they need to check in or not, or be online or not.
- Go to ANY other client, including "All Clients". Check the hostnames. Do the first 1 to N hostnames match the 0_UNASSIGNED names?

OS of server: Ubuntu 20.04.5 LTS
TRMM version: 0.15.2, but it's been happening since at least the 0.14.x's.

**Comment by wh1te909** [comment]
Can you please watch this video, I tried to replicate but seems to be working fine.
Possible to record a video of what you're seeing?

https://user-images.githubusercontent.com/7434746/198852484-ad5869e4-a5ce-4ab9-85b1-0e0b59fd5d1a.mp4

**Comment by cxgl** [comment]
Hi,

I recorded a video, but it has confidential info in it. I assume if I put it here it becomes public record? I'd like to avoid that.

I'd be happy to send you a secure one-time link.

What to do?

Thanks,
Michael

**Comment by wh1te909** [comment]
ok you can email the link to `help@amidaware.com`

**Comment by cxgl** [comment]
Done.

**Comment by silversword411** [comment]
You aren't using imaging software to clone windows installs after TRMM is installed are you?

**Comment by cxgl** [comment]
Most definitely not, no.

[cid:e67cd345-19ad-41af-a293-90d1876126c4]<http://www.computerexpertsgroup.com/>
Michael Schechter​​
President
t: 914-644-6471<tel:914-644-6471>
e: ***@***.******@***.***>       |      w: www.computerexpertsgroup.com<https://www.computerexpertsgroup.com/>
[Twitter]<https://twitter.com/cxgtweet>
[Facebook]<https://www.facebook.com/Computer-Experts-Group-Ltd-312170305462291/>
[LinkedIn]<https://www.linkedin.com/company/computer-experts-group-ltd./>
Schedule a call with me:<https://calendly.com/cxgl/confab> https://calendly.com/cxgl/confab
________________________________
From: silversword411 ***@***.***>
Sent: Monday, October 31, 2022 1:29 PM
To: amidaware/tacticalrmm ***@***.***>
Cc: Michael Schechter ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]:Re: [amidaware/tacticalrmm] Hostnames sometimes change to wrong name unexpectedly (Issue #1338)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


You aren't using imaging software to clone windows installs after TRMM is installed are you?

**Comment by wh1te909** [comment]
it appears you have duplicate agents, because in the `ASSIGN_ME` site I see an identical hostname that also appears in another site, but in the `ASSIGN_ME` site the agent is offline and in the other site, it's online. Nothing in TRMM prevents you from having more than 1 agent with the same hostname, as you could have different clients who happen to have the same computer name. So sounds like you just have some stale agents that you need to manually remove from the dashboard (right click > uninstall).

**Comment by cxgl** [comment]
Embarrasingly, I think it might in fact be a cache problem like silversword411 suggested.

The very odd thing is is happens on multiple browsers (firefox and chrome) on the same linux box, but it did not seem to happen on a crappy windows box I have.

The duplicate agent thing you're seeing is actually the problem I'm seeing. Those computers are definitely not supposed to be the same names. We name them based on model+serial number. That's why I didn't want the video in the public record.

I'll do a little more digging and update you, but much to my chagrin -- thank you for suggesting cache. 😕




[cid:c08b9193-dc49-4422-93aa-64f65586748a]<http://www.computerexpertsgroup.com/>
Michael Schechter​​
President
t: 914-644-6471<tel:914-644-6471>
e: ***@***.******@***.***>       |      w: www.computerexpertsgroup.com<https://www.computerexpertsgroup.com/>
[Twitter]<https://twitter.com/cxgtweet>
[Facebook]<https://www.facebook.com/Computer-Experts-Group-Ltd-312170305462291/>
[LinkedIn]<https://www.linkedin.com/company/computer-experts-group-ltd./>
Schedule a call with me:<https://calendly.com/cxgl/confab> https://calendly.com/cxgl/confab
________________________________
From: Dan ***@***.***>
Sent: Monday, October 31, 2022 3:05 PM
To: amidaware/tacticalrmm ***@***.***>
Cc: Michael Schechter ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]:Re: [amidaware/tacticalrmm] Hostnames sometimes change to wrong name unexpectedly (Issue #1338)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


it appears you have duplicate agents, because in the ASSIGN_ME site I see an identical hostname that also appears in another site, but in the ASSIGN_ME site the agent is offline and in the other site, it's online. Nothing in TRMM prevents you from having more than 1 agent with the same hostname, as you could have different clients who happen to have the same computer name. So sounds like you just have some stale agents that you need to manually remove from the dashboard (right click > uninstall).

**Comment by wh1te909** [comment]
ok I am trying to see if they are actually duplicates, because if there are 2 agents in the database with identical hostnames then the web UI is always going to show them no matter what as the database is the source of truth. 

Please see code snippet below and run the exact same thing on your server and report back the result. Just replace `CHANGEME` with one of the hostnames that's a duplicate (keep the double quotes):

```python
tactical@tacrmm:~$ cd /rmm/api/tacticalrmm/
tactical@tacrmm:/rmm/api/tacticalrmm$ source ../env/bin/activate
(env) tactical@tacrmm:/rmm/api/tacticalrmm$ python manage.py shell
Python 3.10.6 (main, Aug 24 2022, 00:44:45) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from agents.models import Agent
>>> len(Agent.objects.filter(hostname="CHANGEME"))
0
>>>
```

**Comment by cxgl** [comment]
OK -- I did just that, and I'm seeing a single item returned:

***@***.***:~$ cd /rmm/api/tacticalrmm/
***@***.***:/rmm/api/tacticalrmm$ source ../env/bin/activate
(env) ***@***.***:/rmm/api/tacticalrmm$ python manage.py shell
Python 3.10.8 (main, Oct 25 2022, 16:30:27) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from agents.models import Agent
>>> len(Agent.objects.filter(hostname="IRD14-214500301"))
1

(now I go to another 'site' and see the same hostname duplicates via the web UI, but I run the above again and get)

>>> len(Agent.objects.filter(hostname="IRD14-214500301"))
1
>>>


...so that means to me it's a single db entry, right?

I tried that with multiple seemingly-duplicated hostnames, and they all come out '1'.

...which implies something wrong with the cache or browser or something...



[cid:ca4af26b-9b37-4245-a625-11ccd6aae5f7]<http://www.computerexpertsgroup.com/>
Michael Schechter​​
President
t: 914-644-6471<tel:914-644-6471>
e: ***@***.******@***.***>       |      w: www.computerexpertsgroup.com<https://www.computerexpertsgroup.com/>
[Twitter]<https://twitter.com/cxgtweet>
[Facebook]<https://www.facebook.com/Computer-Experts-Group-Ltd-312170305462291/>
[LinkedIn]<https://www.linkedin.com/company/computer-experts-group-ltd./>
Schedule a call with me:<https://calendly.com/cxgl/confab> https://calendly.com/cxgl/confab
________________________________
From: Dan ***@***.***>
Sent: Monday, October 31, 2022 3:17 PM
To: amidaware/tacticalrmm ***@***.***>
Cc: Michael Schechter ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]:Re: [amidaware/tacticalrmm] Hostnames sometimes change to wrong name unexpectedly (Issue #1338)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


ok I am trying to see if they are actually duplicates, because if there are 2 agents in the database with identical hostnames then the web UI is always going to show them no matter what as the database is the source of truth.

Please see code snippet below and run the exact same thing on your server and report back the result. Just replace CHANGEME with one of the hostnames that's a duplicate (keep the double quotes):

***@***.***:~$ cd /rmm/api/tacticalrmm/
***@***.***:/rmm/api/tacticalrmm$ source ../env/bin/activate
(env) ***@***.***:/rmm/api/tacticalrmm$ python manage.py shell
Python 3.10.6 (main, Aug 24 2022, 00:44:45) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from agents.models import Agent
>>> len(Agent.objects.filter(hostname="CHANGEME"))
0

**Comment by wh1te909** [comment]
thank you so yes that means a single db entry. so sounds like browser issue on linux since you said on windows, no issue?

**Comment by cxgl** [comment]
Yeah... Not sure why. My daily driver is a linux box and I flip between chrome and firefox. They both act the same.

But when I just connected via a chrome incognito window, the problem did not show up.

The test I did before was on firefox on a spare windows box.

I just cleared cache, but it's still happening on linux+chrome. I may have to clear more, which is painful. But whatever.


[cid:e8ee0fef-08e7-42fc-a5f2-0ec82267b9db]<http://www.computerexpertsgroup.com/>
Michael Schechter​​
President
t: 914-644-6471<tel:914-644-6471>
e: ***@***.******@***.***>       |      w: www.computerexpertsgroup.com<https://www.computerexpertsgroup.com/>
[Twitter]<https://twitter.com/cxgtweet>
[Facebook]<https://www.facebook.com/Computer-Experts-Group-Ltd-312170305462291/>
[LinkedIn]<https://www.linkedin.com/company/computer-experts-group-ltd./>
Schedule a call with me:<https://calendly.com/cxgl/confab> https://calendly.com/cxgl/confab
________________________________
From: Dan ***@***.***>
Sent: Monday, October 31, 2022 3:53 PM
To: amidaware/tacticalrmm ***@***.***>
Cc: Michael Schechter ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]:Re: [amidaware/tacticalrmm] Hostnames sometimes change to wrong name unexpectedly (Issue #1338)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


thank you so yes that means a single db entry. so sounds like browser issue on linux since you said on windows, no issue?

**Comment by silversword411** [comment]
Linux browsers are known to be glitchy, NiceGuy has problems with them all the time. 

How to track down a linux only browser bug...going to be tricky.

**Comment by cxgl** [comment]
OK. This is good to know. I'll just preemptively give up.

OK -- so let's call this one closed. You all have my undying appreciation. And soon we'll up our game to the code-signing level for mac and linux agents...

Thanks!

[cid:a8d9a270-4c66-4ce9-ba42-c0b5a1de963b]<http://www.computerexpertsgroup.com/>
Michael Schechter​​
President
t: 914-644-6471<tel:914-644-6471>
e: ***@***.******@***.***>       |      w: www.computerexpertsgroup.com<https://www.computerexpertsgroup.com/>
[Twitter]<https://twitter.com/cxgtweet>
[Facebook]<https://www.facebook.com/Computer-Experts-Group-Ltd-312170305462291/>
[LinkedIn]<https://www.linkedin.com/company/computer-experts-group-ltd./>
Schedule a call with me:<https://calendly.com/cxgl/confab> https://calendly.com/cxgl/confab
________________________________
From: silversword411 ***@***.***>
Sent: Monday, October 31, 2022 4:26 PM
To: amidaware/tacticalrmm ***@***.***>
Cc: Michael Schechter ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]:Re: [amidaware/tacticalrmm] Hostnames sometimes change to wrong name unexpectedly (Issue #1338)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Linux browsers are known to be glitchy, NiceGuy has problems with them all the time.

How to track down a linux only browser bug...going to be tricky.
