### ISSUE TITLE
Problematic apostrophe.

### ISSUE THREAD

**Issue by cm-slu** [amidaware/tacticalrmm#1345]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version : Latest

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):2.4.1
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]: All Windows

**Describe the bug**
The terminator ' is missing from the string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
   ception
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**To Reproduce**
1. In description of agent add apostrophe ( ' )
2. In script add an argument agent.description

**Screenshots**
![image](https://user-images.githubusercontent.com/82769965/200615910-78935fe7-44b0-4f96-b515-55d3a885c7b6.png)

**Comment by silversword411** [comment]
Should there be a test in the repo for testing chars in fields?

Should probably have input validation everywhere for all chars...like null space chars and all the other weird chars

**Comment by wh1te909** [comment]
@cm-slu I have pushed a fix please see the linked commit and manually make the change on your server and then `sudo systemctl restart rmm` and please test it out and let me know if it works

@silversword411 a unit test would not catch it, need an end to end test to run on a real agent

**Comment by cm-slu** [comment]
Hello, and thank you very much for the correction.

I prefer to wait for the release, I'm not sure I know how to patch the version.

**Comment by wh1te909** [comment]
@cm-slu it's released now
