### ISSUE TITLE
linux agent disconnect after seconds

### ISSUE THREAD

**Issue by alez404** [amidaware/tacticalrmm#1354]
**Server Info :**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.15.3

**Installation Method:**
  - [x] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.4.2
- Agent OS: Ubuntu 20.04

**Describe the bug**
when i install linux agent app on my linux vps, it connect to RMM panel and show in this panel but after some seconds the vps will disconnect and i cant do anything with RMM on that VPS
how can i get some logs for debug the problem?  or what shuld i do for fix the issue?

**Comment by wh1te909** [comment]
sign up for code signing and use the official linux agents, anything else is not supported: https://docs.tacticalrmm.com/code_signing/
