### ISSUE TITLE
Adding ability to search for serial number in Agent list view

### ISSUE THREAD

**Issue by Vaultpls** [amidaware/tacticalrmm#1355]
**Describe the solution you'd like**
I'd like to be able to search for serial numbers in the Agent list's search box which I assume the search feature is searching the Agent's Summary page.
It'd be nice for internal auditors/inventory specialists to have a dumbed down account to just search for serial numbers to see if they are active/who is and was last using the device.

**Describe alternatives you've considered**
I've considered doing backend searching but that isn't too friendly for non-IT folk.

Under my machines that I have, looking for the serial in BIOS -> Serial Number comes up as the most reliable way of finding the device's serial so I'd like to see that also shown on the summary page :)

**Comment by davidebonavita** [comment]
+1

**Comment by wh1te909** [comment]
just added serial number to the dataset that's part of search so it will filter now when searching for it, will be in next release.
