### ISSUE TITLE
Agent Status | Checks Status

### ISSUE THREAD

**Issue by JSuenram** [amidaware/tacticalrmm#1357]
**Is your feature request related to a problem? Please describe.**
We have an employee who starts using TRMM, he complained that he has problems to differ colors "red/green blackout".
Checks Status is always the same icon, regardless if a check failed. It just changes to yellow or red which is for some people hard to see.

However, when you are in the Checks pane you can see green Checkmark, yellow ! and red X.... so this is not really "consistent" GUI-Design.

Also connection state shows always the same icon but with different colors. Same issue. But here it would be nice for example to have different Icons and make "respect" Latency. So if you already use a signal-strength icon, it should honor signal strength. Maybe ping above 100ms gets yellow and one line less and so on....

**Describe the solution you'd like**
Icons should differ for states and colors. Should be consistent in Overview and Details pane.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/68963439/204303783-08f0d28b-a80a-4944-9345-d40170af5b41.png">
<img width="239" alt="image" src="https://user-images.githubusercontent.com/68963439/204303803-e430efbf-5940-406a-b753-fcf47f47b483.png">
<img width="50" alt="image" src="https://user-images.githubusercontent.com/68963439/204303824-8a884540-a798-4a88-8255-213c416e43d0.png">

**Comment by silversword411** [comment]
I think your employee might have an understanding of the logic of the icons (ignoring being able to see the yellow/red/green colors). 

<img width="647" alt="2022-11-29_231213 - status icons" src="https://user-images.githubusercontent.com/13395348/204706537-d46790fb-e477-4fad-a3a2-97942b079458.png">

On the last if you want to write up an independent feature request for the icon having more/less bars as a connection latency indicator I guess that's a possibility...of marginal benefit.

**Comment by silversword411** [comment]
Unless I'm missing something, going to close this.
