### ISSUE TITLE
Bug: running scripts and sending commands on Microsoft Exchange Servers

### ISSUE THREAD

**Issue by rawbyne** [amidaware/tacticalrmm#1359]
**Server Info (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: chrome 108
 - RMM Version (as shown in top left of web UI): 0.15.3

**Installation Method:**
  - [ ] Standard
  - [x] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.4.2
- Agent OS: Windows Server 2016

**Describe the bug**
If I run a powershell script on this server, which is an exchange-server, I get the following error:
exec: "Powershell": cannot run executable found relative to current directory

I reinstalled the wohle agent, the powershell.exe is available in c:\windows\system32, DISM and SFC Check made with no problems, Server has been restarted several times.

**To Reproduce**
Because I do not know, how the procedure looks like to start the powershell script, I can not reprocedure this. On all other systems I got, the scripts start, but not on this.

**Expected behavior**
The scripts should run.

**Screenshots**
no

**Additional context**
none

**Comment by dinger1986** [comment]
What happens if you try and run a powershell command via send command or remote background?

**Comment by rawbyne** [comment]
Wow. You are fast ;-)

The terminal starts. If I type "powershell", powershell terminal starts. So no problem

**Comment by dinger1986** [comment]
Did you try right clicking on the agent and then send command, choose powershell and even just send a ping command

**Comment by rawbyne** [comment]
If i use "send command", then use "powershell", command = "ping 1.1.1.1", I get a "bad request" after Timeout.

**Comment by dinger1986** [comment]
Can you share a screenshot?

Does this work in other 2016 servers for you?

**Comment by rawbyne** [comment]
More info about AV: AV = Defender, Path Exclusions are set. 
c:\program files\Mesh Agent
C:\program files\TacticalAgent
c:\programdata\TacticalRMM

**Comment by rawbyne** [comment]
![screenshot](https://user-images.githubusercontent.com/12291375/205257300-fec1ed7b-1c8b-449b-a382-1341a8f1e727.png)
![screenshot2](https://user-images.githubusercontent.com/12291375/205257573-499b932e-4c15-47fc-802b-0498f8636bfa.png)

**Comment by dinger1986** [comment]
Try the same command with cmd please

**Comment by rawbyne** [comment]
I got no Problems on all other servers.

CMD = Same error

**Comment by rawbyne** [comment]
I setup an account for you, if you want to test!

**Comment by dinger1986** [comment]
Are they showing online? If you cant use send command for cmd or powershell there's something wrong and scripts won't run.

Click through the tabs in remote background do they all load?

**Comment by dinger1986** [comment]
> I setup an account for you, if you want to test!

I could maybe this evening.

**Comment by rawbyne** [comment]
All loading. Agent is online. No other problems, but the scripts....
How to give the credentials to you?

**Comment by dinger1986** [comment]
Best on discord

**Comment by rawbyne** [comment]
Could you please send me a mail at rawbyne@gmail.com
I do not use discord

**Comment by rawbyne** [comment]
Ola. Did you find something?

**Comment by dinger1986** [comment]
I replied yesterday, I don't have permissions to see/run anything

**Comment by rawbyne** [comment]
Sorry, now you are admin

**Comment by dinger1986** [comment]
Thanks, I just logged in there, this seems to be an issue on all your exchange servers (I searched for `EX` in the search box), I right clicked and clicked `send command`, then `ping 8.8.8.8` and `send`. On every single one they time out, 2012 r2, 2016 and 2019. 

I have one client who also has an exchange server (most are on 365 now) and I can confirm the same behaviour, Ill discuss it and get back to you if we need access again but for now please close my account.

**Comment by dinger1986** [comment]
can you also rename this to `Bug: running scripts and sending commands on Microsoft Exchange Servers`

**Comment by dinger1986** [comment]
@rawbyne I edited above as I checked the running scripts and its only one server thats giving the powershell error, its maybe worth checking the exclusions etc incase something is blocking powershell.exe execution, mesh background finds and executes powershell fine.

**Comment by rawbyne** [comment]
Hi there, I checked the exclusions. All is fine.

**Comment by rawbyne** [comment]
![Screenshot 2022-12-06 131928](https://user-images.githubusercontent.com/12291375/205910936-c61e7c28-3628-4f53-9f93-69320c587d09.png)

**Comment by dinger1986** [comment]
thanks @rawbyne made progress and testing fix on machines prior to rolling out an update
