### ISSUE TITLE
Remote console access

### ISSUE THREAD

**Issue by btrfs-d** [amidaware/tacticalrmm#1364]
**Is your feature request related to a problem? Please describe.**
I haven't found the current iteration of remote command execution to be robust enough. 

**Describe the solution you'd like**
I'm looking for a way to interact with a shell on the remote device. Something in real time, vice the current "Run a script or bash command" implementation. Being able to have multiple shells/remote sessions open in something a terminal multiplex akin to tmux would be the ideal version of this, in the event of needing to manage multiple endpoints at a time. 

**Describe alternatives you've considered**
I use tmux with ssh when I'm connected to my LAN, but obviously an RMM is built for remote management. When I'm OOB, the current "Send command" implementation doesn't quite do it for me. Datto RMM has a remote console that works very well in Windows (CMD and PowerShell), macOS (Bash or Zsh), and Linux (Whichever shell is default).

**Additional context**
No additional context.

**Comment by dinger1986** [comment]
have you tried the terminal in remote background?

**Comment by wh1te909** [comment]
yep what @dinger1986 said, right click on an agent and "Remote Background"

**Comment by dinger1986** [comment]
![remote background](https://user-images.githubusercontent.com/7244447/206040878-ba324748-d239-4ad9-8545-bf48fcefbe94.gif)

**Comment by btrfs-d** [comment]
@dinger1986's suggestion was the feature I was looking for. Maybe a tweak of the action name would be fitting to help others find this feature in the future? Something like "Remote Console" or "Remote Terminal"? I'm not a dummy (by a small margin) but "Remote background" did not even register with me for some reason.

Otherwise, this works perfectly. Thank you @dinger1986 and @wh1te909.

**Comment by btrfs-d** [comment]
Thank you both, I will be closing this issue.
