### ISSUE TITLE
v0.15.4 upgrade "broke" automated tasks

### ISSUE THREAD

**Issue by stavros-k** [amidaware/tacticalrmm#1366]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10]
 - Browser: [e.g. chrome, safari]
 - RMM Version (as shown in top left of web UI):

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
Automated tasks show empty env vars (` `) instead of `[]`
Because of that tasks do not execute and result in a 500 status code.

Top: how it was after upgrade
Bottom: How it it after re-adding

<img width="607" alt="image" src="https://user-images.githubusercontent.com/47820033/206248537-af0009ba-6239-46df-a78f-4534caa4826b.png">

More detailed info in https://discord.com/channels/736478043522072608/1050090372719718411

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by stavros-k** [comment]
Note: This is only an issue on the **previously** created tasks, not new!

New tasks works fine

**Comment by wh1te909** [comment]
thank you, fixed in 0.15.5 I added a migration for older tasks to get them into the newer format
