### ISSUE TITLE
Documentation Fail2Ban Issue

### ISSUE THREAD

**Issue by christophsanz** [amidaware/tacticalrmm#1370]
The regex for the fail2ban filter in the documentation is not ideal. 
I have a device with "200" in its name, which triggers the ignoreregex resulting in not being banned.
My suggestion would be to change it to:
```
tacticalfail2banfilter="$(cat << EOF
[Definition]
failregex = ^<HOST>.*400.17.*$
ignoreregex = ^<HOST>.*200.\d+.*$
EOF
)"
sudo echo "${tacticalfail2banfilter}" > /etc/fail2ban/filter.d/tacticalrmm.conf
```

**Comment by dinger1986** [comment]
nice! do you want to submit a PR? If not happy to change it.

To be  honest with you when I put that together I spent about 3 hours playing with regex and after testing it worked fine for me so wrote it up and wrote a script for it.

**Comment by christophsanz** [comment]
Sry, didn't see there is a repo for the docs, will submit a PR.
No worries, thank you for putting it in the docs, would have taken me much longer to figure this out myself.
Thank you :)

**Comment by dinger1986** [comment]
added in PR https://github.com/amidaware/trmm-docs/pull/114/commits/413bd961014291e2034d14273289b5895077e746.

Thank you!
