### ISSUE TITLE
Add indicator showing the type of script: custom, community, WIP

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1374]
**Is your feature request related to a problem? Please describe.**
When improving the community scripts, often times the process is to clone the script. TRMM will prepend "(Copy)" to the name but nothing else. It doesn't prevent you from naming the script the same as the community script.

**Describe the solution you'd like**
It would be nice if there was an indicator to show which scripts are "custom" and which ones are community driven. This could be accomplished by changing the font color or adding a small light (icon?) to indicate where the script came from.

**Describe alternatives you've considered**
Currently, I append "(Mine)" to the script name. I also make heavy use of the favorites.

**Additional context**
This screenshot shows the problem.

![image](https://user-images.githubusercontent.com/7763429/207076309-2c7f4f14-bd24-4d11-b588-e8b2585ae202.png)

**Comment by NiceGuyIT** [comment]
> The Category "TRMM (LINUX) checks" isn't an indicator it's a community script?
It's not an indicator because you can add any custom script to any category. Nothing in TRMM indicates that I wrote the script vs it coming from the community other than the "Hide Community Scripts" button at the top, and that acts like a filter, not an indicator.

**Comment by silversword411** [comment]
I used all my years of experience with kludging to try and establish a base with what I had to work with so you could tell established vs your own scripts. 

Using naming conventions, and category names, that said we're working with non-enforced boundaries.

All we have ATM is hide/show community scripts.

Probably best to write up an enhancement request to have some other reasonable indicators...did I already write up one that talks about colors, and icons and a column with last modified date?

Hmmmm

**Comment by NiceGuyIT** [comment]
I want to make it clear this is not just the scripts window, but any reference to the scripts like right click > Run a Script or adding a new script check in automation manager as shown in the screenshot. If the name is the same, there's no way to tell which one you're running.
![image](https://user-images.githubusercontent.com/7763429/207868879-e50999d1-04ee-47de-a3f9-4de0eb730fc8.png)

**Comment by silversword411** [comment]
> The Category "TRMM (LINUX) checks" isn't an indicator it's a community script?

Personally till there's other options I do use categories for that purpose. When I clone, I usually put it into testing while I'm working/polishing things. 
Then when it's done I re-categorize to my own categories. I never reuse the category naming format I created for Community scripts so they don't get mixed in and I can sort and find stuff.

![2022-12-16_080100 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/208104438-d24e1002-5834-47bf-a1b8-ae959c2c9184.png)

**Comment by NiceGuyIT** [comment]
Categories aren't shown in my previous screenshot. I'll probably use something like I do for Bitwarden where `{categories}`, `[groups]`, `<tags>` or `(general)` info is appended/prepended to the name.

Then again, I can just add an emoji to my scripts!
![image](https://user-images.githubusercontent.com/7763429/208121260-73a07b5a-2dd6-4657-975d-d6adcc6df794.png)

**Comment by silversword411** [comment]
Oh yeah....no categories displayed in the picker...I do the first letters of the name to PCR when it's prod-ready.

Emoji....I LIKE :D

**Comment by bbrendon** [comment]
>
> I delete a lot of the built in scripts that I know I’ll never use. It gets
rid of a lot of clutter and I know I can reference them on github if I ever
need to. But #unsupported

>
>

**Comment by silversword411** [comment]
Will be in next release
https://github.com/amidaware/tacticalrmm-web/commit/1299bfc93ea5fd4ebe8c4cb69bf4272910bb8aec
