### ISSUE TITLE
How does Tactical RMM generate Linux/MacOS Installers?

### ISSUE THREAD

**Issue by AshleyJackson** [amidaware/tacticalrmm#1377]
Hello,

I've been trying to download a Linux installer however it keeps failing with the following error in the Network tab:
```
"Missing code signing token, or token is no longer valid. Please read the docs for more info."
```

The payload being sent to the server is:
![image](https://user-images.githubusercontent.com/12793989/207507519-f81a6e4e-5a50-447d-bb4b-f422110fa224.png)

Does the below code only generate .exe files? Is it also meant to generate other installation scripts? Or am I just being an idiot and looking in the wrong location?

https://github.com/amidaware/tacticalrmm/blob/f3e44cf45870130f859dcda7836940ffef00607d/api/tacticalrmm/clients/views.py#L349-L380

Thanks.

**Comment by wh1te909** [comment]
you need to be sponsor for linux/mac agents: https://docs.tacticalrmm.com/code_signing/

**Comment by wh1te909** [comment]
it's here https://docs.tacticalrmm.com/faq/#linuxmacos-agents
I can add a link to this in the error message so it's more clear

**Comment by jeekkd** [comment]
Hello, I just ran into this and I too was confused why I could not generate a linux agent installer. It was only after finding this thread was this issue explained. Please update the error message to be more descriptive
