### ISSUE TITLE
Install and manage Tactical purely on internal network

### ISSUE THREAD

**Issue by NeodymiumPhish** [amidaware/tacticalrmm#1383]
Hi,

Similar to the issue (https://github.com/amidaware/tacticalrmm/issues/257), I am trying to run Tactical purely through my personal Tailscale network. This would mean there is no need for a public domain or external port management. 

Is this possible? The documentation implies that configuring the DNS and subdomains is required to continue.

Thanks!

**Comment by dinger1986** [comment]
It has already been answered in #257

yes you need public resolvable dns as you need a real certificate exactly the same as 

This is for NATS to work which is an integral part of the agent communications.

You dont need to port forward.

Closing now, feel free to create a discussion or join discord if you need assistance
