### ISSUE TITLE
Bulk Management of Agents

### ISSUE THREAD

**Issue by matthewogrady** [amidaware/tacticalrmm#1388]
Ability to Change Machine Type in bulk
Ability to Delete Multiple Agents at once
Ability to Dynamically assign Agents to Sites based on certain criteria, IP subnet, Domain, ect..
Ability to Bulk enable Monitoring to email, text ect... 
Ability to Filter views based on criteria, OS, IP, Hostname, Software installed ect...

**Comment by dinger1986** [comment]
Some of these are covered in #976 and #1149, please add to these

**Comment by silversword411** [comment]
Closing as duplicate
