### ISSUE TITLE
Need feature to customize columns of host list!

### ISSUE THREAD

**Issue by leeryst** [amidaware/tacticalrmm#1392]
Hello! If it possible - need opportunity to customise columns on hosts list, especially, with custom fields. Then we can use it in filters and sorting probblems will solve.
![image](https://user-images.githubusercontent.com/121777850/210191137-1d5328a6-5da3-4e7b-b924-e338e7fea266.png)

Thanks!

**Comment by silversword411** [comment]
Dupe
https://github.com/amidaware/tacticalrmm/issues/308
