### ISSUE TITLE
Technician access by customer

### ISSUE THREAD

**Issue by WaffleBoyQc** [amidaware/tacticalrmm#1393]
I sometimes have certain customers who ask me if it is possible to have an access to see their entire computer park.
It might be useful to have a function that allows limited access per site. 
Would it be possible to put individual accesses by client so that they can have a control on their computer park.

**Comment by dinger1986** [comment]
You can already do this with the permissions manager. Mesh however has complete control unless you tick the box and create mesh users per user

**Comment by WaffleBoyQc** [comment]
Nice well.. looks like TRMM is perfect !
