### ISSUE TITLE
Prevent notification while service is shutting down

### ISSUE THREAD

**Issue by Nyphew** [amidaware/tacticalrmm#1396]
**Is your feature request related to a problem? Please describe.**

I'm always frustated when I receive a mail notification about a monitored service failing while the whole computer is shutting down.

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/83342905/210844311-e3e51476-2164-4907-b97a-1dfdc599bdd0.png">

**Describe the solution you'd like**

I'd like it to be ignored (or "passed") like the option we have for "start pending".

<img width="575" alt="image" src="https://user-images.githubusercontent.com/83342905/210844370-ea960bcb-c3f2-42f1-8b4d-092ddab3d564.png">

**Describe alternatives you've considered**

Nothing.

// BTW

Thanks for your beautiful piece of software and happy new year !

**Comment by silversword411** [comment]
Not sure how we'd detect a "shutting down".

Why don't you increase the number of consecutive failures to 2 to avoid the alert?

**Comment by dinger1986** [comment]
That is a very good idea!! 

I'm changing all mine to do that now.

I guess if TRMM service shut down first it wouldn't detect anything wrong but hard to control and being fair to have a delay of max 5 mins wouldn't do any harm!

**Comment by emtek-at** [comment]
> Not sure how we'd detect a "shutting down" scenario

You could look after EventId 1074 from User32

**Comment by Nyphew** [comment]
> Not sure how we'd detect a "shutting down" scenario, and you're getting as many alerts as you are because your running this at defaults (0 seconds) which unless you've changing things, is 120 seconds.
> 
> Why don't you increase the number of consecutive failures to 2 to avoid the alert?

Thanks all for your reply and suggestions. I did not think to use the "consecutive failures" option.

IMO, as the state is visible in TRMM (see my inital screenshot after the link "show run history"), I tought you could look for the string "Un arrêt système est en cours." (in french) to add conditions for example.

**Comment by silversword411** [comment]
Workaround provided. No other way to fix
