### ISSUE TITLE
Feature Request: Monthly Patch Policy Automation

### ISSUE THREAD

**Issue by rawbyne** [amidaware/tacticalrmm#1399]
Hi there,
we install our Updates generally on the 3rd friday in every month. This can not be set in the automation manager. It would be nice, if there would be a possibility to set a custom shedule like crontab. In my opinion this custom crontab could be at every shedule tab in the whole system. 
![Screenshot 2023-01-09 084436](https://user-images.githubusercontent.com/12291375/211260622-8a65ad4f-d2d7-459b-9d00-ea54817ee597.png)

**Comment by wh1te909** [comment]
linking to https://github.com/amidaware/tacticalrmm/issues/1188 as part of the patching rework

for now you can use an automated task with a powershell script to do this
