### ISSUE TITLE
Feature Request: Increase the size of Notes text box

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1407]
**Is your feature request related to a problem? Please describe.**
The Notes text box is too small and hard to read the text because I can't increase the width horizontally.

**Describe the solution you'd like**
It would be more useful if the text area was larger to accommodate larger text blobs. I only noticed this with the Notes text box. I don't know if other text boxes would benefit from the increased size.

**Describe alternatives you've considered**
This UserStyle increases the size of the text box to 90% of the viewport.

```text
/* ==UserStyle==
@name           TacticalRMM
@namespace      github.com/NiceGuyIT
@version        1.0.0
@description    TacitcalRMM
@author         NiceGuyIT
==/UserStyle== */


@-moz-document regexp("https://rmm\\..*") {
    /* Insert code here... */
    .q-dialog-plugin__form {
        max-height: inherit;
    }
    
    div > div.q-dialog > div.q-dialog__inner > div.q-dialog-plugin {
        width: 90vw !important;
        max-width: 90vw !important;
        /* Optional */
        background: darkslateblue;
    }
    
    div > div.q-dialog > div.q-dialog__inner > div.q-dialog-plugin .q-textarea textarea {
        height: 80vh;
    }
    
}
```

**Additional context**
Here is the maximum size of the text box showing both the inner box scroll bar and outer dialog scroll bar.

![image](https://user-images.githubusercontent.com/7763429/213271159-4502f9e5-ea2f-4f32-ab8a-80e3326c6e1f.png)

Using the UserStyle above, I'm able to increase the size to the size of the Notes box to the size of the screen. This greatly improves the readability for large blobs of text. Note: Color was added to visually show the notes box.

![image](https://user-images.githubusercontent.com/7763429/213271703-bba6a27c-fa67-4ad0-979d-446d58b8fe51.png)

**Comment by wh1te909** [comment]
done will be in next release
