### ISSUE TITLE
Header with name or date not found

### ISSUE THREAD

**Issue by 3gmgithub** [amidaware/tacticalrmm#1408]
**Server Info (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): v0.15.7

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Describe the bug**
eMail alert is missing a name caused the error: Header with name or date not found is
This error is from the mailgate receiver in GLPI, but I suspect other eMail systems may cause this issue

**To Reproduce**
Send a test email or any alert using standard SMTP

**Expected behavior**
Add full email header information to correct the issue

**Comment by 3gmgithub** [comment]
This issue can be closed.  I changed hosts and the issue no longer applies.
Looks like the crappy shared hosting email does not provide correct header information.

**Comment by 3gmgithub** [comment]
There may still be an issue with the code as I switched to MailGun (Which is working) and they do replace invalid headers.

**Comment by wh1te909** [comment]
the code doesn't do anything with headers so not sure what you mean by issue with the code. pretty obvious that it's an issue with the provider and not trmm

**Comment by 3gmgithub** [comment]
Since there are missing items in the header, that is the problem.  The name was missing.

**Comment by silversword411** [comment]
> The name was missing.

What "name" are you talking about? 

I self host my mail server and it delivers from TRMM just fine.

Show full email headers, highlighting what you think is missing.

**Comment by 3gmgithub** [comment]
Good to know about the self-hosted email service.  I can only find a missing name.  However, that should not cause an issue.  The mail receiver in GLPI I was using could also have a bug, which I just looking into, but they claim to have fixed it for this issue.  Since by switching providers, I was able to avoid the issue, I, unfortunately, cannot spend more time right now on this.  I will close the issue for now, but when I have the time I will revisit and reopen it if necessary.  Thank you all for your help!
