### ISSUE TITLE
Feature Request: Blank Remote Computer Screen 

### ISSUE THREAD

**Issue by i7phillip** [amidaware/tacticalrmm#1410]
We're still a little new to Tactical. Previously, we used Atera. With Atera, we had the option to black the users screen when we remoted in  to a computer/server. Is this something Tactical could implement?

**Comment by dinger1986** [comment]
this isnt possible with meshcentral, it is a feature request with them https://github.com/Ylianst/MeshCentral/issues/416

You can of course use other remote control options which offer this. I would assume connectwise does https://docs.tacticalrmm.com/3rdparty_screenconnect/#screenconnect-connectwise-control
