### ISSUE TITLE
Github does not want me to sponsor any more (drops PayPal). Alternative?

### ISSUE THREAD

**Issue by forti42** [amidaware/tacticalrmm#1416]
In some way this is a feature request,..

As Github drops PayPal from sponsoring (only), I cannot use it any more. 
I don´t really like PayPal, but in this case it´s my only option. And I guess I´m not the only one.

Will there be an alternative?

**Comment by wh1te909** [comment]
yes i'll be emailing existing sponsors and updating docs over the next couple weeks with alternative ways to sponsor

**Comment by wh1te909** [comment]
@forti42 you can now sponsor directly via Paypal or Stripe: https://docs.tacticalrmm.com/sponsor/#sponsor-with-paypal-or-stripe
