### ISSUE TITLE
silent still shows CMD window

### ISSUE THREAD

**Issue by lolcakes69** [amidaware/tacticalrmm#1427]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10] Debian 11
 - Browser: [e.g. chrome, safari] firefox
 - RMM Version (as shown in top left of web UI): v0.15.7

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Describe the bug**
running agent installer with -silent argument still pops up CMD window. not sure if this is expected behavior or not even with the -silent argument. the message that says installation was successful doesn't pop up, but i was expecting the -silent argument to hide the CMD window as well
this happens if i run it through CMD or powershell
CMD: C:\Users\temp\Desktop>trmm.exe -silent
powershell: Start-Process "C:\Users\temp\Desktop\trmm.exe" -ArgumentList '-silent' -PassThru

**To Reproduce**
1. run installer with -silent argument

**Expected behavior**
again, not sure if the CMD window popping up with the below info is still expected even with -silent argument, but i was expecting it to be truly silent/invisible

**Screenshots**
little blurry sorry
![image](https://user-images.githubusercontent.com/75548486/216806050-8409196f-065f-4013-b02a-3d2e0eb77813.png)

**Comment by wh1te909** [comment]
This is the expected behavior. Only message boxes are suppressed. If you want truly silent then run it from system via gpo or something, not from an interactive session.
