### ISSUE TITLE
install.sh in docker folder fails on linux

### ISSUE THREAD

**Issue by j-mir-prazak** [amidaware/tacticalrmm#1432]
https://github.com/amidaware/tacticalrmm/blob/ebbe90dfa8c808a2004ffb13a579567b5e0e7f4c/docker/tactical-cli#L57

there seems to be flipped expression ~= : should be insted =~

**Comment by wh1te909** [comment]
Hi, that script is actually not supposed to be used, it was just something we were working on back in the day but it's not complete or functional. The instructions for docker are here https://docs.tacticalrmm.com/install_docker/
