### ISSUE TITLE
Client side update notifications.

### ISSUE THREAD

**Issue by paynent** [amidaware/tacticalrmm#1435]
**Is your feature request related to a problem? Please describe.**
From the looks of it there are just two options when pushing updates to clients. Don't reboot. Or reboot immediately after patching. Neither are good options when trying to keep things up to date.

**Describe the solution you'd like**
ConnectWise Automate(labtech) has a feature to where it will detect if a user is logged in and if not it will reboot. If a user is logged in you have the option to set a time where the machine will auto-reboot. and once patches are complete a pop-up will display telling a user that they have until x time to save their work and reboot for updates or it will be done for them. If they chose to delay it will then pop up say an hour later (or whatever you set it to) and repeat this process until the user chooses to reboot or the set time runs or no users are logged on.

IMO this is essential for any workstation patching. 

**Describe alternatives you've considered**
I've looked at doing some work with PowerShell on this and I've got a somewhat okay thing going, but it requires multiple scripts and its not clean.

**Additional context**

**Comment by silversword411** [comment]
There is a script that will do the popup and notification with reboot request

https://github.com/amidaware/community-scripts/blob/eaf62b855c3994de5296e40d683fc803f0528dd0/scripts_wip/Win_Toast_Reboot_Request.ps1

However it is not integrated into the TRMM patching system at this time. This enhancement request should go on this issue (which I've done) which is our windows update rework tracking system https://github.com/amidaware/tacticalrmm/issues/1188
