### ISSUE TITLE
From the Software list on a computer it would be nice to have option to uninstall an application

### ISSUE THREAD

**Issue by cwhitmore88** [amidaware/tacticalrmm#1437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dinger1986** [comment]
Can you complete the template please?

**Comment by silversword411** [comment]
I'm going to search to see if this is already in the issues but it's definitely a tricky proposition because of all the different install systems out there. There is a uninstall script in the script library that will let you do some uninstalls. Takes a bit of work though.

**Comment by dinger1986** [comment]
The only way I can see to do it is convert the software to choco or use winget

**Comment by cwhitmore88** [comment]
Thanks dinger1986 and silversword411. I'll checkout the script.
