### ISSUE TITLE
Tactical RMMv0.15.7 linux agent install issue

### ISSUE THREAD

**Issue by ehinkle27** [amidaware/tacticalrmm#1438]
**Server Info (please complete the following information):**
 - OS: Debian 11]
 - Browser: Firefox]
 - RMM Version (as shown in top left of web UI): v0.15.7

**Installation Method:**
  - [ x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: linux]

**Describe the bug**
Just did a clean install of TRMM and was trying to download/create the installer for linux. When i clicked Agent>Install>agent.
Then I selected linux set the client, site, server token expire to 24 and arch 64 bits.

when clicking  download linux install script I get following error.

Missing code signing token, or token is no longer valid. Please read the docs for more info.
400: Bad Request.

Do I need to purchase cose signing for linux/mac?

![error-2-19-2023](https://user-images.githubusercontent.com/5144391/219995792-2a89026a-8e8f-47f5-9a2d-93fb71bbe6c1.jpg)

**Comment by wh1te909** [comment]
https://docs.tacticalrmm.com/faq/#linuxmacos-agents
