### ISSUE TITLE
Agent Installation GPO

### ISSUE THREAD

**Issue by Len-SVACS** [amidaware/tacticalrmm#1456]
Pretty new to Tactical so forgive me if this has been brought up previously.

Installing the Agent via group policy can be quite cumbersome. The ability to not have the agent expire would go along way here. If security is the main reason for this having an expiry at all to begin with then in this scenario you could potentially make the agent not expire, but then have a toggle to allow the agents to connect back into Tactical. Essentially a toggle to either accept or deny agents upon installation if the toggle is on/or off.

**Comment by Len-SVACS** [comment]
Great Idea. Thank you. I have tried setting the expiry higher but at the time the installation via GPO seemed to be hit and miss, this was most likely just my environment however. The user accounts on the devices I'm trying to deploy to are not administrators unfortunately and the agent requires admin

**Comment by silversword411** [comment]
I think this is solved, closing. Post if needs reopening
