### ISSUE TITLE
Custom Software Installers

### ISSUE THREAD

**Issue by Len-SVACS** [amidaware/tacticalrmm#1457]
Ability to add your own software installers into the software list. So that software that is not already listed can be listed and installed.

Would be nice.

**Comment by dinger1986** [comment]
You can use scripts for this atm or winget might have software that choco doesn't

**Comment by silversword411** [comment]
This is too vague a request, and you can definitely use the scripting library and script running to do choco and winget stuff already. 

Without further clarification closing as wontfix
