### ISSUE TITLE
External Authentication - LDAP/AD/SAML

### ISSUE THREAD

**Issue by hhydes** [amidaware/tacticalrmm#1477]
**Is your feature request related to a problem? Please describe.**
It is a little annoying when you have to manually create users and user details. Being able to use Central Authentication with groups that provide the required access (Either to specific features or Specific Client Access)

**Describe the solution you'd like**
It would be useful to be able to use external authentication with role based groups for accessing Tactical.

**Comment by dinger1986** [comment]
This is already requested in #508, please add there
