### ISSUE TITLE
Linux Agent is not fully functional anymore after upgrade to 0.15.9

### ISSUE THREAD

**Issue by 3gmgithub** [amidaware/tacticalrmm#1480]
**Server Info (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.15.9

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: Ubuntu 22.04

**Describe the bug**

**To Reproduce**
Right-Click Take-Control, no connect button
Installed on Two Ubuntu 22.04 Clients today different hardware

**Expected behavior**
Right-Click Take-Control should have a connect button

**Screenshots**
![See here](https://files.xtekcrypt.com/f.php?h=0QCh_ClJ&p=1)

**Additional context**
Already installed clients do have a connect button.
Remote background Terminal and File Browser do not work (No connect button), but processes do show.

**Comment by 3gmgithub** [comment]
Ok so I found that if I am remoted in using ScreenConnect and I install from the GUI the installation ends up like the description in this issue.  However, if I use SSH and install without the GUI it works fine.

**Comment by wh1te909** [comment]
did you try using the red "Recover Connection" button that should fix it, this happens when trmm doesn't have the mesh agent's id. the recover will resync it

**Comment by 3gmgithub** [comment]
I will give that a try the next time I encounter this.  Thanks!
