### ISSUE TITLE
New install can't access tactical url but can access mesh url

### ISSUE THREAD

**Issue by ioscanner** [amidaware/tacticalrmm#1485]
I did a first time new install.  Everything seemed to go ok.  Them went to connect to the tactical url and it doesn't show up.  The mesh url works.

I am not sure what version of tactical it is, but the mesh is 1.1.5 in the interface.

Installed on Debian 11.  Single IP with DNS for mesh and tac urls. 
Installation Method: Standard

I can get there by IP it seems, but when I try to login it tells me the backend is down. The nginx file looks correct.

**Comment by ioscanner** [comment]
I got it.  Seems the host file after install was wrong.  You put 127.0.0.1 tactical.server tac api.server mesh.server

Split them into 
127.0.0.1 tactical.server tac
127.0.0.1 tapi.server tapi
127.0.0.1 mesh.server.com mash

Seems it is a bug in the installer.

**Comment by dinger1986** [comment]
It's always worked fine for me and I have done installs probably in the 3 figures now

**Comment by ioscanner** [comment]
Just reporting what I found.  I was able to resolve it.  When I install the other location I will report if it does it again.  I did see someone else said something about the host file needing to be updated.  So maybe a patch broke it.

**Comment by silversword411** [comment]
Your problem is probably using AWS and it breaking network settings and cloudinit

https://docs.tacticalrmm.com/troubleshooting/#issues-with-agents-offline-after-reboot-or-new-install-on-aws-and-other-cloud-platforms-using-cloudinit-or-similar
