### ISSUE TITLE
* BUG To Generate Linux Agent

### ISSUE THREAD

**Issue by marcosaraujomvma** [amidaware/tacticalrmm#1492]
**Server Info rmm.neopath.com.br:**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version (0.15.9):

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Describe the bug**
I can not generate the Linux Agente on UI 
![image](https://user-images.githubusercontent.com/18758691/233819340-d6ee2bf5-7f44-4863-8a09-fb57981cf5bd.png)

**Comment by silversword411** [comment]
That's not a bug

https://docs.tacticalrmm.com/faq/#linuxmacos-agents
