### ISSUE TITLE
Ability to automate the installation of software through web interface

### ISSUE THREAD

**Issue by dcwalker3** [amidaware/tacticalrmm#1494]
**Is your feature request related to a problem? Please describe.**
Inability to auto-install software on newly added agents so that admins can make sure all machines have necessary software and if a user of said machine attempts to remove it. It would re-install it. To expand further on this maybe make a policy/template that admins can assign to agents such as workforce agents need to install office automatically, but development agents need to install a different set of tools automatically.

**Describe the solution you'd like**
The ability for Tactical RMM to check if a piece of software is installed and if not attempt to install it through chocolatey automatically.

**Describe alternatives you've considered**
The ability to have a condition for a script to run that would install said application. Such as:
if not google chrome installed:
    choco install googlechrome

**Additional context**
I am not sure if this is already available and I am missing it. I did go through documentation, but all I found were scripts on how to check if x application is installed where I was hoping something more through the web interface. If this is not possible I understand, and thank you for all your hard work.

**Comment by silversword411** [comment]
This can be done now with Choco (or Winget) and scripts...it could definitely use polish and features though.

**Comment by dcwalker3** [comment]
Okay, got ya and thank you for letting me know and the quick response. I figured it could be done with scripting on it's own, but I wanted to submit a feature request anyway in case it was in the works or maybe if it already existed, but I was unaware.
