### ISSUE TITLE
When trying to log into my RMM. I get a Too Many Redirects Issue

### ISSUE THREAD

**Issue by aelrod05** [amidaware/tacticalrmm#1502]
I just installed TacticalRMM on a VPS through Google Cloud. I am using Cloudflare to protect the Domain.

I try to login to my portal and receive an ERR_TOO_MANY_REDIRECTS on both Chrome and Safari.
I have tried the clearing cookies trick but I cannot find any cookies that are being used by the domain. Is anyone else having this issue or no?

Let me know what you need from me to show or do.

**Comment by aelrod05** [comment]
I may have fixed the issue myself. I had an A Record pointing to the root domain. I just removed it and It has cleared my Redirect Errors.

So to clarify.
IF ANYONE IS USING CLOUDFLARE FOR THEIR DOMAIN
Be sure to only have the api, rmm, mesh, subdomains routed (also your acme-challenge)

**Comment by wh1te909** [comment]
Turn off orange cloud for subdomains

**Comment by aelrod05** [comment]
> Turn off orange cloud for subdomains

I did, but I still encountered the issue. I did however restart the VPS and I haven't had the issue again. Ill leave the thread open and come back in 24 hours if the issue doesn't persist.
