### ISSUE TITLE
Windows Patch Management not working / no logging

### ISSUE THREAD

**Issue by felixtech-msp** [amidaware/tacticalrmm#1510]
**Server Info:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 113.0
 - RMM Version: v0.15.11

**Installation Method:**
  - Standard

**Agent Info:**
- Agent version: 2.4.8
- Agent OS: Windows Server 2019

**Describe the bug**
The "Install Approved Updates" button on Windows machines does not do anything. Updates are not installed, even after many hours of waiting.
I was completely unable to find any log files for the server and the agent. I cannot verify if the action is even sent to the agent or if the agent fails to execute the tasks.

**To Reproduce**
1. manually apply patches to any Windows Server 2019 or Windows 10
2. see how nothing happens
3. find out that log files do not exist for server and client

**Expected behavior**
Windows Updates being installed.

**Comment by silversword411** [comment]
Please review this

https://docs.tacticalrmm.com/howitallworks/#windows-update-management

Improvements to the system are planned. Unless you have a specific bug report, with screenshots of your policy, debug log, and other information pertinent to a specific problem I'm going to close this as invalid.

**Comment by felixtech-msp** [comment]
This link is not helpful at all. No information about anything.
The debug log is empty. There was never anything written to the debug log concerning updates. It just shows "No data available".
Log files in the filesystem basically do not exist. Files described here (https://docs.tacticalrmm.com/howitallworks/#log-files) are useless and on the agent side there is no log file written.

The Patch Policy is set to all auto approve, install daily, don't reboot, send e-mail when failed and it is applied to all machines.

I am unable to diagnose the issue mysef, because there are no log files on either side and the documentation is not helpful and I can't find any information if and how to enable proper logging.

Just closing an issue is stupid when a core feature is fundamentally bugged and diagnosing the issue is impossible due to lack of proper logging.

**Comment by silversword411** [comment]
Have you looked at #1188 ?

**Comment by wh1te909** [comment]
agent debug logging: https://docs.tacticalrmm.com/troubleshooting/#from-agent-install
from trmm web ui > debug log
server logs: `/var/log/celery/*` and `/rmm/api/tacticalrmm/tacticalrmm/django_debug.log`

**Comment by silversword411** [comment]
Also lots of logs in debug for me showing patching doing it's job

<img width="745" alt="2023-05-12_153711 - update logging" src="https://github.com/amidaware/tacticalrmm/assets/13395348/64b20e90-32a0-49e2-a7b0-9679d2d2be90">
