### ISSUE TITLE
Feature request: Accessibility theme options - Changing the colour of the Agent status indicator

### ISSUE THREAD

**Issue by Forpus** [amidaware/tacticalrmm#1514]
**Is your feature request related to a problem? Please describe.**
As a partially colour-blind person, it is really hard to tell the difference between "Agent status online" green indicator and "Agent status as offline" orange indicator on the admin frontend.

**Describe the solution you'd like**
Ability to change the colour of Agent status online/offline/overdue indicator, like it's done for the loading bar under user preferences.

**Describe alternatives you've considered**
Changing the colour code in the css by hand, but it will reset every update to tacticalrmm.

**Additional context**
Changed the Agent offline colour in:
/var/www/rmm/dist/assets/index.2b6aa7c5.css (the file ending might be different for others)
#f2c037 > #9316e1
![image](https://github.com/amidaware/tacticalrmm/assets/12444499/7a152805-0be0-4aad-97c9-133ce45a02e2)

**Comment by wh1te909** [comment]
this look good? I added options to change colors for all icons not just the offline.

https://github.com/amidaware/tacticalrmm/assets/7434746/808b2dc6-61d1-4a22-b5ab-a1f2f2fe6f0e

**Comment by Forpus** [comment]
Looks great!
Are the color codes writen on the (i) icon?
![image](https://github.com/amidaware/tacticalrmm/assets/12444499/b5f1a78a-4431-44b2-a0f8-906817857889)
Or can it be added as dropdown menu like on the Loading Bar Color?

**Comment by wh1te909** [comment]
Yes the icon links to the list of available colors which can be found here: https://quasar.dev/style/color-palette/

**Comment by Forpus** [comment]
Thanks, this will help the colour-blind people a lot! Or the fancy people!
:thumbsup:
