### ISSUE TITLE
Django Admin not loading css

### ISSUE THREAD

**Issue by myde2001** [amidaware/tacticalrmm#1524]
**Server Info (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): v0.15.12

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Describe the bug**
The Django Admin page doesn't load assets (css and js)

**To Reproduce**
1. Enable Django Admin Interface
2. Restart rmm
3. Go to Django Admin page

**Expected behavior**
The Django Admin Interface loading with the css and js.

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/93825819/10d10d22-7c08-4a6b-be57-84c4e4ce8452)

**Comment by wh1te909** [comment]
not able to reproduce. try `/rmm/api/env/bin/python /rmm/api/tacticalrmm/manage.py collectstatic --no-input` and if that doesn't work open browser console and see if it's complaining about missing css files or something

**Comment by myde2001** [comment]
Fixed it with that command, thank you.
