### ISSUE TITLE
Lets Encrypt using Cloudflare 

### ISSUE THREAD

**Issue by vithusel** [amidaware/tacticalrmm#1526]
**Is your feature request related to a problem? Please describe.**

Ability to use Certbot's Cloudflare integration to automate certificate renewals. I would set this up myself however, I wanted to confirm that this won't distrupt the applications working state. My dns is provided by Cloudflare and i noticed a lot of the documentation uses screenshots from cloudflare. Happy to create a PR to include this as a option in the installation script as im already working on a similar script for a private project.

**Comment by bbrendon** [comment]
Tactical uses certbot. Anything certbot supports will work.

There are links in the docs about doing this.

**Comment by vithusel** [comment]
> Tactical uses certbot. Anything certbot supports will work.
> 
> There are links in the docs about doing this.

Awesome thanks. I'll go ahead with testing it out
