### ISSUE TITLE
Feature Request - Create Tasks template

### ISSUE THREAD

**Issue by vithusel** [amidaware/tacticalrmm#1530]
Ability to create Templates that can be reused for Tasks. Will save a lot of time when you want to run multiple scripts (Say for Newly Onboarded Machines, or Application Patches)

**Comment by dinger1986** [comment]
whats wrong with automation manager?

**Comment by vithusel** [comment]
That is a good idea, However, I myself am using multiple automation policies for different purposes. Some of those overlap and others have completely unique setups. The task template feature would be beneficial to some to be able to add to tasks as a template direct to machines or Automation Manager.

**Comment by silversword411** [comment]
Currently, if I have something like that I put it as a manual task in automation manager, and just run when needed. Adds more items to the tasks list, but #GetsTheJobDone for now

**Comment by silversword411** [comment]
<img width="554" alt="2023-06-06_125858 - task template" src="https://github.com/amidaware/tacticalrmm/assets/13395348/9bb50409-0c41-4841-8049-b50106c23b0a">

**Comment by vithusel** [comment]
> Currently, if I have something like that I put it as a manual task in automation manager, and just run when needed. Adds more items to the tasks list, but #GetsTheJobDone for now

Agreed. Its what im doing currently. Maybe one day we could make that a feature though. I quite like the thought of it
