### ISSUE TITLE
"Install software" is missing a package that appears at chocolatey.org

### ISSUE THREAD

**Issue by moose999** [amidaware/tacticalrmm#1538]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: firefox
 - RMM Version (as shown in top left of web UI): v0.15.12

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.4.9 
- Agent OS: Win 10/11

**Describe the bug**
A package that appears on https://chocolatey.org/ is not available to install

**To Reproduce**
1. Go to software
2. Click on install
3. Search for remarkable

**Expected behavior**
I'd expect to see https://community.chocolatey.org/packages/remarkable

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/22505336/1e7d8d64-f712-4856-a23a-f7cc739b128c)

This package has only been on choco since Thursday, May 25, 2023 - do I need to refresh the choco package list somehow?

**Comment by silversword411** [comment]
Unfortunately the chocolately library in TRMM doesn't pull the live list of available software from https://community.chocolatey.org

This has yet to be...remedied

**Comment by moose999** [comment]
Hi,

I have installed the new update, and this software is still not listed. Is there a way to manually update the list?

Thanks,
Justin

**Comment by silversword411** [comment]
What package is missing?

In the mean time run the install as a script

```
Choco install -y packagename
```

**Comment by moose999** [comment]
Hi there,

The package is https://community.chocolatey.org/packages/remarkable 

All the best,
Justin

**Comment by wh1te909** [comment]
i updated the list with a few thousand new packages, will be in next release

**Comment by wh1te909** [comment]
released in 0.16.5

**Comment by moose999** [comment]
Sorted, many thanks indeed!

**Comment by ioscanner** [comment]
Is there a way to update without you having to push new packages into Tactical?  This is not very practical if I create a new package and need to push it out ASAP.  I have added new packages into Chocolatey and they are not showing in Tactical RMM Software either.

**Comment by wh1te909** [comment]
@ioscanner yes, you can manually add it to [this](https://github.com/amidaware/tacticalrmm/blob/develop/api/tacticalrmm/software/chocos.json) json file on your server  (just follow the same format) and then run the following [management command](https://docs.tacticalrmm.com/management_cmds/) to load it into your trmm database:

```
python manage.py load_chocos
```

**Comment by silversword411** [comment]
While you're at that...a PR to update the json for the missing package would be nice. :)
