### ISSUE TITLE
Updating installer to Debian 12 or/and Ubuntu 23

### ISSUE THREAD

**Issue by anc-tvr** [amidaware/tacticalrmm#1541]
Please, update the installer to Debian 12 and Ubuntu 23 or at least 22.04.

**Comment by dinger1986** [comment]
We are currently testing with Debian 12, as it’s just afew weeks old we want to make sure it’s stable prior to using it, can send you a link for our test installer if you want to test it for us?

**Comment by anc-tvr** [comment]
> We are currently testing with Debian 12, as it’s just afew weeks old we want to make sure it’s stable prior to using it, can send you a link for our test installer if you want to test it for us?
Yeah, you can put a link here to your test installer and I'll be happy to test it. I'll post the results here a bit later.

**Comment by dinger1986** [comment]
use this:

```
wget https://raw.githubusercontent.com/dinger1986/tacticalrmm/develop/install.sh
chmod +x install.sh
./install.sh
```

**Comment by anc-tvr** [comment]
Thank you for quick response! Today I've tested the updated installer, everything was installed without any problems and at first glance everything works fine! But while installing the installer gave the following:
```
Creating database for the rmm
--------------------------------------------------------------------------------
could not change directory to "/home/tactical": Permission denied
CREATE DATABASE
could not change directory to "/home/tactical": Permission denied
CREATE ROLE
could not change directory to "/home/tactical": Permission denied
ALTER ROLE
could not change directory to "/home/tactical": Permission denied
ALTER ROLE
could not change directory to "/home/tactical": Permission denied
ALTER ROLE
could not change directory to "/home/tactical": Permission denied
GRANT
```
I have no clue how it affects to RMM usage and whether it will affect at all.

**Comment by anc-tvr** [comment]
> Were you able to log in ok? If so its fine as its the main DB, I can only assume as its running the command as the postgres user it wouldnt have permissions on `/home/tactical` so shouldnt be an issue. did you log the install maybe?

Yep, I've successfully logged in. I'll test the system and if something goes wrong, I'll write here about it.

**Comment by dinger1986** [comment]
ok perfect, thanks for the feedback

**Comment by wh1te909** [comment]
official support for debian 12 / ubuntu 22.04 is now in release 0.16.0
