### ISSUE TITLE
Notifications via Telegram

### ISSUE THREAD

**Issue by anc-tvr** [amidaware/tacticalrmm#1542]
It would be great if there was the possibility of notifications via Telegram.

**Comment by ssteeltm** [comment]
Maybe we should have a webhook instead, so anyone could integrate with anyrhing

**Comment by anc-tvr** [comment]
> Maybe we should have a webhook instead, so anyone could integrate with anyrhing

How can I do this? Is there any guide?

**Comment by silversword411** [comment]
I tried working thru this, but not working yet....
https://polarclouds.co.uk/send-telegram-from-powershell/

Maybe you'll have more luck

**Comment by dinger1986** [comment]
Why not PR your changes or make it an option between sms and WhatsApp?

**Comment by ssteeltm** [comment]
> Why not PR your changes or make it an option between sms and WhatsApp?

How to get notifications on whatsapp:
Lets do a meet on discord, I cant show what I did, and then we can think a better approach to a PR.
This thing would fit on "unsuported".

I guess SMS should be more custom, for example, if it let us choose the url it send Post to, I would never need to change code, only set my post url in there (N8N)

**Comment by bernardolankheet** [comment]
> It would be great if there was the possibility of notifications via Telegram.
Try this: https://github.com/bernardolankheet/trmm-telegram

**Comment by wh1te909** [comment]
closing as webhooks was already released
