### ISSUE TITLE
Feature req: Remote banner

### ISSUE THREAD

**Issue by fryj24** [amidaware/tacticalrmm#1547]
**Is your feature request related to a problem? Please describe.**
No this is not related to a problem jut a suggestion we hope to see soon.

**Describe the solution you'd like**
We have Tactical RMM and a supplemental solution ScreenConnect or (ConnectWise Control). We want to do away with ConnectWise control (Cost and we dont like connectwise) We use it now because it has a "Remote Banner" that shows at the top the name of the technician that has a active remote session on the PC or Mac. For some of our customers in their contract they requested knowing when someone is connected. Can this be added to a future update to let users know when a remote session "Take Control" is in  session?

**Describe alternatives you've considered**
No alternatives I want to completely stick with Tactical RMM and ditch ScreenConnect / ConnectWise Control and remove it off my customer's machines as soon as I see its 100% viable. Tested other remote actions in Tactical and they completely meet all our other needs :)

**Additional context**
Example screenshot attached of what ScreenConnect looks like (And the bar has a little arrow for a menu to "hide" it if needed) during the session.
![feature example screenshot](https://github.com/amidaware/tacticalrmm/assets/124483869/6d8918da-155c-4e24-81ed-ebe74e62dc32)

**Comment by dinger1986** [comment]
https://docs.tacticalrmm.com/tipsntricks/#meshcentral

**Comment by fryj24** [comment]
> https://docs.tacticalrmm.com/tipsntricks/#meshcentral

@dinger1986 Thank you so much! Actually this is what I was looking for.
