### ISSUE TITLE
Alerts are not filtered by account

### ISSUE THREAD

**Issue by Yamacore** [amidaware/tacticalrmm#1572]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox/Edge
 - RMM Version (as shown in top left of web UI): 0.16.0

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.4.9 
- Agent OS: Windows 10

**Describe the bug**
When we create a new user in trmm and limit it to one client the alerts of the bell (top right corner) are not filtered, all alerts are shown. When you try to seach alerts you can just search for the allowed client alerts.

**To Reproduce**
1. Go to alert bell top right corner
2. Click on bell
3. See all alerts for all clients not just the selected ones

**Expected behavior**
Just alerts of the allowed clients should show up just like in the search

**Comment by wh1te909** [comment]
thanks, fix will be in next release
