### ISSUE TITLE
Notifications sending for agents after maintenance mode is switched off

### ISSUE THREAD

**Issue by davew909** [amidaware/tacticalrmm#1576]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser:  chrome
 - RMM Version) :v0.16.0

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.4.9
- Agent OS: Server 2016

**Describe the bug**
When placing a client on maintenance mode that has agents that have email and SMS alerts enabled you receive notifications once maintenance mode is switched off for the outages during the maintenance window.

**To Reproduce**
1. Enable Maintenance Mode for a site/client
2. Turn off an agent that is monitored (SMS/Email)
3. Turn the agent back on after the offline period
4. Disable maintenance mode
5. Receive SMS/Email about agent being off and back on again

**Expected behavior**
1. Enable Maintenance Mode for a site/client
2. Turn off an agent that is monitored (SMS/Email)
3. Turn the agent back on after the offline period
4. Disable maintenance mode
5. Receive no alerts because maintenance mode should have paused the monitoring

**Comment by wh1te909** [comment]
this has been fixed in https://github.com/amidaware/tacticalrmm/commit/e6225ad2419bc93db45e9f50325cd46a3f89b2e3 will be in next release. https://github.com/amidaware/tacticalrmm/issues/1849
