### ISSUE TITLE
Search by Windows Version

### ISSUE THREAD

**Issue by Linux-Alex** [amidaware/tacticalrmm#1577]
Hi,

We would greatly appreciate having an option to search Windows devices by their Windows Version (e.g., _21H2_, _22H2_, etc.). This feature would help us quickly verify whether updates were successfully installed on the devices.

Thank you for considering our request.

Best regards, Alex

**Comment by silversword411** [comment]
You'll be able to access this information once reporting comes out

**Comment by dinger1986** [comment]
so now? Guess could do a report that covers this and close this off

**Comment by wh1te909** [comment]
yes reporting covers this

**Comment by silversword411** [comment]
Searching by 21h1 in the search box works fine as well
