### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by feliperocp** [amidaware/tacticalrmm#1587]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
I would like a feature that allow to get the number of the Windows reliability , that can say a lot about the windows health, this will be very helpfull if can show this information on the main dashboard.
**Describe alternatives you've considered**

**Additional context**

**Comment by dinger1986** [comment]
Can you please explain this in more detail?

Thanks

**Comment by feliperocp** [comment]
For sure, There is a "magic" number in Windows, the Historic Reliability Index, it ranges from 1 to 10, this number allows a technician to quickly assess the overall health of Windows.In my company, for example, the support staff uses this number to decide whether or not a computer should be formatted, after receiving a call from someone reporting slowness, they evaluate, if the reliability history index is greater than 8, they they just check for errors, etc. If it's below 8, it's worth formatting the PC. It would be very useful if TRMM brought this information on the Dashboard, or at least had a script that allowed to get this number on the PCs.
thanks for your attention.



    Em segunda-feira, 7 de agosto de 2023 às 16:59:15 BRT, dinger1986 ***@***.***> escreveu:  
 
 


Can you please explain this in more detail?

Thanks

**Comment by dinger1986** [comment]
Sounds like a script check could cover this nicely and could be proactive and action rebuilds on unreliable machines prior to the customer even phoning in?

**Comment by dinger1986** [comment]
Like this
```
<#
      .SYNOPSIS
      This will gather the average Windows Reliabilty Score
      .DESCRIPTION
      Gather and then check average Windows Reliabilty Score
      .PARAMETER Unreliable
      .EXAMPLE
      -Unreliable 5
  #>

param (
    [string] $Unreliable = "8"
)


$wrs = (Get-Ciminstance Win32_ReliabilityStabilityMetrics | Measure-Object -Average -Maximum  -Minimum -Property systemStabilityIndex).Average
$compname = $env:computername


if ($wrs -lt $Unreliable) {
    write-output "$compname is unreliable and at $wrs below $Unreliable."
    Exit 1
}
else {
    write-output "Windows Reliability is fine $wrs."
    Exit 0
}
```

**Comment by feliperocp** [comment]
Thanks a lot, works perfect for us.
Is there any repository of scripts like this available? in addition to those already available within the tool..

    Em segunda-feira, 7 de agosto de 2023 às 18:53:17 BRT, dinger1986 ***@***.***> escreveu:  
 
 


Like this
<#
      .SYNOPSIS
      This will gather the average Windows Reliabilty Score
      .DESCRIPTION
      Gather and then check average Windows Reliabilty Score
      .PARAMETER Unreliable
      .EXAMPLE
      -Unreliable 5
  #>

param (
    [string] $Unreliable = "8"
)


$wrs = (Get-Ciminstance Win32_ReliabilityStabilityMetrics | Measure-Object -Average -Maximum  -Minimum -Property systemStabilityIndex).Average
$compname = $env:computername


if ($wrs -lt $Unreliable) {
    write-output "$compname is unreliable and at $wrs below $Unreliable."
    Exit 1
}
else {
    write-output "Windows Reliability is fine $wrs."
    Exit 0
}

**Comment by dinger1986** [comment]
loads available in https://github.com/amidaware/community-scripts wip and staging still need work done to them but fine to copy and paste to use yourself, also if you can add any please do!

**Comment by jacksonsystems** [comment]
I wonder if this could be expanded on and anything with a X gets marked as a check or a custom field?

**Comment by silversword411** [comment]
> if this could be expanded on

What does that mean?

**Comment by jacksonsystems** [comment]
> > if this could be expanded on
> 
> What does that mean?

The tool that gives you the score will show a Red X of things that are causing an issue, might be worth seeing if we can report that part of it as well via A Check.

**Comment by jacksonsystems** [comment]
> 

Very true that, would get quite cumbersome! 

For now I am just having the Score go to a custom field.

**Comment by dinger1986** [comment]
why not just an alert come up if its below a threshold?

Could change it to a collector task by doing:
```
<#
      .SYNOPSIS
      This will gather the average Windows Reliabilty Score
      .DESCRIPTION
      Gather and then check average Windows Reliabilty Score
      .PARAMETER Unreliable
      .EXAMPLE
      -Unreliable 5
  #>

param (
    [string] $Unreliable = "8"
)


$wrs = (Get-Ciminstance Win32_ReliabilityStabilityMetrics | Measure-Object -Average -Maximum  -Minimum -Property systemStabilityIndex).Average

Write-Output "$wrs"
```

Then create a custom field and collector task running the above script.

**Comment by NiceGuyIT** [comment]
Can someone please change the title to something a little more descriptive than "feature request"?

**Comment by dinger1986** [comment]
should we just close this?

**Comment by bbrendon** [comment]
Yes, this could be a script.
