### ISSUE TITLE
All of sudden , someother client came to our rmm console. this is a bug,

### ISSUE THREAD

**Issue by Ranjannow** [amidaware/tacticalrmm#1590]
<img width="1037" alt="image" src="https://github.com/amidaware/tacticalrmm/assets/141788840/c8048d4c-f9bc-4d3d-919a-9eb8972efa89">
we use Tactical RMMv0.16.0 , on debain OS,
it was working all fine, once we upgrade to new version from 15, this started happening, some other pc gets automatically added to our client site

**Comment by wh1te909** [comment]
no, https://docs.tacticalrmm.com/faq/#help-ive-been-hacked-and-there-are-weird-agents-appearing-in-my-tactical-rmm

**Comment by Ranjannow** [comment]
Do you mean someone hacked the system?

**Comment by wh1te909** [comment]
Bruh

**Comment by Ranjannow** [comment]
Can you please explain What is the issue? Sorry to bother!

**Comment by wh1te909** [comment]
Dude read the link that I posted

**Comment by Ranjannow** [comment]
Got It, thanks for your help.

thanks
