### ISSUE TITLE
Feature Request - Ability to run tasks on first audit

### ISSUE THREAD

**Issue by mearkats** [amidaware/tacticalrmm#1592]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to setup onboarding tasks for clients which have multiple client specific software install scripts within it. 

**Describe the solution you'd like**
The ability to assign tasks at client level and also be able to assign global tasks and client level tasks with a "Run on first audit" schedule. (When the agent first checks into the dashboard)

**Comment by silversword411** [comment]
You can.

Set task as run once in the past. On task creation on agent it gets set to 5mins in the future and runs
