### ISSUE TITLE
Agent overdue ignored from new agents while defined in policy

### ISSUE THREAD

**Issue by Yamacore** [amidaware/tacticalrmm#1600]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox/Edge
 - RMM Version (as shown in top left of web UI): 0.16.2

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.4.9
- Agent OS: Windows 10/ Windows 11

**Describe the bug**
Policy gets pulled but does not affect overdue checkboxes where it should

**To Reproduce**
1. Go to Automation Manager
2. Create an Policy
3. Apply Policy to Client/Site
4. Add new Agent
5. New Agent pulls checks n tasks but never gets the "dashboard/mail/sms alert when agent is overdue" checkbox in the overview
6. Disable Policy
7. Enable Policy 
8. Agent now pulls checkboxes

**Expected behavior**
Policy gets applied and pulls alerts based on that.

**Screenshots**
![ZTIyS7C](https://github.com/amidaware/tacticalrmm/assets/20658441/344f8d04-e6e7-4c11-b4b3-cc43614d1e02)

**Additional context**
The Agent shows that the Policy is applied correctly it seems this just happens for overdue alerts, at least thats the only part we have tested.

**Comment by wh1te909** [comment]
fixed in https://github.com/amidaware/tacticalrmm/commit/0235dadbf732ae4c469ce1e02c96b701ef635cda will be in next release
