### ISSUE TITLE
Agent install fails on macOS 12.6

### ISSUE THREAD

**Issue by RichardBurt65** [amidaware/tacticalrmm#1605]
Trying to install agent 2.4.11 on macOS 12.6 via terminal. 

Error message after starting agent install:

```
dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /usr/local/bin/./rmmagent
  Expected in: flat namespace

Abort trap: 6
```

Any suggestions?

**Comment by wh1te909** [comment]
what's the output of calling the binary with the `-version` flag
