### ISSUE TITLE
Script Manager: Run As User flag is ignored when using environmental variables

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1614]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa)
 - Browser: Firefox 116.0.2 (64-bit)
 - RMM Version (as shown in top left of web UI): v0.16.3

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.4.11 
- Agent OS: Opensuse-Leap 15.4

**Describe the bug**
The scripting system ignores the Run As User flag when using environmental variables. Running `Get-ChildItem ENV:` produces identical output regardless if the Run As User is checked **IF** there are environmental variables.

**To Reproduce**
1. Create a PowerShell script to dump all the environmental variables: `Get-ChildItem ENV:`
2. Do not check Run As User.
3. Add an environmental variable.
4. Run the script and save the output. Pay attention to the `USERNAME`, `USERPROFILE`, and other user specific variables.
5. Check Run As User.
6. Run the script and save the output. Pay attention to the `USERNAME`, `USERPROFILE`, and other user specific variables.
7. Notice the user specific variables did not change.
8. Leave Run As User checked and remove the environmental variable.
9. Run the script and save the output. Pay attention to the `USERNAME`, `USERPROFILE`, and other user specific variables.
10. Notice the user specific variables now reflect the logged in user.

**Expected behavior**
I expected the environmental variables to reflect the logged in user when Run As User is checked.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by wh1te909** [comment]
fix will be in agent 2.4.12 in next release

**Comment by wh1te909** [comment]
released in 0.16.4
