### ISSUE TITLE
Feature Request: Reset all Checks Button

### ISSUE THREAD

**Issue by meuchels** [amidaware/tacticalrmm#1615]
**Is your feature request related to a problem? Please describe.**
a machine goes offline in the middle of checks or goes to sleep it sends flags all checks as timeout

**Describe the solution you'd like**
I would like a button on the checks page to reset all checks (maybe with permissions attached or a are you sure prompt)

**Describe alternatives you've considered**
I don't have any that I can think of.

**Additional context**
none at this time

**Comment by silversword411** [comment]
Why do you need to reset button? 

Just run the checks again and it will update all the statuses

**Comment by meuchels** [comment]
if the machine times out while running checks it leave all the checks red until it comes back on and runs checks again.
if you train yourself to look at red checks as being okay, that is not good.
I want to be able to clear them if the machine is offline and let it recheck when it comes back.

**Comment by MadGodNerevar** [comment]
![image](https://github.com/amidaware/tacticalrmm/assets/34100671/2635da63-b5dc-4389-8ffd-3159e772e7aa)

There is this reset option?

**Comment by meuchels** [comment]
> ![image](https://user-images.githubusercontent.com/34100671/263071066-2635da63-b5dc-4389-8ffd-3159e772e7aa.jpeg)
> 
> There is this reset option?

you have to do them one at a time

**Comment by MadGodNerevar** [comment]
I guess as another option, a select all box with individual select boxes could be another way to do it, that way you only select the checks you want or all of them. Then change that right-click option to only take note of the one it's on like it does currently or the select boxes? 🤷‍♂️

**Comment by wh1te909** [comment]
Will this work?

![chrome_nq8jySXOGJ](https://github.com/amidaware/tacticalrmm/assets/7434746/c4bfde4d-1d75-4ab3-84f3-70324fa78cbb)

**Comment by meuchels** [comment]
> Will this work?
> 
> ![chrome_nq8jySXOGJ](https://user-images.githubusercontent.com/7434746/263115106-c4bfde4d-1d75-4ab3-84f3-70324fa78cbb.png)

Absolutely

**Comment by wh1te909** [comment]
done, will be in next release

**Comment by wh1te909** [comment]
released in 0.16.4
