### ISSUE TITLE
Editing a script in Script Manager is slow on Chrome based browsers

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#1624]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa)
 - Browser: Google Chrome Version 116.0.5845.96 (Official Build) (64-bit) (running in openSUSE Linux)
 - RMM Version (as shown in top left of web UI): v0.16.4

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): N/A
- Agent OS: N/A

**Describe the bug**
Viewing a script in Script Manager takes several seconds, consumes 100% CPU and the memory footprint balloons vary large.

**To Reproduce**
1. Open Google Chrome and perhaps other Chrome based browsers
2. Open Chrome's Task Manager
3. Go to Script Manager
4. Edit or view a script
5. Observe the Memory Footprint and CPU.
6. Observe how long it takes to view script.

**Expected behavior**
The script should appear immediately. Perform the same tasks in Firefox and it works.

**Screenshots**
Guest profile with no plugins viewing a simple script.
![image](https://github.com/amidaware/tacticalrmm/assets/7763429/6ed62ea4-3118-47f3-ac3c-0858f86fff87)

**Additional context**
Others have reported the [same issue in Discord](https://discord.com/channels/736478043522072608/815123191458299934/1148270305396146268).

## Observations

By "creating" I mean create the script, save it and then edit the script again to experience the hang or slowness.

1. The size of the script does not seem to matter.
2. Creating a new script does not have the problem.
3. Creating an empty script does not have the problem.
4. Creating a PowerShell script with `Get-Item "C:\"` causes the slowness.
5. Creating a Batch script with `dir` causes the slowness.
6. Creating a Python script with `#!/usr/bin/env python3` causes the slowness.
7. Creating a shell script with `#!/usr/bin/env bash` causes the slowness.

**Comment by silversword411** [comment]
Linux...the red-headed stepchild without enough QA testing :(

**Comment by NiceGuyIT** [comment]
This is related to hardware acceleration as it pertains to the GPU. Check `chrome://gpu/` or `edge://gpu/` to see if hardware acceleration is enabled.

**Comment by BMTTeam** [comment]
Ubuntu LTS 20.04 here.  Chrome Version 116.0.5845.179 (Official Build) (64-bit).
After jumping to TRMM v0.16.4, there is no more delay (didn't tweak the GPU or hardware acceleration).

**Comment by dinger1986** [comment]
has this been fixed?

**Comment by NiceGuyIT** [comment]
This is no longer happening.
