### ISSUE TITLE
Integrated Ticket System

### ISSUE THREAD

**Issue by 3eeKeeper** [amidaware/tacticalrmm#1630]
First I would like to start with thank you for the wonderful product! In the future it would be nice to see a ticket system integrated into the dashboard.

Having the agent provide a tray icon in the taskbar that offers users the option to file a ticket when they right-click or double-click.

**Comment by silversword411** [comment]
Systray is already a feature request. Please search before posting to issues.

Adding an entire ticketing system is out of scope for TRMM.

We're working on an Extension system, that will then allow others to build official connections between other systems and TRMM. 

Closing this one
