### ISSUE TITLE
Agents has no pending restart but RMM shows different

### ISSUE THREAD

**Issue by wangshiok** [amidaware/tacticalrmm#1632]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: chrome
 - RMM Version 0.16.3

**Installation Method:**
  - [ ] Standard

**Agent Info (please complete the following information):**
- Agent version - 2.4.11
- Agent OS: SERVER 2019 Standard

**Describe the bug**
According to RMM, the agent - server 2019 has a pending restart, which is fault info.

**To Reproduce**
can not be reproduced

**Expected behavior**
should show the true status of agents

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/113150961/2dd15680-b883-4c6e-b3cc-2265bbee367d)

![image](https://github.com/amidaware/tacticalrmm/assets/113150961/9d116f9f-465f-4753-97e0-dcd6ba943c41)

**Additional context**

**Comment by silversword411** [comment]
Are you looking at the agent list?

Did you update it first?

https://docs.tacticalrmm.com/tipsntricks/#understanding-refreshing-trmm-data

**Comment by wangshiok** [comment]
> Are you looking at the agent list? - YES
> 
> Did you update it first?
> 
> https://docs.tacticalrmm.com/tipsntricks/#understanding-refreshing-trmm-data
tried refresh globally and just that agent, no difference

**Comment by wh1te909** [comment]
does this reg key exist https://github.com/amidaware/rmmagent/blob/753242a9493dcba22f90ad08597bd94aaffbbfd5/agent/agent_windows.go#L586

**Comment by wangshiok** [comment]
> does this reg key exist https://github.com/amidaware/rmmagent/blob/753242a9493dcba22f90ad08597bd94aaffbbfd5/agent/agent_windows.go#L586

thanks will give it a try, it is happening occationally to very small number of agents, and seems only on server 2019, and if I reboot the agent anyway, the pending reboot icon on RMM eventually goes away, it is not a big deal after all, I am closing this bug report
