### ISSUE TITLE
Working with computer groups instantly

### ISSUE THREAD

**Issue by MarcoZaino** [amidaware/tacticalrmm#1634]
It would be useful to be able to work with groups to execute commands instantly.
For example:
- do a WOL (Wake On Lan) to a group of PCs to turn on an entire laboratory with a single iteration;
- run a script or execute a command on the group so that it is executed on all PCs in the lab.

Thanks

**Comment by wh1te909** [comment]
Hi this is what clients/sites are for and you can already do this (Tools > Bulk). for WOL there is already a feature request to do a bulk one
