### ISSUE TITLE
502 Gateway error when using Take Control

### ISSUE THREAD

**Issue by cvanbrummelen** [amidaware/tacticalrmm#1649]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser:Chrome
 - RMM Version (as shown in top left of web UI): 0.16.5

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.5.0
- Agent OS: Windows Server 2016 Standard (But it happens on all servers)

**Describe the bug**
When using the take control option we got a 502 gateway error from NGINX. This happens on all our servers, no exceptions.

**To Reproduce**
1. Go to the server
2. Right click on the server
3. Click on Take Control

**Expected behavior**
Getting control of the server

**Screenshots**
https://snipboard.io/hsBiyz.jpg

**Comment by dinger1986** [comment]
please see here https://github.com/amidaware/tacticalrmm/discussions/1648#discussioncomment-7260527 and continue there
