### ISSUE TITLE
Install Error making API not working

### ISSUE THREAD

**Issue by SBunder** [amidaware/tacticalrmm#1659]
Server Info:
 - Ubuntu 20.04
 - Browser: Chrome

**Installation Method:**
  - Standard

 Issue:
Having an issue with the backend of the server. Went to re install however every time I try to install I get this error:

django.db.utils.ProgrammingError: permission denied for table scripts_script

Note: This was a re install not a clean install, if there are any guides on how to completely remove trmm from the server please let me know

**Comment by wh1te909** [comment]
Hi reinstall won't work and is not supported. You must wipe the vm and start over.
