### ISSUE TITLE
Can't set permission for removing agent

### ISSUE THREAD

**Issue by gkokpc** [amidaware/tacticalrmm#1673]
**Server Info (please complete the following information):**
 - OS: Debian
 - RMM Version 0.16.5

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Describe the bug**
We created some custom permissions, but can't set a permission to remove an agent.

**To Reproduce**
1. Create an new rol
2. No permission can be set, for removing an agent. Only superusers are able to remove an agent.

**Expected behavior**
Have an checkbox to grant permission for removing an agent.

**Screenshots**
![TRMM foutmelding](https://github.com/amidaware/tacticalrmm/assets/150350836/fcd0563c-bf09-4675-9f17-d7bbc3482010)
![2023-11-09 13_37_39-Tactical RMM – Mozilla Firefox](https://github.com/amidaware/tacticalrmm/assets/150350836/5b89274d-e786-418c-acbf-3f21ed503328)

**Comment by wh1te909** [comment]
Thanks, there is actually a permission called "Uninstall Agents" which you have already checked, but this has a dependency on the "Ping Agents" permission which you don't have checked, I'll fix this in next release but in the meantime just add the "Ping Agents" permission (it's only used to check if an agent is online before removing it) and it should work.
