### ISSUE TITLE
Reporting Folders for Organization 

### ISSUE THREAD

**Issue by oiooioio-github** [amidaware/tacticalrmm#1674]
**Describe the solution you'd like**
Ability to create folders within the Reports Manager. I would like to store all the Templates in their own folder and clone out from there for further organization. 

**Describe alternatives you've considered**
Locking templates and forcing users to clone for a new report.

**Comment by wh1te909** [comment]
This was planned, just didn't make it in time for release but will be added.

**Comment by silversword411** [comment]
Dupe: https://github.com/amidaware/tacticalrmm/issues/1665
