### ISSUE TITLE
Change Serial Number Length (more than 50chars)

### ISSUE THREAD

**Issue by Sedlise** [amidaware/tacticalrmm#1678]
I've a probleme with serial number in tactical rmm.
I have some esx virtual machine and the serial of this machine have a length of 54 chars.

But tactical have only 50 chars.

Is it possible to change this?

Thanks.

**Comment by silversword411** [comment]
Where are you talking about?

**Comment by wh1te909** [comment]
yes please add a screenshot of where you are seeing this behavior

**Comment by dinger1986** [comment]
should we close this if its not being updated?

**Comment by bbrendon** [comment]
Maybe it was fixed? This is an ESX SN and its 54 chars
VMware-42 1d 8d 9a db 9d ab 0c-50 b3 5b 27 85 a5 fe b0

**Comment by dinger1986** [comment]
Did you get that from tactical?

**Comment by dinger1986** [comment]
![image](https://github.com/amidaware/tacticalrmm/assets/7244447/51c1e10b-6a2b-48ca-8fa9-d7ff5509896d)

Working fine, thats 54 charachers
