### ISSUE TITLE
Include Serial Number on MacOS (like Windows does)

### ISSUE THREAD

**Issue by jptechnical** [amidaware/tacticalrmm#1683]
**Is your feature request related to a problem? Please describe.**
Currently you can't search for serial number on MacOS, only Windows. You also can't view/retrieve the serial number from the summary tab of the agent.

**Describe the solution you'd like**
The agent queries the serialnumber from the mac host and populates the serial field in the summary view, consistent with how it is displayed on Windows hosts. The serial number is then searchable, also consistent with Windows hosts.

**Describe alternatives you've considered**
Manually add the serial# to the Description field of the agent.
Add the serial as a custom field and populate with a collector script (but it won't be searchable or easily viewed)
```bash
$ ioreg -l | grep IOPlatformSerialNumber | grep -o '"IOPlatformSerialNumber" = "[^"]*"' | awk -F'"' '{print $4}'
M6CXC70G21
```

**Additional context**
This would be desirable on Linux hosts.

**Comment by jptechnical** [comment]
Another alternative would be to allow populating the Description field via collector script, OR make the custom fields searchable. I don't really like either idea though.

**Comment by wh1te909** [comment]
Done, will be in next release
