### ISSUE TITLE
Script Editor - "TEST AND SAVE" button

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#1685]
**Is your feature request related to a problem? Please describe.**
I've lost work a few times using script editor when I accidentally press esc because I'm running around between so many windows. Previously I've avoided using the script editor because I don't want to screw myself but alas I broke the rule today and lost about an hour of script editing work.

**Describe the solution you'd like**
add a "TEST AND SAVE" button

**Describe alternatives you've considered**
Don't use the script editor

**Additional context**
No. I'm frustrated right now. Don't talk to me.

**Comment by silversword411** [comment]
How about we just ask you if you reelyreely want to close the script editor if there's unsaved changes?
https://github.com/amidaware/tacticalrmm-web/commit/d0e49d27fd17b1ad679b1416468d082a69d4b007

**Comment by bbrendon** [comment]
sweeeeeeeeeeeeet. Should be fine... but ask me again in a few months. :D
