### ISSUE TITLE
Per-Server Code Signing

### ISSUE THREAD

**Issue by AddoSolutions** [amidaware/tacticalrmm#1686]
**Is your feature request related to a problem? Please describe.**
I would like to have the server sign my agent files per server, like MeshCentral does

**Describe the solution you'd like**
https://www.youtube.com/watch?v=qMAestNgCwc

**Additional context**
This is the one thing holding me back from using this tool.  I am not looking to avoid the sponsorship, but rather interested in the security implications of whitelisting an entire genre of software, some of whom are threat actors.  By having each server sign their own agents with a cert only that server has, it allows me to just whitelist that one certificate knowing I am the only one with it.

**Comment by silversword411** [comment]
That is a paid service we can offer, please open a ticket for pricing information.

Https://support.amidaware.com

**Comment by AddoSolutions** [comment]
You are saying I can have the code signed by MY cert automatically, locally as is?

**Comment by silversword411** [comment]
You can use your own code signing cert, yes

**Comment by JonaseQ** [comment]
Hello, - this means that after buying sponsorship I will be able to use my own EV Code Signing certificate? Which Tier should I choose?

**Comment by dinger1986** [comment]
once you buy sponsorship you would use Amidawares code signing certificate open a ticket if you would like to use your own https://docs.tacticalrmm.com/support/
