### ISSUE TITLE
Timeout alerts after x tries

### ISSUE THREAD

**Issue by nomadusje** [amidaware/tacticalrmm#1697]
Currently a alert script timeout creates a alert and skips the "Number of consecutive failures before alert".

Script timeouts should only show alerts after the same tries that is configured in the "Number of consecutive failures before alert".

Currently this causes alot of false positives in the mail and dashboard.

**Comment by silversword411** [comment]
Are you sure a timeout is ignoring the number of consecutive failures?

I specifically adjusted that to minimize the number of false alerts and pretty sure it worked

**Comment by nomadusje** [comment]
It seems to fail with Return Code: 98 and gives a alert after just 1 failure when this return code is used.

The script shows the output just before the exit (echo "everything is OK") and then the script seems to keep running, never returning the normal exit code.

Run Time: 390.2651 seconds
Return Code: 98
Script timed out after 90 seconds

I will try to change the scripts to use exit 0 (instead of just exit). Maybe this helps a bit.

**Comment by silversword411** [comment]
Set exit code 98 to be an informational exit so it doesn't create any return for those timeouts

**Comment by nomadusje** [comment]
It works, I've seen much less errors. Now the icon sometimes becomes blue because of the information exit code, but it doesn't produce real alerts anymore.
