### ISSUE TITLE
Add script run time and exit code to Script Editor's script tester

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1713]
Add these to script editor header

![2023-12-22_062756 - trmm script results](https://github.com/amidaware/tacticalrmm/assets/13395348/01346a46-6416-42dd-9f50-06383ba4abef)

**Comment by wh1te909** [comment]
done, will be in next release:


https://github.com/amidaware/tacticalrmm/assets/7434746/75eefaab-b3f8-4f05-96ac-6e857209ed7f
