### ISSUE TITLE
Windows Defender False positive

### ISSUE THREAD

**Issue by noalphakamp** [amidaware/tacticalrmm#1723]
Windows defender suddenly calling code signed tactical installs as Trojan:Win32/Wacatac.H!ml  Defender deletes install files.

**Comment by dinger1986** [comment]
Yep... https://docs.tacticalrmm.com/av/#antivirus

**Comment by noalphakamp** [comment]
Bummer, I will PS from here on out.  This can be closed.

**Comment by Anaphylaxis** [comment]
Hasn't happened to me for ages but 2.10.0 update triggered it.

**Comment by Anaphylaxis** [comment]
It also states that it's detected monitored keystrokes via WH_KEYBOARD_LL...
"MeshAgent.exe set a hook of type WH_KEYBOARD_LL to monitor user keystrokes"
?

**Comment by silversword411** [comment]
Looks like you already investigated why and why that happens
https://github.com/amidaware/tacticalrmm/issues/2406
