### ISSUE TITLE
Add from name email

### ISSUE THREAD

**Issue by MatijaTerzic** [amidaware/tacticalrmm#1726]
**Is your feature request related to a problem? Please describe.**
When you setup e-mail you can only set a from e-mail address, it would be nice to also set the "name from" e.g. RMM <rmm@domain.com>" 

**Describe the solution you'd like**
Also able to define "from name".

**Describe alternatives you've considered**

**Additional context**

**Comment by dinger1986** [comment]
so something like this?

![image](https://github.com/amidaware/tacticalrmm/assets/7244447/c1f02094-f1f5-41b2-837b-cbfb39413e4d)

**Comment by dinger1986** [comment]
some something like this? just mocked up atm:

![image](https://github.com/amidaware/tacticalrmm/assets/7244447/412f0d5d-a047-43a1-aa9b-84bfc6e98e20)

**Comment by MatijaTerzic** [comment]
Yes indeed, now when TRMM sends a mail you just see the email address in the from. It would be nice to have a "From name" also ;)

**Comment by wh1te909** [comment]
done, will be in next release:

![chrome_nR8HxUdNXM](https://github.com/amidaware/tacticalrmm/assets/7434746/93f9a9ed-2a03-4307-8aad-ddd23d63f305)
![chrome_WXSvXRHAlP](https://github.com/amidaware/tacticalrmm/assets/7434746/72f3e492-ec0f-408a-8cbf-68979b5214ca)
