### ISSUE TITLE
Alert Template Not Updating with Automation Policy Change in Tactical RMM

### ISSUE THREAD

**Issue by dinger1986** [amidaware/tacticalrmm#1733]
Description:
In Tactical RMM, changing the automation policy for an agent does not update the associated alert template as expected. This issue was discovered while troubleshooting delayed SMS alerts for offline servers. Despite changing an agent's type to 'server' and applying the 'server default' automation policy directly to the agent/PC, the alert template remains unchanged. This behavior persists even after performing a bulk update to the offline overdue time setting.

Steps to Reproduce:
Assign the 'server default' automation policy directly to an agent/PC.
Change the agent's type from 'workstation' to 'server'.
Observe that the alert template does not update in accordance with the automation policy change.

Expected Behavior:
Assigning a new automation policy or changing an agent's type should update the alert template to reflect the settings defined in the automation policy.

Actual Behavior:
The alert template remains unchanged despite changing the automation policy and agent type, leading to inconsistencies in alert management.

Additional Information:
The issue was initially identified during a power outage when servers went offline, but SMS alerts for data being overdue were not received as expected.
The default setting for data overdue was discovered to be set to half an hour, which was adjusted to 4 minutes for testing.
The primary issue regarding delayed SMS alerts was resolved; however, the problem with alert templates not updating persisted.
[Reported on discord](https://discord.com/channels/736478043522072608/1194322433251999794). 

Environment:
Tactical RMM Version: 17.2
Operating System: Debian 11

**Comment by tkintenn** [comment]
I have this problem as well. 17.3, debian 11.

**Comment by P6g9YHK6** [comment]
same here debian 12 / 17.3

this is quite a big deal of inconsistent behavior
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/cd848bab-0a6c-4aec-b559-6b99e1d0731a)
screenshot of 2 devices moved from an OU without AT to an OU with AT
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/76b0478e-208c-4a00-a49e-e45ac342e6f1)
screenshot of the same ou after removing the Automation policy and re-adding it.

**Comment by wh1te909** [comment]
fixed, will be in next release
