### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by justfor-it** [amidaware/tacticalrmm#1734]
**Is your feature request related to a problem? Please describe.**
Is there an option for the feature to create reports? So when you schedule a job it have always an output of a script. Can that be set in an report every month?

**Describe the solution you'd like**
Is there an option for the feature to create reports? So when you schedule a job it have always an output of a script. Can that be set in an report every month?

**Comment by wh1te909** [comment]
yes we do have a [Reporting](https://docs.tacticalrmm.com/ee/reporting/reporting_overview/) feature. They cannot be scheduled yet but that feature is planned: https://github.com/amidaware/tacticalrmm/issues/1665
