### ISSUE TITLE
Reporting issue with Q-INPUT

### ISSUE THREAD

**Issue by subzdev** [amidaware/tacticalrmm#1737]
**Server Info (please complete the following information):**
 - OS: Debian
 - Browser: Any browser
 - RMM Version (as shown in top left of web UI): 0.17.3

**Installation Method:**
  - [x ] Standard
  
**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.6.1
- Agent OS: Any OS

**Describe the bug**
When the `<q-input />` component is present the entire browser will freeze. This was working until January 13th.

**To Reproduce**
Start with quasar/vuejs template and make sure the component `<q-input />` is present.

**Expected behavior**
Browser should not freeze, the `<q-input />` component should be able to be used without issue.

**Screenshots**
None.

**Additional context**
None.

**Comment by silversword411** [comment]
I wonder what changed...but as I understand it isn't that a shorthand version of the tag?

Try
`<q-input></q-input>`
as a workaround

**Comment by subzdev** [comment]
> I wonder what changed...but as I understand it isn't that a shorthand version of the tag?
> 
> Try `<q-input></q-input>` as a workaround

Same thing unfortunately.

**Comment by subzdev** [comment]
This can be closed. Apparently something in my Internet history did not like the q-input component. Cleared out all history since beginning of time and it is working as expected now.
