### ISSUE TITLE
I think I just found a weird bug when logging in to RMM

### ISSUE THREAD

**Issue by BubbaGTX** [amidaware/tacticalrmm#1738]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox, Edge
 - RMM Version (as shown in top left of web UI): v0.17.3

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): not using any agents yet
- Agent OS: not using any agents yet

**Describe the bug**
So today I decided to install Tactical RMM. After 1 hour of installing Debian 12, setting it up and installing Tactical RMM I went to log in at rmm.mydomain.local and every time I would try to log in I would get this error:

![error](https://github.com/amidaware/tacticalrmm/assets/45404197/e0975a97-37e8-42b3-9051-0e22ecc33e5a)

After troubleshooting and updating Tactical RMM (troubleshooter showed all in green) I got an idea to try an open api.mydomain.local in my browser and I got this error:

![image](https://github.com/amidaware/tacticalrmm/assets/45404197/92a521c2-bf42-4583-b89e-5338783c450c)

After that I decided to try logging in one last time and for some reason there was no error this time: 

![image](https://github.com/amidaware/tacticalrmm/assets/45404197/94d60417-6229-4d89-bd1c-44b3862ebf39)

Logging in was successful but every time I want to log in to rmm.mydomain.local I first need to open api.mydomain.local and then I can log in to rmm.mydomain.local.

Is there a way to fix this problem?

**Comment by wh1te909** [comment]
this is normal when using self-signed certs because you need to accept the security warning in browser before you can login (the docs mention this). If you don't want this problem, use real certs.
