### ISSUE TITLE
Automation Manager - Policy - if you enable it after disable it first, the policy does not kick in, have to apply the policy on agents again

### ISSUE THREAD

**Issue by wangshiok** [amidaware/tacticalrmm#1742]
**Server Info (please complete the following information):**
 - OS: [ Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version (as shown in top left of web UI): 17.3

**Installation Method:**
  - [ ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):2.6.1
- Agent OS: [Server 2012r2/2016/2019]

**Describe the bug**
got a Automation Manager - Policy to restart server every Monday, and applied the policy to a group of agents. During Christmas/New year, I decided to suspend the policy, so instead of removing the policy from agent, I just disabled the policy from Automation Manager, after  the new year break, I enabled the policy in Automation manager, and the policy is not working, you have to remove the policy and apply the policy again on agents.

**To Reproduce**
as ABOVE in **Describe the bug**

**Expected behavior**
as ABOVE in **Describe the bug**

**Screenshots**

**Additional context**

**Comment by wh1te909** [comment]
I am not able to reproduce, seems to be working for me. I've recorded a video, please let me know if you are doing something different and provide exact steps to reproduce or a record a video if you can, thanks.


https://github.com/amidaware/tacticalrmm/assets/7434746/57fe54c1-fc25-4829-8ab0-321e29b0cad8

**Comment by wangshiok** [comment]
thanks, see below screenshots, the task is there but not executing after I
re-enabled the policy after the Christmas/New year break, you can see the
task last run time was 18 -Dec-2023 before Christmas.

[image: image.png]


[image: image.png]

**Comment by wangshiok** [comment]
happy to close

**Comment by wangshiok** [comment]
a quick work-around is to make a small change on the policy in automation manager, then you will notice on the related agents > "Will sync on next agent checkin", then it is all good.
