### ISSUE TITLE
Hide Custom Fields from Agent Summary but not Edit

### ISSUE THREAD

**Issue by dinger1986** [amidaware/tacticalrmm#1745]
**Is your feature request related to a problem? Please describe.**
Due to some custom fields containing alot data or something irrelevant data for the Summary it would be good to hide it from summary and still show it if you Edit the Agent.

**Describe the solution you'd like**
The Hide in Dashboard option should either only hide on agent summary or a new option should be added to hide in summary.

**Describe alternatives you've considered**
For some, reports would be able to show the contents of custom fields, checking the output of the collector task or adding a new tab in agent summary for custom fields,
**Additional context**

**Comment by wh1te909** [comment]
Will be in next release:

![KQ0yrAisna](https://github.com/amidaware/tacticalrmm/assets/7434746/d7602234-505b-486a-aca3-3567e8869856)
