### ISSUE TITLE
2FA delay while logging in after update

### ISSUE THREAD

**Issue by otuva** [amidaware/tacticalrmm#1758]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: all of them
 - RMM Version (as shown in top left of web UI): v0.17.5

**Installation Method:**
  - [x] Standard
  - [ ] Docker

**Describe the bug**
While logging in, entering the 2fa password won't work until it expires or very close to expiring 

**To Reproduce**
1. Go to login page
2. Try to login 
3. 2fa won't work. wait until it expires
4. after expiring it will work

**Expected behavior**
It should just log in

**Additional context**
Tried resetting 2fa, tried rebooting, tried updating

**Comment by silversword411** [comment]
2FA is TOTP. Time Based Onetime Password.
Your clock is probably off by 45 seconds

**Comment by otuva** [comment]
@silversword411 
Yeah that was the problem, installed `ntp`.
