### ISSUE TITLE
Tag Manager

### ISSUE THREAD

**Issue by paulmataruso** [amidaware/tacticalrmm#1759]
I would really love to see a tag manager for TRMM. I understand that there are sites and groups. For example, today's workflow was to go and remote into every single Veeam Backup Server for each client. While it is not insanely difficult to find the servers, I would absolutely love the ability to be able to just add a tag to each endpoint (Servers, Veeam Servers, Backup Servers, Domain Controllers etc). So, I can just sort by Tag and all the endpoints tagged with "Veeam" would show up in my list and everything else would not show up.

Side note I really love this project and am using it to support a small MSP(~40 Clients) it has been absolutely invaluable.

**Comment by silversword411** [comment]
Please search before posting.
Duplicate https://github.com/amidaware/tacticalrmm/issues/653
