### ISSUE TITLE
Linux agent not connecting after Certificate change

### ISSUE THREAD

**Issue by albindy** [amidaware/tacticalrmm#1786]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): v0.17.5

**Installation Method:**
  - [ X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):Agent v2.6.2
- Agent OS: Debian 12

**Describe the bug**
When changing the Certificate in nginx Linux Agents no longer connect.
No error in /opt/tacticalmesh/meshagent.log or /var/log/tacticalagent.log
Switching back to old Cert brings back the Agents online. Or reinstallation.
Result: Certificate Change is impossible for me. But I have to.
How can the change be done without reinstalling all Linux Agents.
**To Reproduce**
1. Go to '/etc/nginx/site-available/*.conf'
2. Change from Lets encrypt Zertificate to bought Cert
3. Restart Nginx
4. Linux Agents no longer connecting

**Expected behavior**
Agents should accept other active and valid certificates without reinstallation.

**Screenshots**

**Additional context**

**Comment by albindy** [comment]
Problems are meshcentral.conf  and rmm.conf
When changing the Certificate there the Agents are no longer working.
Yes we use code signing.
"Code signing all agents"

**Comment by wh1te909** [comment]
so windows agents connect fine with new cert?

can you run the linux agent in debug mode and see if any errors related to certs? don't paste the full output here because it contains sensitive info:

```
# stop service
sudo systemctl stop tacticalagent

# run in debug
tacticalagent -m rpc -log debug -logto stdout

# after done debugging, don't forget to start service back up
sudo systemctl start tacticalagent
```

**Comment by albindy** [comment]
SyncMesh: Post "https://api.*********/api/v3/syncmesh/": tls: failed to verify certificate: x509: certificate signed by unknown authority
But the cert is valid and an official wildcard working on several other systems.
Additional info, it is a wildcard Cert.
 (CN)	Sectigo RSA Domain Validation Secure Server CA
 (O)	Sectigo Limited

Yes Windows connects fine.

**Comment by dinger1986** [comment]
Did you follow this and update all files?

You don't need to do the nats regen.

You need to use the fullchain which you haven't.

**Comment by albindy** [comment]
Yes, followed the guide. Did the nats regen and worked like a charme.
But! Good hint, I'm trying fullchain actual using cert.

**Comment by dinger1986** [comment]
So it worked after a nats regen?

**Comment by albindy** [comment]
Nats worked before. 
Just to complete the picture. Problem was using cert instead of fullchain.
But Nats works with cert only and frontend too.
For rmm and meshcentral fullchain is mandatory to work.

Maybe a hint in the docu would help. But, yes I know it is unsupported.
Thanks for clearing things up and helping lightning fast!
Thanks for the great support!
All up and running now!

**Comment by dinger1986** [comment]
Did you not see this?
![image](https://github.com/amidaware/tacticalrmm/assets/7244447/74b419fa-bc09-4058-9875-87b4537b47cf)

Nats doesnt actually need a cert anymore, glad its working now

**Comment by albindy** [comment]
OMG Sorry! Totally overlooked this note.
Thanks again!
Closing.

**Comment by dinger1986** [comment]
lol no worries!
