### ISSUE TITLE
The CTRL+ALT+CANC sequence is not sent to the Hyper-V 2019 server

### ISSUE THREAD

**Issue by Monostatos61** [amidaware/tacticalrmm#1788]
**Server Info (please complete the following information):**
 - OS:  Ubuntu 20.04 LTS
 - Browser: Firefox and Edge
 - RMM Version (as shown in top left of web UI): 0.17.5

**Installation Method:**
  - [ X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.6.2
- Agent OS: Microsoft Hyper-V Server 2019

**Describe the bug**
Taking control of the remote machine through the agent, the unlocking sequence of the remote server (CTRL+ALT+CANC) is not sent. So it is not possible to access the session

**To Reproduce**
1. Go to 'Take Control'
2. Click on "Connect"
3. Scroll down to 'CTRL+ALT+CANC'
4. Press Send
5. Nothing happens

**Comment by wh1te909** [comment]
Hi, this is handled by another software. Please search for this issue there and if there is no open issue, open a new one: https://github.com/Ylianst/MeshCentral

**Comment by Monostatos61** [comment]
Ok.
  
Thanks!
  

  Alberto Grasso
