### ISSUE TITLE
When deleting agent from TRMM - delete all check and task historical data

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1789]
When agent is deleted from TRMM need to cleanup leftover data from check history and task history so it doesn't show up in automation manager.

<img width="830" alt="2024-03-08_091945 - delete check and task history when deleting agents" src="https://github.com/amidaware/tacticalrmm/assets/13395348/7035ed8c-b8be-4452-bb42-6e18e1130ea1">

**Comment by P6g9YHK6** [comment]
This also appears when the agents are not deleted and simply moved out of a policy.
A dedicated function to purge Individual agent history should made available for manual use trough the ui too not only back-end when deleted.
