### ISSUE TITLE
Feature Request: Central Patch View

### ISSUE THREAD

**Issue by Epod** [amidaware/tacticalrmm#179]
Greetings,

At the moment, the process to manually approve a patch involves clicking on every single agent across the entire RMM, and approving a patch. 

A improved method would instead be a central patch view, allowing a review of all patches for a the entire install/site/location and approving a specific patch once.

**Comment by subzdev** [comment]
I would also like to suggest some type of chart/graph breakdown of healthy, vulnerable and/or highly vulnerable systems, so that it is easy to pinpoint those that require immediate patching due to how vulnerable they are.

**Comment by Nyphew** [comment]
Hi,

I've been using tactical rmm for a month now and that would be nice to :
- have a filter to hide patches based on "severity".
- be able to resize the "name" column.
- to replace the whole list of windows defender updates KBs with only the last one.
![image](https://user-images.githubusercontent.com/83342905/116385675-4e863880-a819-11eb-8568-28d7e4accffb.png)

Thanks for your great work.

**Comment by davidrudduck** [comment]
Perhaps a way to create a "Patch Policy" and apply that policy to a site (or automation policy?) and then be able to "View Patches" in that Patch Policy, filter by severity, etc and mass approve.

**Comment by silversword411** [comment]
Ticket Consolidation: Combining into https://github.com/amidaware/tacticalrmm/issues/1188
