### ISSUE TITLE
add the possibility of re-ordering URL actions.

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1795]
**Is your feature request related to a problem? Please describe.**
curently the order of URL actions seems based on the last edited date of each url. this cannot be a behavoir that was made on purpose.

**Describe the solution you'd like**
Either make it alphabetical or
Allow reordering from the url action Global Settings page by drag and drop or
add an additional numerical field to each url action and then order it from smallest to biggest.

**Describe alternatives you've considered**
i have all my url neatly organised by editing them manually one by one to have them in the order i wanted.
it is painfull.

**Comment by wh1te909** [comment]
the url actions is getting a rework (as part of the webhooks feature) so we'll make it sort alphabetical once that is released

**Comment by P6g9YHK6** [comment]
![image](https://github.com/user-attachments/assets/9507dd14-b08e-41ae-882f-14d48460dc79)
did not work
