### ISSUE TITLE
Filter with expired older than 30 Days doesnt work

### ISSUE THREAD

**Issue by Manolosun** [amidaware/tacticalrmm#1803]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Debian 10] ubuntu 22.04
 - Browser: [e.g. chrome, safari] Edge
 - RMM Version (as shown in top left of web UI): 0.17.5

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.6.2
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] all

**Describe the bug**
If i use the filter function on the first site after login in mixed mode
i use the older than 30 days filter
then i become all machine for vision there are no filter function right now.

**To Reproduce**
1. Go to 'Startpage after Login'
2. Click on 'All Clients (left top) 
3. then on Filter (right top) 
4. then on 'Show Offline for over 30 days''
5. See that there is no filter active all devices will be shown up

**Expected behavior**
should show nothing or a handfull of devices that will be expired

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/87390875/2d8d3d53-15b0-4260-8dda-bdc77fafa3d4)

**Additional context**

**Comment by wh1te909** [comment]
thanks, just fixed. will be in next release

**Comment by jvandenbroek** [comment]
Not sure if I misunderstand this feature, but it seems to filter out agents on boot time > 30 days instead of last report date > 30 days.

**Comment by wh1te909** [comment]
@jvandenbroek thanks, not sure what I was thinking when I "fixed" this I must have been really tired, I used the boot_time instead of last_seen field lol. Just pushed a fix again for this, will be in next release.

**Comment by wh1te909** [comment]
Released in 0.18.2
