### ISSUE TITLE
Sync Mesh Perms with TRMM doesn't work

### ISSUE THREAD

**Issue by pcxeon2** [amidaware/tacticalrmm#1816]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): 0.18.0

**Installation Method:**
  -Standard

**Describe the bug**
The new feature "Sync Mesh Perms with TRMM" doesn't work.
Users created in TacticalRMM are not created in Meshcentral.

**Comment by dinger1986** [comment]
tracking on #1814 please check there and report if you are still having issues
