### ISSUE TITLE
Add Support for all Linux agents in MeshCentral - Mainly "Take Control"

### ISSUE THREAD

**Issue by LPJon** [amidaware/tacticalrmm#1821]
**Is your feature request related to a problem? Please describe.**
I can't install the Linux TacticalRMM agent for freebsd based distros

**Describe the solution you'd like**
I would like to be able to use "Take Control" to access the "Files" and "Terminal" options for freebsd based distros from within the UI. Currently I have to use a completely separate instance of MeshCentral to do this. Support for checks and tasks could be added later.

**Describe alternatives you've considered**
Using a completely different instance of MeshCentral

**Additional context**
Freebsd requires you to expose the "proc" partition in order to install meshagent. We manage "OPNsense" and "PfSense" firewalls and it would be much easier if we could do this from within TacticalRMM.

**Comment by dinger1986** [comment]
FreeBSD tracked in #1525 and take control being changed to command and file manager tracked in another issue. Please search before opening new issues
