### ISSUE TITLE
Groups lost in mesh central after updating to 18.1

### ISSUE THREAD

**Issue by rubybrars** [amidaware/tacticalrmm#1825]
**Server Info (please complete the following information):**
 - OS: Debian GNU/Linux 11
--

 - Browser:  chrome
 - RMM Version v0.17.5 updated to 0.18.1

**Installation Method:**
 Standard

**Describe the bug**
I updated 17.5 to 18.1 version today and after that, i lost custom device groups, and there was no option to move the devices into new groups that i created thinking we can add groups and devices again.
I reverted back to the old version from the snapshot and the options came back again.
We need those groups to enable user consent on connection to prompt for computers and bypass prompt on servers

Some icons are missing as well as you can see in the screenshots i have added, tags and move to device group options are gone in new mesh.

**Screenshots**
New version shot
![image](https://github.com/amidaware/tacticalrmm/assets/140012835/7a1207ce-d2be-43bb-9114-bf2a8f03b74b)
Move to device group and edit tags option missing
![image](https://github.com/amidaware/tacticalrmm/assets/140012835/8b7b6ce6-9143-4799-af3d-a8ee3e110d1a)

Old version shot
![image](https://github.com/amidaware/tacticalrmm/assets/140012835/2f3b2296-f64c-4a83-917c-36b109b01553)

**Comment by dinger1986** [comment]
Use the following command https://docs.tacticalrmm.com/mesh_integration/#get-a-url-to-login-to-mesh-as-the-mesh-superuser

And then assign the newly created users to the groups.

You can also disable the new feature to sync users in global settings

**Comment by wh1te909** [comment]
the new sync feature no longer auto logs you into mesh as the mesh super user. you can now the instructions here to get a url to login as the mesh superuser just how it used to be before 0.18.0: https://docs.tacticalrmm.com/mesh_integration/#get-a-url-to-login-to-mesh-as-the-mesh-superuser, or as @dinger1986 you can simply disable the new sync feature to revert back to the previous behavior
