### ISSUE TITLE
Export Assets summary

### ISSUE THREAD

**Issue by TechSOSnet** [amidaware/tacticalrmm#1827]
I would like an option to export a simplified version of the assets section of a client.
Maybe as a CSV or XML or even a simple txt file. Anything I can easily share with a 3rd party.
It wouldn't need to include all the verbose details in the asset section. But something just a little more detailed than the summary tab.
One thing it should definitely include is the type of RAM and number of slots used/available on the board.
Similar to an export you might get from programs like Belarc Advisor or Speccy
Thank you.

**Comment by dinger1986** [comment]
This is available with our reporting feature
