### ISSUE TITLE
Getting email alerts on informational/warning check results.

### ISSUE THREAD

**Issue by technoicon** [amidaware/tacticalrmm#1834]
Server Info (please complete the following information):
OS: Ubuntu 18.04.05
Browser: chrome
RMM Version (as shown in top left of web UI): 0.17.5

Installation Method:
Docker

Agent Info (please complete the following information):
Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.6.2
Agent OS: Windows Server 2019 Standard, 64 bit v1809 (build 17763.4010)

Describe the bug
Getting email alerts on informational/warning check results.

**To Reproduce**
1. Setup an automation policy with email alerts.
2. have a script check log as informational or Warning.
3. This will produce an email alert.

**Expected behavior**
It would be good to have a global alert on "failure" "warning" "informational" check boxes in global settings to configure what will alert on.

**Comment by silversword411** [comment]
This issue should fix: don't sms/email on informational returns

**Comment by wh1te909** [comment]
added a global setting to configure this, will be in the upcoming release next week

**Comment by wh1te909** [comment]
Released in 0.19.0
