### ISSUE TITLE
Add the option to save output of a bulk script run

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1845]
**Is your feature request related to a problem? Please describe.**
not allowed to save output of a script when run trough bulk and it does remove a bit of flexibility to the tool

**Describe the solution you'd like**
the same 3 save option than when a script is run individualy to be set under the the bulk script tool

**Describe alternatives you've considered**
creating a task for updating custom field. no alternative available for any other output.

**Additional context**
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/d5c84275-6aee-4415-937f-26a70851d1bd)
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/07dd8429-a23d-47af-b685-67881bddf8fb)

**Comment by lqdmist** [comment]
This feature would've saved our day today

**Comment by wh1te909** [comment]
@lqdmist fyi the output of bulk actions is already saved in the history tab of each agent

**Comment by wh1te909** [comment]
done, will be in next release
