### ISSUE TITLE
Feature Request: Search bar for sites

### ISSUE THREAD

**Issue by ekunzag** [amidaware/tacticalrmm#1860]
Hello there :)

I would like to ask for an feature request. We got many sites on Tactical RMM. It would be nice, if there was a search bar to search sites.
I think this place would be a good option:
![image](https://github.com/amidaware/tacticalrmm/assets/131602288/a0dce06f-67e5-40ee-bc61-4bc2f38fab37)

**Comment by P6g9YHK6** [comment]
personally i janked this one out:
i made a recurring collect tasks that include client name and site name. 
slapped the whole bunch of data into a hidden custom field.
now if i want to be able to search the devices by site name of client name i can as the main search do parse custom fields.

**Comment by dinger1986** [comment]
this functionality is already there, if you click all clients and then use search it shows all the machines in a site/client, or am I missing something?

![search](https://github.com/amidaware/tacticalrmm/assets/7244447/a70640e7-d3da-4233-a726-c9773310782a)

**Comment by silversword411** [comment]
Agreed, already searches everywhere natively
