### ISSUE TITLE
Tray Icon for TRMM

### ISSUE THREAD

**Issue by screwlooseit** [amidaware/tacticalrmm#1861]
I'd love a feature like a trmm tray icon to be implemented into Tactical where a user can right-click on the tray Icon and be met with the following options

Identify My PC - This gives them an output of their hostname
Submit a support request - This gives them a text box where they can type in an issue they are experiencing and it then either sends an email to the helpdesk or generates an alert in the dashboard.
Show Support contact - This is a field that can be edited showcasing an email and phone number or whatever is deemed necessary
Go to the Support website - a button that opens a web browser to a user-defined website

I know there is an alternative below. But it would be really nice if this was built into the agent or a feature you could enable for agents. 
https://github.com/conlan0/Trayicon

**Comment by dinger1986** [comment]
Please add comments to #253 

Closing as duplicate
