### ISSUE TITLE
SNMP Relay / probing from a device/agent on another network

### ISSUE THREAD

**Issue by W1BTR** [amidaware/tacticalrmm#1872]
[**Is your feature request related to a problem? Please describe.**

Somewhat similar to #112 - which mentions SNMP scanning of printers.

**Describe the solution you'd like**
Allow a device to be used to check the status of other devices on its network using SNMP (or even better, receive SNMP traps). This snmp device could then show up as an additional device on the overal list, or simply as a status on the "probe" device's details.

The configuration options needed would be:
SNMP OID: (the oid to check for)
SNMP Community: (SNMP Community, which acts as an encrpytion key)
SNMP Value type: (string, displaystring, integer)
SNMP Version: (v1, v2, v3)

and then some manipulation to work with the results such as expected numbers or values, ranges inside and outside of numbers, etc.

**Describe alternatives you've considered**
Currently we use Davicom Cortex Units at each site. These units are expensive at about $2,000-$10,000 each depending on the configuration. SNMP is implemented, but it's a bit buggy and hard to set up.

We're also looking into Zabbix, but it's SNMP implementation is weak at best, and the configuration is a nightmare. Plus, this is another paid solution

**Additional context**
SNMP is used in far more than printers. For us, we use SNMP to monitor police and fire radio repeaters, UPS units, DC Power Distribution Panels, GPS Time Clocks, Network Switches, and much more. Almost everything we work with supports SNMP to get status indicators like alarms, GPS Lock Status, and more!
](https://github.com/amidaware/tacticalrmm/issues/112)

**Comment by eduardomozart** [comment]
You may also consider using a SNMP Proxy. I wrote about it here (Google Translate): https://translate.google.com/translate?sl=pt&tl=en&hl=pt-BR&u=https://eduardomozartdeoliveira.wordpress.com/2024/05/09/howto-grafico-de-varios-dispositivos-usando-um-snmp-proxy-net-snmp/&client=webapp
You can find the original post which this article is based on EN at the Cacti Forums: https://forums.cacti.net/viewtopic.php?t=28175
But in fact it seems you need a third party solution as TacticalRMM doesn't seem to be intended to do this. Here you can find a NMS comparision table: https://eduardomozartdeoliveira-wordpress-com.translate.goog/2024/05/10/tabela-comparativa-de-nmses-opensource/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp
Zabbix is free, and if you have a complex infrastructure to monitor, it seems you also should have resources to pay for a commercial solution. The free ones you also pay, the time you waste searching documentation and troubleshoot issues.

**Comment by wh1te909** [comment]
Added in release 0.19.0: https://docs.tacticalrmm.com/functions/snmp_checks/
