### ISSUE TITLE
Sharing connect

### ISSUE THREAD

**Issue by gasergroup** [amidaware/tacticalrmm#1878]
**Server Info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - RMM Version 0.18.2

**Installation Method:**
  - [ X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.7.0
- Agent OS: Windows 10

**Describe the bug**
today not working sharing connect
If i click "take control" of a client, i can click "connect" for me but i can't share this connection: bottom right of screen is not available icon of sharing.
Is it possible recover this function?

**To Reproduce**
1. Go to 'Client'
2. Click on 'one client'
3. Click on 'take control'
4. In window not appeare sharing button

**Comment by wh1te909** [comment]
follow the instructions in the 0.18.2 release notes to re-sync the perms and guest sharing will be added back: https://github.com/amidaware/tacticalrmm/releases/tag/v0.18.2
