### ISSUE TITLE
AD problems

### ISSUE THREAD

**Issue by hakerakn** [amidaware/tacticalrmm#1881]
**Server Info (please complete the following information):**
 - OS: Ubuntu 
 - RMM Version v0.18.2

**Installation Method:**
  - [ ] Standard
 

**Agent Info (please complete the following information):**
- Agent version v2.7.0
- Agent OS: Win 10

**Describe the bug**

**To Reproduce**
 
I have Active Directory and all client computers are connected to it.
I have 10 accounts without admin rights and 2 accounts with admin rights.
1. I enter the GUI of the RMM server and select the client machine
2. I press the Take Control button and enter the machine.

After I log into the client machine which is with Win 10 with one of the accounts without admin rights and I had to change the account, my session freezes.

**Expected behavior**

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/5690740/36ab392a-b06e-4cd3-912b-ca04fed166eb)

**Comment by dinger1986** [comment]
does it not just log out and then you reconnect? are the users logged in with rdp? 

This is an issue with https://github.com/Ylianst/MeshCentral most likely, not something I have replicated other than if its linked with the 2 questions above

**Comment by BMTTeam** [comment]
Indeed. That's on Mesh and has nothing to do with TRMM.
Well it's obvious what workaround is - just click disconnect and connect again.

Cheers,
-Tiho
