### ISSUE TITLE
Add tooltip on tasks with task guid name for troubleshooting

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#1886]
When troubleshooting task creation etc need a way to tell what task is what item

<img width="276" alt="2024-06-12_130809 - brave_Tactical_RMM_-_Brave" src="https://github.com/amidaware/tacticalrmm/assets/13395348/c928b6dd-c575-475e-a6fa-cbe5bfca0e52">

**Comment by wh1te909** [comment]
Done: 
![chrome_Oaq7Y1LRlU](https://github.com/user-attachments/assets/0925f4eb-e075-4365-a560-d46f786238e8)
