### ISSUE TITLE
New agents not assigned alert template

### ISSUE THREAD

**Issue by alvanson** [amidaware/tacticalrmm#1896]
**Server Info:**
 - OS: Debian 12
 - Browser: (all)
 - RMM Version: 0.18.2

**Installation Method:**
  - [x] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Agent Info:**
- Agent version: (all)
- Agent OS: (all)

**Describe the bug**
New agents are not assigned the automation policy's alert template when added. The correct automation template is shown in the agent edit window, but alert template shows None. This can be corrected by going to Tools > Global Settings and making a change to the default alert template and hitting Save. Sometimes you have to cycle between populating an alert template and clearing the alert template to get the correct alert templates to populate.

**To Reproduce**
(see above description)

**Expected behavior**
New agents should be assigned their automation policy's alert template when added.

**Screenshots**
(none)

**Additional context**
We have multiple automation policies set with different alert templates.

**Comment by wh1te909** [comment]
thanks just pushed a fix for this, will be in the next release.
