### ISSUE TITLE
[BUG] sends resolved notification when no alert has been sent in the first place.

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1909]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: N/A
 - RMM Version (as shown in top left of web UI): v0.18.2

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):Agent v2.7.0
- Agent OS: N/A

**Describe the bug**
When an alert with a level that does not have an email or sms is resolved it still send for exemple "info" will still send in this case:
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/4d2d7ff8-85cc-4a9a-9456-cad2233d2bc4)

**To Reproduce**
see screenshot

**Expected behavior**
no resolved if no alert has been sent

**Comment by wh1te909** [comment]
fixed in https://github.com/amidaware/tacticalrmm/commit/beb121532964da2c7c9a3c3602500f18fd35b7ba

**Comment by wh1te909** [comment]
actually fixed in 0.19.1 xD
