### ISSUE TITLE
tactical meshagent memory leak

### ISSUE THREAD

**Issue by slapplebags** [amidaware/tacticalrmm#1913]
**Server Info (please complete the following information):**
 - OS: Ubuntu 22.04.4
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): v0.18.2

**Installation Method:**
  - [ x ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.7.0
- Agent OS: Ubuntu 22.04.4

**Describe the bug**
tactical meshagent service has a memory leak and slowly grows to 10s of gigabytes of memory usage until it is restarted. 

**To Reproduce**
1. install tactical agent on ubuntu 22.04.4

**Expected behavior**
agent uses a reasonable amount of ram and doesnt need to be restarted to reduce memory usage

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/8379092/1cabea83-88d8-46b0-b416-0c7fc3a1b080)

**Comment by wh1te909** [comment]
I have dozens of agents on various ubuntu 22.04 systems and never have had a memory leak. You'll need to provide more logs and info about your setup. Also please open the issue in the meshcentral or meshagent github repo, there are already several reports about agent memory leaks there.
