### ISSUE TITLE
Display bitlocker key in summary tab

### ISSUE THREAD

**Issue by root-it74** [amidaware/tacticalrmm#1919]
Hello,

Is it possible in the future to have the bitlocker key sent directly to the rmm?

The only solution I have is to use a script or to look for it in my DC.

I think we can save time by having it directly available in the summary tab. 

Thank you

**Comment by dinger1986** [comment]
theres a script already and you can save to custom fields, then set the custom fields to show in the summary tab or not.

**Comment by root-it74** [comment]
> theres a script already and you can save to custom fields, then set the custom fields to show in the summary tab or not.

Ok thanks, I'll try that
