### ISSUE TITLE
[BUG] {{agent.used_ram}} {{agent.plat_release}} {{agent.time_zone}} broken

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1932]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 19.2

**Installation Method:**
  - [ ] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v2.7.0
- Agent OS: window server 2019/2022

**Describe the bug**

{{agent.used_ram}} output the hostname
{{agent.plat_release}} output the hostname
{{agent.time_zone}} output null

**To Reproduce**
Use the variables

**Expected behavior**
fields should be giving an expected output

**Additional context**
https://discord.com/channels/736478043522072608/744281869499105290/1265683298735099964

**Comment by wh1te909** [comment]
used_ram and plat_release no longer exist, just updated the docs to remove those. time_zone is an optional field, if it's not set the agent will fall back to the default global timezone so you probably want to use `{{agent.timezone}}` (no underscore).
