### ISSUE TITLE
Feature Request - Store Hostname As Caps or Lower Case Option

### ISSUE THREAD

**Issue by davesmith87** [amidaware/tacticalrmm#1939]
**Is your feature request related to a problem? Please describe.**
When sorting reports using the "order by" for hostname, case sensitivity seem to mater.  For example, Apple, Bat, Cat would be in order but another value with apple, but be under Cat.

**Describe the solution you'd like**
A Global Option, for the Item Hostname Value to store as All Caps, or All Lowercase.

**Describe alternatives you've considered**
Create a custom field.  Running a powershell script to get the Hostname then convert it to all caps.  Then reference the custom field hostname instead of the item.hostname.

**Comment by wh1te909** [comment]
check discord, I replied with an example template of how to first convert all to lower and then do the sorting.
