### ISSUE TITLE
Users need permission "Core > Edit Custom Fields" to see custom fields values of agents

### ISSUE THREAD

**Issue by janstalhut** [amidaware/tacticalrmm#1941]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): 0.19.2

**Installation Method:**
  - [x] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Describe the bug**
If I understand correctly, the permission "Core > Edit Custom Fields" means that the user can adjust custom fields in the global settings. Regardless of this, the values ​​of the custom fields should be visible and, if necessary, changeable in the edit dialogs of individual clients, sites and agents.

Currently, without this authorization, I can see and change the values ​​of custom fields for individual clients and sites, but when I call up the edit dialog for an agent, I only get the following message:
`No agent custom fields found. Go to **Settings > Global Settings > Custom Settings**`

**Comment by dinger1986** [comment]
So it should have read only view for everyone but some custom fields maybe shouldn't be seen by everyone so would need extra permissions for that also

**Comment by janstalhut** [comment]
Without wanting to offend the developers, who really do a great job, but why should the described error be a feature request? I think the current behavior is clearly a bug. I can change the values ​​of the custom fields of clients and sites in their dialogs. But in the dialog for editing agents, the wrong permission is apparently checked.

**Comment by wh1te909** [comment]
this is a bug, im not sure why it was tagged as enhancement. i've updated it.

**Comment by wh1te909** [comment]
just pushed a fix for this, will be in next release
