### ISSUE TITLE
Feature: Method to get script ID in the GUI

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#1943]
Mousing over the company/site gets the ID. Would be nice if there was a way to get the script ID in the GUI as well.

**Comment by silversword411** [comment]
Tooltip everything everywhere. 

Sounds like a great plan to me.

**Comment by P6g9YHK6** [comment]
> Done: ![chrome_PlvXlkgyVE](https://private-user-images.githubusercontent.com/7434746/352911604-91ed1383-b058-4e1d-be09-ef58281c92fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTMzODksIm5iZiI6MTcyMjI1MzA4OSwicGF0aCI6Ii83NDM0NzQ2LzM1MjkxMTYwNC05MWVkMTM4My1iMDU4LTRlMWQtYmUwOS1lZjU4MjgxYzkyZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMTEzODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0MTMzNDk4MGM1YjcwYWI1ZGY4YTQ5NDcxMzY2NzVkNDI0ZWQyZjk1NjQzOTNiMTIzMWZjNmU3YmMwY2EyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RKCm2Dc-o7W706xBTyYFB2XeiUXJF3cCoNakh1pSr40)

do the same for custom fields ! :)

**Comment by P6g9YHK6** [comment]
> Done: ![chrome_PlvXlkgyVE](https://private-user-images.githubusercontent.com/7434746/352911604-91ed1383-b058-4e1d-be09-ef58281c92fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTMzODksIm5iZiI6MTcyMjI1MzA4OSwicGF0aCI6Ii83NDM0NzQ2LzM1MjkxMTYwNC05MWVkMTM4My1iMDU4LTRlMWQtYmUwOS1lZjU4MjgxYzkyZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMTEzODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0MTMzNDk4MGM1YjcwYWI1ZGY4YTQ5NDcxMzY2NzVkNDI0ZWQyZjk1NjQzOTNiMTIzMWZjNmU3YmMwY2EyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RKCm2Dc-o7W706xBTyYFB2XeiUXJF3cCoNakh1pSr40)

do the same for custom fields ! :)

**Comment by wh1te909** [comment]
added for custom fields as well
