### ISSUE TITLE
Missing client and site names in email with script result

### ISSUE THREAD

**Issue by janstalhut** [amidaware/tacticalrmm#1945]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): 0.19.2

**Installation Method:**
  - [x] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Describe the bug**
If I run a script on a device and select the option to receive an email with the result, this email only contains the host name and the script name in the subject. (And the same information in the first line of the email.)

**Expected behavior**
The email must contain the site and client name, as is the case with alert emails. Otherwise, this email cannot be clearly assigned, as host names can occur multiple times across customers.

**Additional context**
In our specific case, we have integrated several Proxmox VE systems into Tacticel, these usually have "pve" or "pve1" as host names. I run a script on all of these machines to carry out the latest updates and have the emails sent to me, as the processes usually take a little longer. In these emails, I cannot see which of the systems for which customer is affected if an error has occurred.

**Comment by wh1te909** [comment]
added, will be in next release
