### ISSUE TITLE
Add Syntax Hover Icon from "Run Script" onto "Run Bulk Script"

### ISSUE THREAD

**Issue by ZzBombardierzZ** [amidaware/tacticalrmm#1946]
**Is your feature request related to a problem? Please describe.**
It's frustrating when you go to run a bulk script that has special variable syntax, and you have to open a second window to view the variable syntax for the script you are about to bulk run.

**Describe the solution you'd like**
Add the same info icon with hover for syntax to the bulk script menu that the regular script menu has.

**Describe alternatives you've considered**
No other alternatives that I've considered fixing the issue. My current work-around is having a second window open with the scripts library or the run script menu on it.

**Additional context**

Bulk Script View:
![image](https://github.com/user-attachments/assets/a9b37dbb-bff4-4c1d-b84f-013d9015e932)

Single Script View:
![image](https://github.com/user-attachments/assets/845fc6ae-e128-403c-a60b-aed8549ef158)

**Comment by wh1te909** [comment]
done, will be in next release
