### ISSUE TITLE
[FEATURE REQUEST] Ability to "Disable/Enable" "Checks/Tasks" without deleting them from the UI

### ISSUE THREAD

**Issue by LPJon** [amidaware/tacticalrmm#1959]
**Is your feature request related to a problem? Please describe.**
When there is a problem with a specific PC and the Automation running on it. It is useful to be able to "Disable" the offending task or check until the automation script or PC issue is resolved.

**Describe the solution you'd like**
A "Right Click Context Menu" option to disable/enable any task or check in the respective list

**Describe alternatives you've considered**
Not using TacticalRMM

**Additional context**
I need to be able to stop the automation for a specific PC/Server anywhere in the system with at simple "Disable/Enable" option so that the automation does not persistently fail while troubleshooting is being done. It should always be "Enabled" by default.

**Comment by wh1te909** [comment]
So individual tasks can already be enabled/disabled (the check box with the power icon) but yes we also need to add this for checks. There's already a feature request for that in #1770 so closing this one as duplicate
