### ISSUE TITLE
Restore failed / 500 Internal Server Error after Restore

### ISSUE THREAD

**Issue by aliarsalahn** [amidaware/tacticalrmm#1964]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: edge
 - RMM Version 19.3

**Installation Method:**
  - [ ] Standard
  - [ x] Standard with `--insecure` flag at install
  - [ ] Docker

**Describe the bug**
Hi, I'm new to tactical rmm und generally new to Linux. I'll try to make a concise description of my issue. So first of all, I'm currently evaluating Tactical RMM for my company. One of the most important aspects of the evaluation is how backup and restore is working. Backups are made easy with the provided script which is good, sadly restore doesn't seem to work (or atleast not for the insecure installation). I've tried restore multiple times, but it failed everytime. As you can see in the screenshot I'm not able to access the webinterface after i did a restore. 

I would love to provide for logs if there are any, unfortunately i don't know where to locate them. 

**Expected behavior**
I would assume, that after restore everything is accessible as it was before. If not please let me know which steps are needed to make sure, everything works as previously. 

**Screenshots**
![image](https://github.com/user-attachments/assets/22743113-48e7-46fa-b857-cfbc1ce6a7f0)

**Comment by dinger1986** [comment]
please install using ssl, `--insecure` is not built for production

**Comment by aliarsalahn** [comment]
Hi @dinger1986 , as mentioned in my post i'm only evaluating tactical rmm. It is not in production yet

**Comment by dinger1986** [comment]
understood but backups is a production feature, why would you backup a test environment?

**Comment by wh1te909** [comment]
restore isn't supported on an insecure install anyway...so you won't be able to test restores
