### ISSUE TITLE
Indicator of Agent Type in 'Mixed' View

### ISSUE THREAD

**Issue by adamjrberry** [amidaware/tacticalrmm#1966]
**Is your feature request related to a problem? Please describe.**
When using the 'Mixed' view on the dashboard, there doesn't seem to be any other indicators of what is/isn't a workstation or server 'at a glance'.

**Describe the solution you'd like**
Having an icon next to the OS icon that shows whether a device is a workstation or a server. 
Example:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/67b18f8a-b26c-43ed-b03e-5f6fac322df2">

**Describe alternatives you've considered**
Just using the filtering tabs. Although in Mixed view, it would be nice to have visibility of all devices, but with their respective type.
Alternatively, adding a note to the agent description. 

**Additional context**
I apologise if this has already been raised... I did a search but didn't find anything, but it feels like something that might have been asked before...

**Comment by wh1te909** [comment]
done, here's how it will look in next release:
![chrome_EQvHzF5gaB](https://github.com/user-attachments/assets/2514e04a-9998-430f-8577-c1e512cd46d3)

**Comment by P6g9YHK6** [comment]
I can predict a feature request to customize these icons per agent :D
