### ISSUE TITLE
rmm.mydomain.com opens the NPM Default site page.

### ISSUE THREAD

**Issue by cornerstoneconsulting-pro** [amidaware/tacticalrmm#1968]
Both api and mesh open up to their respective sites, but for some reason rmm will open to the NPM Defaut Site page. And to clarify, this is when I am trying to access the site within my local network. I have gotten it to load when connecting from outside of my network with a Cloudflared tunnel. Is there supposed to be a login for the admin page to get rmm to redirect/load correctly or is this not normal behavior?
<img width="1279" alt="Screenshot 2024-08-08 at 18 51 46" src="https://github.com/user-attachments/assets/270cc663-7e98-476f-b318-b83563c41684">

**Comment by wh1te909** [comment]
NPM or using a another proxy isn't officially supported and not going to work out of the box. you can try looking through the unsupported section on our docs or asking for help in our Discord in the unsupported channel.

**Comment by cornerstoneconsulting-pro** [comment]
> NPM or using a another proxy isn't officially supported and not going to work out of the box. you can try looking through the unsupported section on our docs or asking for help in our Discord in the unsupported channel.

Doesn't it have NPM built in by default to handle the certificates? I should also add that I can go to https://localipaddress and I can get logged in. Only using the domain name I have for it doesn't work.

**Comment by dinger1986** [comment]
Is this a new install?

To be clear Nginx which is used with TRMM is different from NPM so do you have another proxy in the mix?
