### ISSUE TITLE
[BUG] Alert template not applied on move

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1975]
**Server Info (please complete the following information):**
 - OS: [Debian 12
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 19.2

**Installation Method:**
  - [X] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.7.0
- Agent OS: all

**Describe the bug**
Alert template is not applied properly when moved from a site with a default template to one with a "client" level 

**To Reproduce**
1. see screenshots the client is in the group with the alert disabled and was moved from a group with only "default" policy applied

**Expected behavior**
the alert template should be properly updated like the policy.

**Screenshots**
![image](https://github.com/user-attachments/assets/af08fbd1-942d-422c-b92f-1390313aad1a)
![image](https://github.com/user-attachments/assets/e53ab230-c52f-405b-83c4-e652214948a7)
![image](https://github.com/user-attachments/assets/fffd6d36-b48f-42ee-8da0-b9b4c2871b9a)
![image](https://github.com/user-attachments/assets/6d8def5a-a3db-40e2-a011-d85d6d12aa77)

**Additional context**

**Comment by P6g9YHK6** [comment]
i confirm that 24h later the policy is still not applied 
i don't need it for prod so i will leave it in a Schrodinger state but any other device would be problematic to say the least.

**Comment by P6g9YHK6** [comment]
i confirm that 24h later the policy is still not applied 
i don't need it for prod so i will leave it in a shrodinger state but any other device would 

> it appears to be working for me when trying to reproduce, but maybe I'm not doing the same thing you are. Here is a video of what I did that shows it working please let me know if you're doing something different:

yep it is what i did would there be another way of finding out why it is not changing ?

**Comment by P6g9YHK6** [comment]
Oh i just realised !
i moved the whole SITE not the agent!

**Comment by wh1te909** [comment]
thanks just pushed fix
