### ISSUE TITLE
Uninstall Prevention

### ISSUE THREAD

**Issue by zoltan151** [amidaware/tacticalrmm#1976]
Often times, after installing the RMM, either TacticalRMM or Mesh Agent is uninstalled/deleted from the endpoint by an existing antivirus (especially AVG and McAfee), usually after several hours. Most RMM's have uninstall prevention to prevent the files and services from being removed or disabled. Any way we can do that with the Tactical RMM and Mesh agents as well? This would be a huge improvement.

**Comment by dinger1986** [comment]
https://github.com/amidaware/tacticalrmm/discussions/1389
