### ISSUE TITLE
Enhancement request: Force deny installing a patch

### ISSUE THREAD

**Issue by DjMagicFingers** [amidaware/tacticalrmm#198]
The current options allow to approve, ignore or do nothing with patches.
Sometimes there are Windows updates that do not "play" well with the OS and MS takes all the time in the world to release a fix or an updated patch.
In the meanwhile, the malfunctioning update can be triggered by a manual update or by another software.

The suggested enhancement is to provide another option to deny a patch so it can no longer harm the OS.

**Comment by wh1te909** [comment]
once I have rewritten the windows update module in golang this will be the default during install, agent will set the registry keys to disable auto updates so that they are only controlled by the rmm.

**Comment by DjMagicFingers** [comment]
> once I have rewritten the windows update module in golang this will be the default during install, agent will set the registry keys to disable auto updates so that they are only controlled by the rmm.

That is great and really should be the default, but the request is to also be able to define a patch as bad patch so even if i accidently select all patches to be approved, there would be a mechanism that will force me to pay attention to the bad patch and not auto-patch with others.

Another thing to consider I think, would be the ability to overcome default RMM settings with manual updates - can you lock bad patches from manually being updated?

I think forcing me to double check may be tedious but would be much better than having to uninstall a patch that caused problems to the user...

**Comment by silversword411** [comment]
> once I have rewritten the windows update module in golang

Wasn't the rewrite finished back here? https://github.com/wh1te909/tacticalrmm/releases/tag/v0.4.0 

I'm looking for the reg key you're setting.

**Comment by silversword411** [comment]
Ticket Consolidation: Combining into https://github.com/amidaware/tacticalrmm/issues/1188
