### ISSUE TITLE
Multiple script checks based on the same script in an automation policy do not work.

### ISSUE THREAD

**Issue by janstalhut** [amidaware/tacticalrmm#1995]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - RMM Version (as shown in top left of web UI): 0.19.3

**Installation Method:**
  - [X] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 2.8.0
- Agent OS: Linux (Maybe others too, I haven't tried that.)

**Describe the bug**
If I add a script check multiple times with different parameters via an automation policy, then this check only appears once for the agents to which this policy was assigned. Based on the email notifications I receive from this script, it seems to be random which of the script checks is actually executed on the agent.

**To Reproduce**
1. Create an Automation Policy with 2 script checks
2. Use the same script twice with different parameters
3. Asign the Policy
4. Have a look at checks view of the agent.

**Expected behavior**
If I enter multiple script checks via a policy, I expect that they will all be executed on the assigned agents.

**Workaround:**
Distribute the script to the agents only once using the policy and then assign further script checks with the same script individually at agent level. But of course this is very tedious and not really in the spirit of the policies.

**Comment by silversword411** [comment]
Dupe https://github.com/amidaware/tacticalrmm/issues/1462

**Comment by janstalhut** [comment]
I think there is some different between this issue an the #1462:
In #1462 will be multiple checks on the agent level while there are already the same check in a policy.
But I try to create simply multiple checks in one policy. There are no warning or error while do so, it finally doesn't work!
