### ISSUE TITLE
Show more details of the results on the Checks overview.

### ISSUE THREAD

**Issue by janstalhut** [amidaware/tacticalrmm#2014]
**Is your feature request related to a problem? Please describe.**
It is a bit annoying when I always have to click on "Last Output" each time a check fails to find out the background.

**Describe the solution you'd like**
For a few built-in checks, the essential information of the check is displayed directly (e.g. Disk Usage and Service Check). I would like to see output like this for other built-in checks:

- CPU Load Check (Simply print the last percentage)
- Memory Check (Simply print the last percentage)
- Ping Check  (A short version of the ping statistics, like `0% packet loss, avg: 350.733µs`)

It would also be desirable if the result of one's own script could be displayed here. This means, of course, only the first line of the script output and, if necessary, shortened with a "More" link, which then displays the intended output of the script as before.

**Describe alternatives you've considered**
Using your own script, which is stored as a collector task, so that its output can be saved in a custom field and displayed on the summary tab. However, this is quite time-consuming and quickly becomes confusing.

**Additional context**

![Bildschirmfoto vom 2024-09-24 17-50-08](https://github.com/user-attachments/assets/e558f4a9-585d-4381-b5de-a476e62fa42a)

**Comment by wh1te909** [comment]
How does this look?

![chrome_d7iPpJeokf](https://github.com/user-attachments/assets/b7a12e23-011e-4e35-9359-25f0924f3f84)

**Comment by janstalhut** [comment]
That looks fantastic. That's exactly how I imagined it. When will this update be available?

**Comment by wh1te909** [comment]
in the next release, trying to get it out sometime this week
