### ISSUE TITLE
Allow use of context (subdirectory) instead of subdomains

### ISSUE THREAD

**Issue by muzzol** [amidaware/tacticalrmm#2034]
**Is your feature request related to a problem? Please describe.**
Install script only gives you the option to use subdomains:
```
      api.mydomain.com
      mesh.mydomain.com
      rmm.mydomain.com
```

**Describe the solution you'd like**
I would like to use context instead of subdomains:
```
mydomain.com/api
mydomain.com/mesh
mydomain.com/rmm
```

**Additional context**
This configuration allows more options, simplicity and flexibility for certs, proxys and general management.

**Comment by wh1te909** [comment]
this will never be possible without a complete rewrite
