### ISSUE TITLE
[UI Tweeks] Add total cpu/ram to remote background

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#2037]
**Is your feature request related to a problem? Please describe.**
there is no view of totals in the process tab of remote background

**Describe the solution you'd like**
not having to go and check the totals somewhere else
would it be possible to have the view of the totals in the process tab ?
![image](https://github.com/user-attachments/assets/107064db-c969-4c65-ad17-0504fe21e621)

**Describe alternatives you've considered**
just for convinience

**Comment by wh1te909** [comment]
Done: 
![chrome_ra9GYH59WE](https://github.com/user-attachments/assets/83b75193-d38a-4e44-a5a2-646fbebd358a)
