### ISSUE TITLE
[Feature request] Run individual checks

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#2041]
**Is your feature request related to a problem? Please describe.**
currently we can only manually run ALL checks at once and no single checks 

**Describe the solution you'd like**
a button when right clicking a check that allow to run the selected check

**Describe alternatives you've considered**
change the timer to a low interval and set it back to default value when refreshed...

**Additional context**
![image](https://github.com/user-attachments/assets/81056726-cae9-4516-a67e-3f18e5bc5524)

**Comment by silversword411** [comment]
Dupe https://github.com/amidaware/tacticalrmm/issues/1441

Tried working on this with Josh a while ago...it's a non-trivial add because of....complexities
