### ISSUE TITLE
Missing option to group agents across clients.

### ISSUE THREAD

**Issue by janstalhut** [amidaware/tacticalrmm#2056]
**Is your feature request related to a problem? Please describe.**
We have been using TRMM successfully for several months now and it saves us a lot of manual work. However, there is one option that we always miss. If we want to run a script in parallel on various devices that belong to different clients but are of the same type (e.g. all Windows-Domain-Controllers, all Nextcloud-Servers or all RaspberryPi-Devices), we have to search for the corresponding agents individually in the "Run Bulk Script" dialog and can at best search by host name. This is very annoying, especially because it is always the same groups of agents that have to be selected here in order to run certain scripts on them.

**Describe the solution you'd like**
We would like to have the option of assigning agents to freely definable groups across customers. We can also use the term "tag" here. It would be important that an agent can also be assigned to several groups/tags.

On the one hand, these tags could then be used in the search or filter function. But above all, it would then be important that with the Bulk Script function (and of course with the other bulk tools) you can select one of the defined groups/tags as an alternative to the existing target selection options, so that the process is applied to all devices assigned to this group.

**Describe alternatives you've considered**
We already use the description field for each individual agent to enter unique keywords such as "WindowsDC", "NextcloudSrv" or "RaspberryPi". This then makes it possible to find all devices using these "tags" in the global search function. Unfortunately, the search in the "Select Agents" field does not search in the same way as this global search, but only searches the host names.

An alternative (makeshift) solution, if it can be implemented more quickly/easily, could be that the search function when selecting agents in the "Run Bulk Script" dialog has the same functionality as the global search function. Or perhaps not quite as extensive, but at least the client name, site name, host name and description should be searched here to filter the otherwise very long list. This would make the selection much easier.

And finally, as a third variant, I could imagine that the "Run Bulk Script" dialog would have another option under "Choose Target" that would read something like: "all currently listed agents". So that the global search or filter can be used first and its result list can then be used as a target for the bulk execution of a script.

**Comment by P6g9YHK6** [comment]
https://github.com/amidaware/tacticalrmm/issues/653

**Comment by silversword411** [comment]
Yes duplicate. Closing
