### ISSUE TITLE
Feature Request: FIDO2/WebAuth 2fa Login Support (ex Yubikey)

### ISSUE THREAD

**Issue by johnnyq** [amidaware/tacticalrmm#206]
Excellent project and thank you for contributing back to open source. FIDO2/WebAuthn 2FA Support would be awesome. Meshcentral seems to have it already so you may be able to piggy back off of that.

**Comment by wh1te909** [comment]
sounds good, will look into it!

**Comment by johnnyq** [comment]
@wh1te909 Excellent Thank! 2021 the year passwords will be gone

**Comment by KLISCHE-HW** [comment]
+1

**Comment by jlydia** [comment]
+1 

Any updates on this?

**Comment by mxroo** [comment]
+1

**Comment by wh1te909** [comment]
hardware token support is now possible with the release of SSO in v0.20.0: https://docs.tacticalrmm.com/ee/sso/sso/
