### ISSUE TITLE
[Feature Request] Regedit UI in Remote background

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#2064]
**Is your feature request related to a problem? Please describe.**
Currently there is no convenient way of editing and visualizing the registry of a remote device.

**Describe the solution you'd like**
a new tool in remote background to help with registry edit in the UI
the result could be something close to the current file browser

**Describe alternatives you've considered**
Take control / scripts

**Additional context**
![image](https://github.com/user-attachments/assets/3ddd1ec3-a08e-461e-aa46-6319a233c833)

**Comment by wh1te909** [comment]
duplicate https://github.com/amidaware/tacticalrmm/issues/1452

**Comment by P6g9YHK6** [comment]
damn i was sure it was a dupe and looked for it before posting
