### ISSUE TITLE
[Feature request] Tasks History

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#2068]
**Feature Request: Task History Logs**

**Is your feature request related to a problem? Please describe.**

Currently, there is no way to view historical logs for tasks, which makes it difficult to trace past executions, identify recurring issues.

**Describe the solution you'd like**

Implement a history log feature for tasks that records:
- Each execution timestamp
- The task status (e.g., success, failure, timeout)
- runtime
- Terminal output

This would allow to track task to troubleshoot issues 

**Describe alternatives you've considered**

Manually logging task output

**Additional context**
![image](https://github.com/user-attachments/assets/7dfcfc7a-bfbe-4ef7-b589-73b071878326)

**Comment by wh1te909** [comment]
what about the agent history tab? all the info you want is already there for task runs for every run.

**Comment by P6g9YHK6** [comment]
> what about the agent history tab? all the info you want is already there for task runs for every run.

i had a brain fart i didn't think about it 
 it is just very clogged up but yea it would do the job 
 
 i noticed that the export does not have the output 
![image](https://github.com/user-attachments/assets/e13c13a3-40ca-4ab7-a603-2d57a5e7681d)

**Comment by P6g9YHK6** [comment]
will close this one and open an issue for the export missing

**Comment by wh1te909** [comment]
for exporting it's better to just use the reporting feature with the CSV option the one in the tables is limited and won't work for stuff that requires tons of data as its client side only and loading all the data client side will cause browser to freeze/crash
