### ISSUE TITLE
Usage Monitoring Endpoint via Docker / MON_TOKEN via (docker-) environment variable

### ISSUE THREAD

**Issue by tobfel** [amidaware/tacticalrmm#2075]
Hi is it possible to use active the monitor feature like descripted here:

[https://docs.tacticalrmm.com/tipsntricks/#monitor-your-trmm-instance-via-the-built-in-monitoring-endpoint](url)

for the docker stack?
I have tried to set Environment var in docker-compose.yml on some places, but it seems not to be regognized.

Thank you.

**Comment by wh1te909** [comment]
the checks are designed for monitoring services on a standard install only, not docker so they won't work even if you manage to enable it.
