### ISSUE TITLE
SSO Microsoft: Error AADSTS500113: No reply address is registered for the application.

### ISSUE THREAD

**Issue by TeamInfoGit** [amidaware/tacticalrmm#2076]
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: edge, chrome
 - RMM Version (as shown in top left of web UI): v0.20.0

**Installation Method:**
  - [ ] Standard

**Describe the bug**
I followed the example tutorial for Microsoft SSO integration, double or triple checked.. And when i try to login using Microsoft i get that error:

AADSTS500113: No reply address is registered for the application.

I really checked everything, but it seems the callback url does not work when logging in.. 

Things to know:
Every user has MFA configure in Microsoft.
![image](https://github.com/user-attachments/assets/04a04b56-2020-4eaf-afae-51d903324e84)
![image](https://github.com/user-attachments/assets/7956a857-c626-4616-bc80-d397ff46fc70)

**Comment by wh1te909** [comment]
yea that's strange, because you have indeed set the callback url yet MS somehow thinks its missing. Maybe open a support ticket with MS and ask why it's not being saved.

**Comment by dinger1986** [comment]
Can you share a snip of the error and also of your settings in trmm (please hide your tokens

**Comment by TeamInfoGit** [comment]
Now i don't have a proper MS error anymore, but when i registered the app as MS user i had the error:
"Error AADSTS500113: No reply address is registered for the application."

This is what i get now:
![image](https://github.com/user-attachments/assets/f8690ae1-d8ed-4a86-8aed-39b9b0f89ee4)


And this is my configuration in TRMM:
![image](https://github.com/user-attachments/assets/f9ddbf41-9432-462f-802f-9c05d5f73765)

**Comment by silversword411** [comment]
https://docs.tacticalrmm.com/ee/sso/sso/#troubleshooting

**Comment by TeamInfoGit** [comment]
Great !!! I didnt even see this troubleshooting section, my bad.
All fixed thanks

**Comment by wh1te909** [comment]
we just added those docs today which is why you didn't see it earlier :) glad it's working now
