### ISSUE TITLE
[Feature Request] Provide a warning when a file could not be downloaded when it is opened on the remote machine

### ISSUE THREAD

**Issue by lqdmist** [amidaware/tacticalrmm#2083]
**Is your feature request related to a problem? Please describe.**
When one wants to download a file (from a Windows machine) using remote background and the file is opened in notepad for example, we are unable to download it. There is no warning indicating that the file has been opened.

**Describe the solution you'd like**
When trying to download a opened file, provide a warning stating that the file is open and therefor cannot be downloaded.

**Describe alternatives you've considered**
Provide an option to close the file on the remote machine before downloading

**Comment by P6g9YHK6** [comment]
you should open this issue on mesh central rather than trmm as the file browser is developed by them
FYI also:
https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith
https://github.com/microsoft/PowerToys/issues/22315
