### ISSUE TITLE
Export of users and devices

### ISSUE THREAD

**Issue by SamPry** [amidaware/tacticalrmm#2097]
In my opinion, the program would greatly benefit from an export feature that allows users to generate a comprehensive list of all devices and associated users. This functionality would be particularly useful for companies looking to quickly assess their inventory, such as the number of laptops or PCs in use and the individuals assigned to each device. Adding this feature would streamline asset management and enhance the program's value for organizations.

**Comment by P6g9YHK6** [comment]
it's already possible with reporting/api/customfields or any combinaison of the previous three

**Comment by wh1te909** [comment]
https://docs.tacticalrmm.com/ee/reporting/reporting_overview/
