### ISSUE TITLE
unable to take remote session

### ISSUE THREAD

**Issue by Ronysiby** [amidaware/tacticalrmm#2099]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ronysiby** [comment]
unable to take remote session in tactical rmm

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

To address the feature request, we'll add the ability to select different OpenAI models in the core settings. This will allow users to choose between various models like GPT-3.5-turbo and GPT-4, providing more flexibility in AI-powered features.

Changes:
1. Add a new field to the CoreSettings model for OpenAI model selection.
2. Update the CoreSettingsSerializer to include the new field.
3. Modify the OpenAICodeCompletion view to use the selected model.
4. Update the dashboard_info view to include the available OpenAI models.

You can review changes in this commit: https://github.com/zxsa89675/amidaware-tacticalrmm-2099/commit/cde9ccad6998650429881f0008de55cc0ad4a3f8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Ronysiby** [comment]
Could someone please explain why this neds to be done when an agent already installed with all the features.

thanks.


***@***.***

rony​​​​ siby

cloud support

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Femtech-computers-llc-dubai&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=0AfiEv5SIAmjm3EgXlbN_OyboFwKG6rH2xAhV0CMevI&excomponenttype=Image&signature=hMD9la7sxGQmd9mOlDXpH3ajg9CrdUyMoaGGCNfWd3F0p0xeSC-EHaG-p5DpWxHKMoUpj0Tn5MOTE8esLr9yivXSPGcFcT8Zt0W1fhXBfMNJd2ZAdr6LHu_6YAFrcQrlHCygZJsiS661Z8E-dJCcOAlXJ8vIrHpNgiVBvnM26d4Lx4FuCl24pAOO8gCY31yrjATYrWWkwAF2Lc5SKyZPTz8thmoY60reQCcyr65_j2o102xDb97CJfgNY_Q-XOTbJhi8SjI7bRkUVNHrY_LDmYKAnDn-hoI0rqMMs_B_Qlxskqb0iT-NrCWwfjzQuUmZZZzA_qWSvfCTvgXHRCr1qg&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Ftwitter.com%2FEmtechGroup&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=2WOvmv9Y0Lzvq02RG3Z0ja31A_lUybIiXoWH3KiSVrU&excomponenttype=Image&signature=ZdHwHOWamTeriiGwZQkorj_q0Jf5wMnXEcCpbn9-7ksQ42KpArdYYUxImp-toDC7D-szrAyTCqhtzxuPhaIvBYS6V3K9rg5PrDnXjuSfq7Dkp-1c-G807YoyaMj4g_JeszTWuK3D39HdQqyEJFeNjbebsbZkIZNQ_HeRP8B5j65dy8EFgaZ_GEaDHBExcwNHWR1KtrvG-_nXLbHdaBMZG0g_08-YU16SB-_SNbjOSAjcLurjAOA3bUebnrho1pdRM9QxKgojjurUtikhJzOF4U2AmuJy9R5W5Zi4DPUyYXOxWenKXU5XNG9EaSwpNrW8GdtmJdr4dDPa74QmkvutRg&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Fwww.facebook.com%2FEmtechGroupUAE&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=xxpwRGSXQVZjUe6yEs6OWWAyPzAys8-GO_ryoy2Szbo&excomponenttype=Image&signature=hKcFAAqWWT77pSr7PD9LfKR3_K5WQDcEP4TGiPzxMQv0tuzPukKwhiBtC3Pa3r-sP92GZI7dLq4HewAVtXuqprjSs66EvuNWL0IzlHnPRRklpyEzecf90WJQ6cZ1uMELAruhGwLJsMz4uUJF2de2dwVj8QqEdVFNtU56UXoeVwUIvc8lzSPcHd2HOqgg8jSUXlz5ipBgjGKl-4evlPK7kIec-vTkYCtMdjClDEkDkinoNH69_0cQCrIHcaucjEhK_GTApBiyg4MRs_F84YGpyQkgETZtTmRBoeI1zrLInpIlJv4hudqHZfgjxqeJ7yD2S7U0e8eyiEOV4hXfMKRW0A&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Fwww.instagram.com%2Femtech_computer%2F&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=ZYV7CcCGplL98Os7qviHjobBskddzXwI7-3gvNsziQ0&excomponenttype=Image&signature=T01eOIIVRfQSS3yTzVynwiPR9-dIhIFpemzW4O3Q0FGkXSEgG7hd2uwdDp3qj_I1_7jfZrZIhjxZQTLsryhHA8Gq3beihaQL0TnxxEEKi3fRy-a0lhXRGaYMekOM6OGxfyEzeZSQQiSH4JV1qKG8NInC6fDv1nhr6zJBkI7_cpuAIMUu1fzNGFI7Y40r4AekGzVNYivMPdTJV3fSCU5h6NF0r1UQ-YiBMo0CeDv5XfhXzkb8NslGOrnv7WULMr25Kc_6z0JlOTSQBuZmCH1FIV8beCv8a0DxtW9xe1WlYMQ9hXFzfEk-iCCOFiU2hEMI4QdZOGHD8fFByrhimTd5Ug&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCabvTjICX1pLwDW6xRz4CJg&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=JrhhLpIaIILzNHnAqflmveZAn2qOF8sK3rI_NxQlKiQ&excomponenttype=Image&signature=Bm8l-H2XsTZdCk8N0zF_LecEkGvypDDTqs-jeLVOjggqA_MkGqkoumAGAz8OLPnqYnxxaEazPRxL0PbtKwUlGx1OaKwLk5Xv1B43QIZQWA7JhAx0Lc9Ulzqyyyuhpc9o_CE-C13aXstpAJIsGH7pBZ6Bau9M4fdKcIYA8Kv5jYhjnALlL2FufbS6ejDyjVkV8KAZxUnBdxv-JwDrZ3erEuPMeEHrlKGbnjBiFuMM8lBGxnEXEWzVXvJX-picRU00hi4vHVpt37ruox238xs-CARgsKurKILg1Dvy_dkKQCDL39XyjF6jQqXQQIkqCW-kx9pjTYxoiwn3-CGncw_VEA&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

UAE | KSA | Bahrain | India

+91 7012979109<tel:+91%207012979109>

 |

***@***.******@***.***>

+971 4 3966233<tel:+971%204%203966233>

 |

emtech.ae<https://uae.content.exclaimer.net/?url=http%3A%2F%2Femtech.ae%2F&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=FptdwVm2-ZDlkOXrJPGQWdlRZER_RdrwWgHnDTzA_WM&excomponenttype=Link&signature=EjURKD_2G37A-jCQxtL95ZVk8Y_JKYxoBzBNV5zafuUT4Gr-tYz4lIEMVfLFupa8Gw-QAi7vBQKqF7tbxsH1JFeTHZMP1i1p_DeAROajk8ZlEC_-t5W8K1hC_E6r4bPu8DT8cA0V5On_RVFlh2O9bYciI__XfXrUQyuZen7Dpp4QNlqeSL0pkRfN5NhY78ytew6TjgyEK19Fyiz_S-P56c21eku-oNFJnOgy7YluHcqJ-tsA8WxTonMc-PJ4HaIGnf-Nw-s2epmMG90KXWkFGqXiCoM4NPpGqXd07cWJuljVYvNRr6Mf_3TZM7WgbNaXTA8Lb_7Qr1v5l4iGb1LMtg&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

***@***.***

celebrating 30 years of technology excellence

***@***.***<https://uae.content.exclaimer.net/?url=https%3A%2F%2Fwww.ispg.ae%2F&tenantid=L9i_ZcZ6Ee6F-WBFvWqIGQ&templateid=b958d698e3e1ee1185fb002248cb613b&excomponentid=EZboKzsa-b0fZZ3oFTu1FjG5jnP3KPb4w6glNL3yRzk&excomponenttype=Image&signature=vX1okL3PqWJvgdVaErom3Z39owTbkFk7OORizoYnXimkqiRDaFjTFAtGyggyY0_di1sjJ9xKJKJHJad9RQ4lJoaP9D8xhYIAUL76sGiXn6HGzq9DLJfHuqF3MJxmVbpd6EKHz42G1MEsk8FjWaapLJpKem4Vv3TWlR4GkOITBX2KE1AgVkVgXRQUt3AypNVATtx_gwLJ_IXYF1QzfrUln5tYjBeDPuYR2rdGt1sXmxxgyqO3JmX4j81QCamAnv1bUOkgCmxympiSBvvfJwbiHhjaVYrcqbVmRw03GCkn27AfzfvE6YpsRoYomkgbLuxKRMNcVUrGiCPBE0NVzkMxYw&v=1&imprintMessageId=99cff285-0e06-4b72-a88c-43e95469e266>

________________________________
