### ISSUE TITLE
[Feature Request] htaccess for web-frontend

### ISSUE THREAD

**Issue by turnschuhadmin1337** [amidaware/tacticalrmm#2100]
Hi there,

thanks a lot for your work!

I was wondering if it's posisble to add a htaccess file before web login, just to have some extra step or security.
Is it possible and if yes where do I have to put it on my server/tactical user? Or will there be any conflict after?

Thanks to all of you!

**Comment by P6g9YHK6** [comment]
Nginx doesn't support .htaccess

**Comment by turnschuhadmin1337** [comment]
Ok, didn't know that. More like apache guy. Thanks and I'll take a look.
