### ISSUE TITLE
Authelia or 3rd party 2fa

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#237]
I prefer a push 2FA App like Duo+Authelia.  For that to work, it probably doesn't require changes to Tactical, it's just not allowed.

I totally understand the need of 2FA but I'm not a big fan of forcing it on people especially since there are better options like Authelia. If 2FA wasn't forced on me, I could use Authelia on nginx and have Duo push, but we're currently not allowed to do that. 

Is there a way so everyone can be happy?

**Comment by dinger1986** [comment]
@bbrendon I think @azulskyknight made a good point about this on discord, are you happy if we close this?

**Comment by bbrendon** [comment]
Not really. Having a single 2FA portal makes things easier. One less time to pull out the phone.

**Comment by bbrendon** [comment]
There is also https://github.com/authelia/authelia/issues/189#issuecomment-832295639

**Comment by dinger1986** [comment]
@sadnub maybe this? https://github.com/pennersr/django-allauth

**Comment by bbrendon** [comment]
This is too old. I don't think this feature request makes sense. Can I close it ? SSO is the way forward.

**Comment by dinger1986** [comment]
Fine by me
