### ISSUE TITLE
Feature Request: Add DNS Robocert to the Docker package

### ISSUE THREAD

**Issue by meyerje** [amidaware/tacticalrmm#264]
If you include https://github.com/adferrand/dnsrobocert in the docker package it will provide automation to the certificate renewals.  It does require a Lexicon DNS host so that API access can be configured for the record generations (https://github.com/AnalogJ/lexicon).

**Comment by unplugged216** [comment]
@meyerje I am wondering if this could be handled with automating updates. At least from the docker perspective. Updates of TacticalRMM are fairly regular. However, for stability, auto updates may not be the best approach. Hmm. 

I have already written a docker upgrade script that also updates cert. Ill see if I can contribute that and possibly integrate this feature request at the same time.
