### ISSUE TITLE
Feature request: View device serial number in the overview tab

### ISSUE THREAD

**Issue by frankemann** [amidaware/tacticalrmm#389]
It would be nice to see the serialnumber in the overview tab.
We often need to find the devices serialnumbers to f.ex check the warranty of the device with a quick copy and paste into the manufactures website.

**Comment by silversword411** [comment]
That data is under Assets | BIOS | SerialNumber
https://github.com/wh1te909/rmmagent/blob/3b070c3fadb1ae4dff8f20196fc721d99a760474/shared/types.go#L558
it's queried WMI data. 

What if there was under Settings | Global Settings a "Custom data on Summary" tab.
Something like (don't judge, probably completely wrong brackets and structure):
`Serial Number: {{ Win32_BIOSEX.SerialNumber:string }}`

Where you could populate whatever WMI data you wanted at the bottom of the Summary screen. Then anyone could add whatever they needed/wanted

**Comment by wh1te909** [comment]
Done, will be in next release:

![hsp8UwhfOQ](https://github.com/amidaware/tacticalrmm/assets/7434746/ac0cd6e2-ea02-42de-80b9-5b697fc6cfab)

**Comment by asasin114** [comment]
This is awesome! Will we be able to use this as a script variable like {{agent.serialnumber}} to inject in a custom URL to, say, pull up the Dell support site right to the device like we were able to with a custom field before??

Reference: https://docs.tacticalrmm.com/functions/examples/

**Comment by wh1te909** [comment]
@asasin114 yes, you can use `{{agent.serial_number}}` https://github.com/amidaware/tacticalrmm/blob/ae5d0b1d81ed7e7ee1f3ebaafaf8a8ad96c8a49a/api/tacticalrmm/agents/models.py#L412
