### ISSUE TITLE
Feature: Possibility to edit reports

### ISSUE THREAD

**Issue by cm-slu** [amidaware/tacticalrmm#412]
One idea for improvement will be to have the possibility of displaying and exporting reports.

For example:
Of all the agents installed, how many are in Windows 7,8,10 ...

Report on the types of processor, ram etc ...

From time to time a software publisher must make decisions to stop supporting certain platforms or make changes to their software and small configurations may no longer overload the new version of the software.

I think all the useful information is already present in the "assets"
sorry for my bad English

**Comment by dinger1986** [comment]
this is dealt with with reporting now
