### ISSUE TITLE
Add counts to all clients and sites

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#426]
Add a right-justified count for every Client (and site) to show total number of machines.

**Comment by silversword411** [comment]
FYI for others: I was used to seeing it in the left tree associated with the name

![2021-06-07_163214 - client count](https://user-images.githubusercontent.com/13395348/121086332-057aba00-c7b1-11eb-8534-b90c20b1c90e.png)

But you can also find it in the bottom-right of the right pane

![2021-06-07_163046 - trmm client count](https://user-images.githubusercontent.com/13395348/121086388-13c8d600-c7b1-11eb-9552-ef3211a64258.png)

**Comment by jacksonsystems** [comment]
This would be handy to have, an automated counter beside each client, as to how many agents are in that client. 

ConnectWise Control does it nicely.

**Comment by jacksonsystems** [comment]
> 

Yes but you have to click the lcient name to be able to see the total count in the bottom right, its nice to be able to glance with no clicks needed from the main Dashboard as to how many agents are in a client.

**Comment by jacksonsystems** [comment]
This sort of thing would be ideal for Admin / Billing

![image](https://user-images.githubusercontent.com/51890084/149955346-0bebf8a4-4b67-42bd-89db-895304bfb7a2.png)

**Comment by jacksonsystems** [comment]
> Here's some tips on needed stuff:
> 
> ```
> {{ props.node.children ? props.node.client.agent_count : props.node.site.agent_count }}
> 
> That's how you get the agent count. Check line ~120 in web/views/Dashboard.vue for the label placement
> Can put it before or after the label
> ```
> 
> I'd try and right-justify like SC if I get to it.

Thanks for all of your hard work... it is very much appreciated.

**Comment by bbrendon** [comment]
I'd vote to close this. Do not want this feature.

**Comment by jacksonsystems** [comment]
I would say it would be better if we have the option to turn it on in User PRefs. Those that don’t want it enable/disable it.




Kind Regards,

Chris Jackson
MD / Systems Engineer
[logo]

01482 935101
***@***.******@***.***>
www.jacksonsystems.co.uk<http://www.jacksonsystems.co.uk/>
[facebook icon]<https://www.facebook.com/JacksonSystemsHull>    [linkedin icon] <https://www.linkedin.com/in/jacksonsystems/>     [instagram icon] <https://www.instagram.com/jacksonsystemshull/>
[banner]
Jackson Systems Limited
359-361 Anlaby Road, Hull, HU3 6AB

**Comment by jacksonsystems** [comment]
> I'd vote to close this. Do not want this feature. Screen space is too valuable. You can also get the info right now by mousing over the site/client.

Good to know about the mouse over thing I did not know about that and I cant see it refrenced in the Docs.

**Comment by wh1te909** [comment]
if we add this then yes it definitely needs to be optional and can turn on/off via user preferences. there is already the mouseover option and you can also get this info by querying the API

**Comment by jacksonsystems** [comment]
> if we add this then yes it definitely needs to be optional and can turn on/off via user preferences. there is already the mouseover option and you can also get this info by querying the API

OK where in the docs is the mousover thing because I did not know it even existed? I cant see it in the docs anywhere. 

Yes Querying API would also work, but tend to use this info on the fly and not neesescarily through anything automated.

**Comment by silversword411** [comment]
> I cant see it in the docs anywhere.

Don't think it's actually stipulated in the docs but leave your mouse over a client/site on the left list and

![2022-01-18_134019 - brave_Tactical_RMM_-_Brave](https://user-images.githubusercontent.com/13395348/149999330-9c7d87dc-b6bc-49d9-81f2-c63950c27aaa.png)

**Comment by jacksonsystems** [comment]
Gotcha! Neat!
