### ISSUE TITLE
Linux and Mac agents

### ISSUE THREAD

**Issue by dinger1986** [amidaware/tacticalrmm#461]
I know it's planned but something a lot of people have commented on so would be a good feature to add.

**Comment by zharding** [comment]
I understand they under development. My curiosity though is where are they in the repos? I would certainly like to contribute if possible.

**Comment by dinger1986** [comment]
I think they are planned rather than underdevelopment. If you want to help or collaborate on this project worth chatting to the devs on discord.

**Comment by silversword411** [comment]
I believe this is a 100 sponsor goal...so keep sponsoring!

**Comment by zharding** [comment]
Has there been any progress? Like I said, I would love to help

**Comment by zharding** [comment]
So,

I decided to fork the [rmmagent](https://github.com/wh1te909/rmmagent) repo and see whats up. I feel there may a bit of work to this. I am really curious if work has been started. if so, may I know where to work? As far as I can tell, this may require a decent amount of adjustment to breakout OS support.

**Comment by silversword411** [comment]
@zharding I doubt work has been started on this yet. As this is a 100 sponsor goal, and I think the current count is half that, and other priorities are reporting and 1-2 other things to try and get to v1 release.

I'm sure if you wanted to build a Linux agent on your own and commit the work it would be welcomed though.

**Comment by wh1te909** [comment]
i'm still experimenting with the design so yes work has been started, not public yet until i finalize the design

**Comment by athornfam2** [comment]
With my feature request being closed for this open request. How far are we on a Linux/Mac agent?

**Comment by dinger1986** [comment]
I'm sure the status is still as above due to other development being carried out

**Comment by bdrayersyno** [comment]
+1 for a Linux client

I can perhaps offer my help, if needed, for the Linux part because Linux is my core competences :-)

**Comment by JSuenram** [comment]
+1

**Comment by plao** [comment]
+1 from my side also :-)

**Comment by wh1te909** [comment]
linux agent is released. mac coming soon

**Comment by Serenfo** [comment]
# github.com/amidaware/rmmagent/agent
agent/agent.go:95:8: undefined: NewAgentConfig
agent/agent.go:209:23: undefined: SetDetached
agent/agent.go:337:14: a.getMeshNodeID undefined (type *Agent has no field or method getMeshNodeID)
agent/agent.go:349:9: cannot assign error to err in multiple assignment
agent/checkin.go:38:14: a.GetServices undefined (type *Agent has no field or method GetServices)
agent/checkin.go:41:14: a.osString undefined (type *Agent has no field or method osString)
agent/checkin.go:42:19: a.SystemRebootRequired undefined (type *Agent has no field or method SystemRebootRequired)
agent/checkin.go:48:19: a.LoggedOnUser undefined (type *Agent has no field or method LoggedOnUser)
agent/checkin.go:60:14: a.GetWMIInfo undefined (type *Agent has no field or method GetWMIInfo)
agent/rpc.go:35:18: undefined: SchedTask
agent/checkin.go:60:14: too many errors

Some error to on freebsd/amd64

**Comment by dinger1986** [comment]
@wh1te909 we can probably close this now

**Comment by wh1te909** [comment]
@dinger1986 yep lol thanks!
