### ISSUE TITLE
Feature Request: SSO integrations

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [amidaware/tacticalrmm#508]
**Is your feature request related to a problem? Please describe.**
this is not a problem.  this is an improvement

**Describe the solution you'd like**
I would like to be able to configure external user authorization.  Imenoo is interested in AzureAD and SSO implementation.

**Comment by dinger1986** [comment]
So the feature request is to use single sign on using AzureAD?

**Comment by AntonAndreevichMoroz** [comment]
Yes.  Exactly.  My request is about AzureAD and SSO.  but I think someone will be interested in authorizing through the local Active Directory or LDAP.

**Comment by dinger1986** [comment]
Ok, have changed the title to reflect this, its up to the devs of course.

I for one am quite happy its not integrated, like having these things separated out.

**Comment by davidrudduck** [comment]
I think SAML / SSO type auth would be a great addition, providing it provides the ability to tie access control to user security groups in the SSO data source.

It makes sense to integrate authentication so we dont end up with a billionty user accounts that need to be provisioned and de-provisioned when staff start and end with our companies.

We leverage LDAP or Azure AD / SAML SSO in everything we can - providing we can still use MFA.

**Comment by subzdev** [comment]
My preference would be Azure/365 before LDAP.

**Comment by FranklinClinton** [comment]
+1 for SAML auth. SSO is a requirement for a lot of organizations.

**Comment by d4-maertzdorf** [comment]
yes please, SSO / MFA with SAML (for AzureAD)

This way you'd still be able to offer MFA, through the MS AzureAD MFA functionality.

**Comment by adamjrberry** [comment]
+1 for LDAP/Azure AD SSO

**Comment by ranomier** [comment]
I fine with oauth/oauth2/openid or saml.

But please don't add ldap first. It's pain.

Thank you and to all have an wonderful day!

**Comment by JSuenram** [comment]
+1 LDAP/Active Directory

**Comment by plao** [comment]
+1 LDAP/Active Directory for me too, thanks

**Comment by swalker234** [comment]
+1 to ldap or AD radius would even be fine

**Comment by jbrouhard98** [comment]
+1 for LDAP/Azure AD SSO for me.   I would also be keen on OAuth or custom Oauth's.

**Comment by netwalker0099** [comment]
+1 for SAML we use a different SSO provider

**Comment by lateTWoIT** [comment]
+1 for SSO of any kind

**Comment by Len-SVACS** [comment]
+1 for SSO. Would be amazing.

**Comment by NathanTarbert** [comment]
SuperTokens wrote about a solution that uses OAuth 2.0 + SAML SSO if anyone wants to check it out? - https://supertokens.com/docs/thirdparty/common-customizations/saml/with-boxyhq/flow-diagram

**Comment by Neeeeeeeeeo** [comment]
+1 for LDAP/Azure AD SSO

**Comment by zebedeeh7** [comment]
+1 for LDAP/AzureAD/SAML (Authelia would be cool too)

**Comment by josvink66** [comment]
+1 for Azure AD SSO

**Comment by topdarkstar** [comment]
+1 for LDAP/AzureAD/OAuth/SAML

**Comment by c74infrateam** [comment]
+1 for LDAP/AzureAD/OAuth/SAML - this is important for our processes

**Comment by Henrique-Batista** [comment]
+1 for LDAP/AzureAD/OAuth/SAML

**Comment by axidnt** [comment]
+1 for LDAP/AzureAD/OAuth/SAML

**Comment by bbrendon** [comment]
@wh1te909 can we lock this issue? I think we've seen enough spammers.

**Comment by wh1te909** [comment]
@bbrendon done. yes we'll eventually implement SSO but focusing on other features atm.

**Comment by wh1te909** [comment]
SSO support has just been released in 0.20.0: https://docs.tacticalrmm.com/ee/sso/sso/
