### ISSUE TITLE
[features request] personalize column and report

### ISSUE THREAD

**Issue by Sedlise** [amidaware/tacticalrmm#523]
Hi,

can we personnalize column to add for example serial number to the principal view?

is it possible to create some csv report (cllient, site, hostname, ..)? or personalize report

thanks a lot

**Comment by johnnyq** [comment]
+1 Some Good customization could be Make Model, Serial, OS, Public IP, LAN IP, MAC Address would all be good column customization options

**Comment by bbrendon** [comment]
@johnnyq I think git edicate is to not +1 but to use emojis. I just received qty 3 "+1" emails from you.

**Comment by johnnyq** [comment]
@bbrendon good call +1s are not very helpful i'll stick with the thumbs up emoji and add helpful messages. I will remove those +1s

**Comment by bernardolankheet** [comment]
This is a simple powershell script that can serve to export the assets of all agents in csv via API.

https://github.com/bernardolankheet/TacticalRMM-Extras/blob/main/Scripts/Maintenence/RMM-report-assets-agents-csv.ps1

**Comment by silversword411** [comment]
Merge with https://github.com/amidaware/tacticalrmm/issues/308
