### ISSUE TITLE
Feature request: run patch installation ASAP after a scheduled patch installation is missed

### ISSUE THREAD

**Issue by zimmer-service** [amidaware/tacticalrmm#532]
**Is your feature request related to a problem? Please describe.**
I have workstations that are just sporadically online, so that it is not possible to find a time when the scheduled patch installation should run. That is why approved patches are never automaticaly installed on those machines.

**Describe the solution you'd like**
Run the patch installation ASAP if the scheduled patch installation time is missed.
Maybe one could set a flag for offline agents when the scheduled patch installation time is reached and consider it when the agent is back online.

**Comment by johnnyq** [comment]
+1

**Comment by RichardBurt65** [comment]
Any update on this? It really needs this enhancement.

**Comment by dinger1986** [comment]
The devs have been working very hard on various features and bugs and will get to patching.

Some have had bounties on them, feel free to contact support via https://support.amidaware.com if you would like to contribute to a bounty for this or any other feature which is really needed.

**Comment by silversword411** [comment]
This is a dupe and integrated into the Windows update rework. 
https://github.com/amidaware/tacticalrmm/issues/1188

Closing
