### ISSUE TITLE
Small UI tweaks

### ISSUE THREAD

**Issue by affarinha** [amidaware/tacticalrmm#583]
**Is your feature request related to a problem? Please describe.**
No. Those are only a few simple suggestions for improving UI (in my opinion).

**Describe the solution you'd like**
1. **Checks and Agent Status Icons** - Yellow and Green Icons are very similar and sometimes is hard to tell them apart. I'd suggest a lighter yellow and darker green in order to better differentiate them;
2. **Summary tab > Hardware Details** - Group the processors. Instead of printing 8 lines like "Intel(R) Xeon(R) CPU E5630 @ 2.53GHz", print one line only with "8x Intel(R) Xeon(R) CPU E5630 @ 2.53GHz"
3. **Summary tab** - would it be possible to add somewhere a table with "Custom Fields"? Perhaps at the right of the "Disks" column. This table could also be shown when no agents are selected to display the Site/Customer's Custom Fields.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by wh1te909** [comment]
3. was added a few releases ago (custom fields now show up in summary tab). 1. will be added in next release (can change all icon colors)

**Comment by wh1te909** [comment]
added 2. will be in next release

**Comment by affarinha** [comment]
Regarding #2, it seems processor count is not working for Hyper-V VM's.

- Physical machines (including Hyper-V hosts): 
![image](https://github.com/amidaware/tacticalrmm/assets/84356971/70a4e8a2-8886-44a0-b974-b7bed010bc6e)

- VMware VM:
![image](https://github.com/amidaware/tacticalrmm/assets/84356971/d18933f9-d9f9-446e-a184-184aea313349)

- Hyper-V VM (VM has 4 vCPU):
![image](https://github.com/amidaware/tacticalrmm/assets/84356971/885c1d69-8377-4992-8a58-9063a1511832)
