### ISSUE TITLE
Add serialnumber and other data to Summary Tab

### ISSUE THREAD

**Issue by frankemann** [amidaware/tacticalrmm#605]
Would be great to have the device serialnumber on the Summary Tab.

**Comment by johnnyq** [comment]
Good recommendation @frankemann 
I would like to add as well as the connected interface's mac address 
and if possible if connected to WiFi show the connected WiFi network name 
and possibly WiFi Signal.

**Comment by silversword411** [comment]
I think there have been several discussions about enhancing the "Summary" tab and giving some options at user customization.  All the data here is basically pulled from 

Till then, you have to dig, but the SN is under Assets > Motherboard > SerialNumber:

There's a lot of info in the Assets tab...you just have to dig a bit ;) And if there's something you can't find in there and it's a WMI class it can be easily added: https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page

**Comment by silversword411** [comment]
@frankemann this is the 3rd time you've opened issues with the summary screen customization feature request. Please search existing issues, and stop posting duplicates.

**Comment by jacksonsystems** [comment]
I think it would be A good idea to be able to add 'buttons' to the summary page of agent, admin of TRMM to be able to set what these buttons do. Possibility to set one to drop into Mesh, and the other to a URL Action.

Would be nice to be able to fully customize the Summary page as well to be able to add links to Documentation and such like.

To be able to have quick glances at important information on Sumamry would be good, Versions of Windows etc but this should all be fully customizable by the Admin. 

Thanks

**Comment by wh1te909** [comment]
serial number now shows up in the summary tab. custom fields now show up as well in the summary tab, so you can write collector scripts to populate custom field data and have them show up in the summary tab
