### ISSUE TITLE
Enhanced agent search

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#652]
Related kind of to: https://github.com/wh1te909/tacticalrmm/issues/650

Right now, you can't search by the detailed data in systems.
Items to include in the "search" box (maybe only after enabling an "advanced search" checkbox) might include:
Public IP
Private IP
Hardware Details (PC Model)
Processor type (finding older machines/BIOS firmware flash requirements)
HDD Model (firmware updates required for x HDD type)
OS (Windows 7/10/11)
OS "Version" eg 10.0.19043
Not sure if you could have a search structure to be able to query a specific wmi data field in the assets tab:
Assets-Operating System-Organization: HP (searches for all agents with the data field matching that)
or Assets-Disks-Model: "KXG50ZNV256G TOSHIBA"
kind of thing

**Comment by bradhawkins85** [comment]
Could this also be related to #553 
Would be great if these sorts of things could be included in the "Session Group" searches as well.

**Comment by silversword411** [comment]
That looks too easy...even I might be able to put the kitchen sink in there now! LOL

How hard would it be to have an "advanced" checkbox so we could list a ton of fields...that would probably slow search. Hence it wouldn't be searched by default (probably result in too many matches as well)
