### ISSUE TITLE
Multiple patch policies per client / site / agent / automation policy

### ISSUE THREAD

**Issue by mctaguma** [amidaware/tacticalrmm#665]
**Is your feature request related to a problem? Please describe.**

The problem I see is that critical and low priority patching has to be added to the same automation policy and scheduled the same, for each client / site / agent.
I would prefer to run critical patching daily, and run low priority patching monthly.

**Describe the solution you'd like**

When assigning patch policies to an agent, site, client, or automation policy, it would be helpful to be able to assign multiple patch policies.
An example would be the following patch policies for a single automation policy:
- Critical daily patching
- Important weekly patching
- Low priority monthly patching

For example, in a 24 / 7 health scenario, we need agents split into A and B categories (we currently use the sites feature for this), then we would like to assign multiple patch policies to each of these sites. This ensures that one site (half the critical agents) are always available.
As an example, we could then schedule:
- Critical patching for the A site daily at midnight, and the B site daily at 2am
- Low priority patching for the A site monthly on the 20th day at 1am, and the B site monthly on the 27th day at 1am

**Describe alternatives you've considered**

The best current method appears to be weekly patching of critical and important patches, with any low priority patching completed manually using the "Bulk Patch Management" feature.

**Additional context**

**Comment by mctaguma** [comment]
Apologies, partial duplicate of #427

**Comment by silversword411** [comment]
Closing as dupe
