### ISSUE TITLE
SSL expiring soon indicator

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#722]
Similar to the "update available" in the top left of admin panel have an SSL expiring icon that appears.

Yellow @ 2 weeks
Red @ 1 week

**Comment by dinger1986** [comment]
Mesh already warns about it about a week before and would show up when you remote connection a computer

**Comment by r3die** [comment]
This enhancement would still be good, especially if you utilize a 3rd Party platform for remote connectivity

**Comment by bbrendon** [comment]
This seems a lot like https://github.com/wh1te909/tacticalrmm/issues/643
Close?

**Comment by silversword411** [comment]
> Mesh already warns about it about a week before and would show up when you remote connection a computer

As a screenconnect user, I'm rarely in native mesh...never seen this message (of course I may be a little too proactive on cert renewals 😉)

Does that error appear in the native TRMM dialogs, or only if you manually login to the mesh console/interface?

**Comment by silversword411** [comment]
> This seems a lot like https://github.com/wh1te909/tacticalrmm/issues/643
> Close?

Definitely could be. Or not. It's in the hands of the Dev's. Just suggesting improvements to the project.

**Comment by silversword411** [comment]
Looks like this is a feature of mesh

![Screenshot_20210925-110328.png](https://user-images.githubusercontent.com/13395348/134776064-38d21868-0b43-4ed5-b2d5-866ecf2fffa0.png)

**Comment by wh1te909** [comment]
done, will be in next release. given how many people forget to renew certs and so many issues are related to expired certs, i'll make an exception for this one and have added a small indicator when certs are close to expiring.
