### ISSUE TITLE
Agent Automatically Disables Windows Update

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#742]
Create setting under Settings | Global Settings | General

- [x] Disable Windows Automatic Updates during Agent Installation

I think this was already planned by @wh1te909 just adding it to issue tracking so we don't forget :)

**Comment by sadnub** [comment]
Might be easier with a script check that checks the registry key for the value and an automated task that changes it. Gives you full control and visibility into what ones you want auto updates disabled on and which ones are having issues and need remediation.

I can also see existing GPOs toggling the setting back which would go undetected if it is just a one-time change.

**Comment by silversword411** [comment]
There is a script that will reverse agent registry changes if someone needs: 
https://github.com/wh1te909/tacticalrmm/blob/develop/scripts_wip/Win_Windows_Update_RevertToDefault.ps1

**Comment by silversword411** [comment]
Ticket Consolidation: Combining into https://github.com/amidaware/tacticalrmm/issues/1188
