### ISSUE TITLE
Agent error

### ISSUE THREAD

**Issue by rwcloudridgeworks** [amidaware/tacticalrmm#749]
after installing on a server it appears in the dashboard, 5 mins later goes red , looked at the server and services getting the error below when trying to manually restart the service

![image](https://user-images.githubusercontent.com/62990713/136406236-9f42976d-9a45-450d-ba6b-70a88f3b6d97.png)

**Comment by dinger1986** [comment]
need to start giving more information like client etc. Also best to get support on discord

**Comment by rwcloudridgeworks** [comment]
Hi sorry it’s server 2012 patched , we have other ones on sale working fine ,

**Comment by wh1te909** [comment]
I have seen this error before when AV nukes the exe. I would check in program files\TacticalAgent and I bet you the tacticalrmm.exe isn't even there
