### ISSUE TITLE
Execution Time of Scheduled Tasks

### ISSUE THREAD

**Issue by rjusher** [amidaware/tacticalrmm#756]
Hi,

I have been testing TactialRMM to move away from Pulseway, so far it has fulfilled all the requirements, but I am finding the following issue.

For me it is necessary to run tasks at specific times, for this purpose I created a Policy where I scheduled the tasks I need to run. The problem I have been finding is that the tasks don't execute at the specified times. A proof of that is the following screenshot.

![image](https://user-images.githubusercontent.com/3855349/136801736-7deb263b-42e6-481a-87c6-6f7553ee2d39.png)

I don't know if it is a Time Zone issue (I don't think it is and I ensured that the machines have the correct time zone).

I verified that the task on the Task Scheduler on the server has everything synced right. To me it seems that way. Here are some screenshots of what I think validates this.

![image](https://user-images.githubusercontent.com/3855349/136802417-51878eff-4f52-4152-96a9-ef44434a956c.png)

![image](https://user-images.githubusercontent.com/3855349/136802589-53937347-92af-4ba4-82c2-976d022c2ca8.png)

I don't know if I am missing some configuration to ensure that the tasks gets executed at the right time, or I don't understand how Task Scheduling is handled in TacticalRMM. 

But I need to ensure that these tasks execute at the scheduled times. Specifically the one that Reboots the server at 3:30AM.

**Comment by sadnub** [comment]
Would the machines be offline potentially when they are supposed to run? The scheduled task needs access to the dashboard in order to pull the correct script to run and save the results.

**Comment by rjusher** [comment]
Thank you @wh1te909.

To set the TZ globally from TRMM's web UI. 

Is the following setting the right one?

![image](https://user-images.githubusercontent.com/3855349/136830622-f81f0b71-e825-4a89-be00-56c1aba33985.png)

Am I missing some other setting I have to set to have it configured correctly?

**Comment by sadnub** [comment]
datetimes in the dashboard will be converted to the local browsers timezone. This should fix the time appearing to be off
