### ISSUE TITLE
History items give blank screen if client not online at time of script run

### ISSUE THREAD

**Issue by silversword411** [amidaware/tacticalrmm#759]
If you run a script on an offline agent (using bulk script, or manually) a history of the event is created under the Agent | History tab, but clicking on it results in a blank screen (you can hit <esc> to clear the empty page). 

Should there even be a history log if something doesn't run? (when we get to the point of scripts getting scheduled with the "pending actions" function the log should only write after run on client)

**Comment by silversword411** [comment]
@sadnub If you have long-running scripts there are history entries created at start of script trigger, but are blank until the script finishes and returns data. Only then is the output populated with data.

How is this going to be affected when the new feature of all script runs will be scheduled for offline agents? I don't think there's an official issue for that yet is there?

**Comment by silversword411** [comment]
It's been working, but doesn't seem like an ideal implementation.

If the history entry was set first as
`date/time: Execution on agent started`

And then return data was added to/replaced that when it worked successfully and you could track/troubleshoot the process if it broke (agent offlines/nats problem) before data is returned.

I think this may also require agent changes.

**Comment by wh1te909** [comment]
this has been resolved in a recent release, now when clicking on Output you'll get an error that the script is still awaiting it's initial run
