### ISSUE TITLE
Help: Install in LAN without DNS

### ISSUE THREAD

**Issue by ThanosAntmanEntrance** [amidaware/tacticalrmm#760]
Hey Guys, 
i want to know, is there a simple way to install tacticalrmm in LAN without a dns-server.
My "DNS-Server" is my router and i cant create records on the router.

Cheers

**Comment by dinger1986** [comment]
please follow the docs, they state clearly that you have to use a real domain, you dont have to open ports as it uses TXT records to get the DNS

https://wh1te909.github.io/tacticalrmm/install_server/
