### ISSUE TITLE
Enhancement: Bulk Patch Management- Target Automation Policy

### ISSUE THREAD

**Issue by r3die** [amidaware/tacticalrmm#776]
**Is your feature request related to a problem? Please describe.**
Feature Request/Enhancement, Have like devices across multiple clients/sites under automation policies- currently need to select individual agents under 'Choose Target'

**Describe the solution you'd like**
Under 'Choose Target' on the Patch Management Window have the ability to select an Automation Policy that way all agents under that policy could either be scanned or installed.

Additionally, It would be nice to be able to manually approve/deny individual updates for the entire Automation Policy

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/89989185/140084149-f41787dc-336a-4557-baec-c39969f171ea.png)

**Comment by silversword411** [comment]
Ticket Consolidation: Combining into https://github.com/amidaware/tacticalrmm/issues/1188
