### ISSUE TITLE
[Ping check] A message sent on a datagram socket was larger than the internal message buffer

### ISSUE THREAD

**Issue by NiceGuyIT** [amidaware/tacticalrmm#812]
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Chrome Version 95.0.4638.69  (64-bit)
 - RMM Version (as shown in top left of web UI): 0.10.1

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v1.7.0
- Agent OS: Windows Server 2012 R2 Std.

**Describe the bug**
Occasionally receiving this error during a ping check. Pinging the destination shows the destination manually works.

```text
read ip4 0.0.0.0: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
```

**To Reproduce**
1. Create a ping test.
2. Verify ping results are shown in the UI.
3. Shut down the destination machine to make it "unreachable". The error happens sporadically when the machine is up. Shutting it down is only to reproduce the problem.
4. Check the ping results.

**Expected behavior**
I expect the ping results to work if the host is up.

**Screenshots**
![image](https://user-images.githubusercontent.com/7763429/142736319-1d9ae93b-7256-4dd2-be20-a646d3fec8d6.png)
![image](https://user-images.githubusercontent.com/7763429/142736331-57032560-2707-46d2-98a5-b613af994bc8.png)

**Additional context**
_I'm opening this on behalf of some Discord users._

5am79 and Hugo on [Discord](https://discord.com/channels/736478043522072608/744281869499105290/911661984439730187) had an error message exactly like [issue #168 for go-ping/ping](https://github.com/go-ping/ping/issues/168). The [rmmagent](https://github.com/wh1te909/rmmagent/blob/3b070c3fadb1ae4dff8f20196fc721d99a760474/agent/checks_windows.go#L386) code uses exec but I understand the rmmagent repo is not up to date. It's possible it uses go-ping/ping for ping.

**Comment by dinger1986** [comment]
Also an error I have seen, however haven't reported as it clears the next time the check runs

**Comment by wh1te909** [comment]
yes we are using the go-ping library now. so until that issue you linked is fixed I would recommend just creating your own ping script check

**Comment by wh1te909** [comment]
here a script check you can add that functions similar to a ping check:
```python
import subprocess
import sys

if len(sys.argv) != 2:
    print("ERROR: Missing hostname or ip argument")
    sys.exit(1)

cmd = ["ping.exe", sys.argv[1], "-n", "5"]

r = subprocess.run(cmd, capture_output=True)

success = ["Reply", "bytes", "time", "TTL"]

print(r.stdout.decode())

if all (i in r.stdout.decode() for i in success):
    sys.exit(0)

sys.exit(1)
```

**Comment by silversword411** [comment]
For those that can't read python....that's python 😉
