### ISSUE TITLE
Problem with Patches Duplicates on Windows Portuguese Brazilian

### ISSUE THREAD

**Issue by guilhermejucoski** [amidaware/tacticalrmm#820]
**Server Info (please complete the following information):**
 - OS: Debian 11
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): v0.10.2

**Installation Method:**
  - [ X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): Agent v1.7.0
- Agent OS: Windows 10 PRO

**Describe the bug**
Hello

I believe that because I have Windows with Brazilian Portuguese language in the Patch part, KB2267602 appears duplicated.

I tried to follow the colleague's procedure: https://github.com/wh1te909/tacticalrmm/issues/647

But to no avail

**To Reproduce**
Go to patch tab

**Expected behavior**
That there was a way to remove these duplicate updates, I've tried to have it installed but it never disappears and this happens in all windows in Portuguese... in English it's ok.

**Screenshots**
<img width="1514" alt="Captura de Tela 2021-11-23 às 15 48 28" src="https://user-images.githubusercontent.com/30603026/143086056-1f327d7a-dffa-4f1c-b760-9f57aba30cd1.png">

**Comment by silversword411** [comment]
Probably related to https://github.com/amidaware/tacticalrmm/issues/647

**Comment by wh1te909** [comment]
fixed in latest release
