### ISSUE TITLE
Windows 10 is displayed on the Summary page despite Windows 11

### ISSUE THREAD

**Issue by MalteKiefer** [amidaware/tacticalrmm#892]
**Server Info (please complete the following information):**
 - OS: Debian
 - Browser: Edge
 - RMM Version (as shown in top left of web UI): 0.10.5

**Installation Method:**
  - [ ] Standard
  - [X] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.7.2
- Agent OS: Windows 11

**Describe the bug**
Windows 10 is displayed on the Summary page despite Windows 11.
The overview page shows Windows 10, whereas the assets page sees Windows 11

<img width="461" alt="image" src="https://user-images.githubusercontent.com/59220985/147073202-8aa5c2bf-13f2-488e-8bed-255b4ed64c18.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/59220985/147073271-faa28db4-45cd-4b80-8977-d0b372f30ce2.png">

**Comment by dinger1986** [comment]
Microsoft themselves list it as Windows 10 21H2, 

https://thewincentral.com/microsoft-still-refers-windows-11-as-21h2-update-officially/

**Comment by silversword411** [comment]
Probably going to have to jerryrig it like Microsoft does ;)

**Comment by ninjamonkey198206** [comment]
Can you pull the os build number? If I remember correctly, windows 11 bumps it to 22xxx or something like that.

Ah, found a link.

https://docs.microsoft.com/answers/questions/605991/how-to-differentiate-between-windows-10-and-window.html

**Comment by wh1te909** [comment]
fixed in 0.14.1
