### ISSUE TITLE
escaping issue with custom field string replacement

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#918]
**Describe the bug**

Puting a custom field with a value like `asdf\basdf` and passing that custom field to a power shell script as a parameter you get output like:
![image](https://user-images.githubusercontent.com/6364477/148306409-fd576d5e-e699-414f-9875-9477e531bf47.png)

BUT
If you don't use a custom field, and just enter it as a parameter to a power shell script, the `\b` doesn't corrupt.

I'm thinking this is fixable? Seems like it should be.

Create a Simple powershell script in tactical:
```
param ($MYARG) 
Write-Host "MYARG PARAM: $MYARG"

```

call it with Args : `-MYARG asdf\basdf`
...Which should work.

Put `asdf\basdf` into custom field
call script with arg: `-MYARG {{agent.FIELD}}

You should get the corrupt output.

**Comment by sadnub** [comment]
Any text in custom fields must be escaped manually. This will break other properties like newlines, tabs, etc if I escape all backslashes. It will also break existing functionality if someone is already escaping output.
