### ISSUE TITLE
Add a copy button to assets

### ISSUE THREAD

**Issue by gurizz** [amidaware/tacticalrmm#931]
**Is your feature request related to a problem? Please describe.**
No so much a problem, it's just difficult to see where the text I'm highlighting is

**Describe the solution you'd like**
I'd like a copy button on the assets tab for things like Serial Numbers, Hostnames, Model numbers etc

**Describe alternatives you've considered**
Possibly a right click context menu to do the same,

**Comment by jacksonsystems** [comment]
I would add to this and add a copy button to the left of 'Pop Out', with the agents unique URL so this can then be added to Documentation/Tickets for going straight to that agent from external source.

**Comment by wh1te909** [comment]
@gurizz this was added a while back, each item in the assets tab now has a copy to clipboard button next to it
@jacksonsystems please open new ticket for your request if still needed
