### ISSUE TITLE
Feature - Group Policy Editor

### ISSUE THREAD

**Issue by johnnyq** [amidaware/tacticalrmm#973]
**Is your feature request related to a problem? Please describe.**
Instead of using active directory it would be nice to set policies through tactical RMM like we would with gpedit.msc on a local machine and see what policies are active and such.

**Describe the solution you'd like**
Group Policies

**Describe alternatives you've considered**
Using Task Manager and scripts to set certain things but that's not what task manager is for, and doesn't handle the same way as the group policy manager would

**Additional context**
I would keep the policies to the most common as there are so many of them. One we use a lot is Block Microsoft Account Additions and Sign ins

**Comment by dinger1986** [comment]
This can be achieved via scripts setting registry entries so would possibly be more a community scripts request than feature, however a management interface for it would be a feature request.

I feel a nice to have but not necessary with scripts being so easy to write and practically all the info available online.

Shall leave open for devs but my suggestion would be to close.

**Comment by johnnyq** [comment]
@dinger1986 I see I guess that will work im not much of a powershell script writer but I should learn I just wish there was more scripts to choose from

**Comment by dinger1986** [comment]
There's loads of them about, for group policies this is a good template: https://github.com/amidaware/community-scripts/commit/f9c05af56a9b81cb3a667abd9061042c22ba9b1c

As most will be registry edits.

Happy to chat on discord and help get some done up if you get a chance or have a feature request list.

**Comment by silversword411** [comment]
There's a couple wish list items. Live registry editor (like files), group policy is basically a gui registry editor for specific features.

**Comment by johnnyq** [comment]
Okay thank you @dinger1986 and @silversword411 This can be closed

**Comment by silversword411** [comment]
I'll leave it open as a feature request, if we get to a native registry editor at some point then we'll bundle and close till then....#Wishlist :)

**Comment by dinger1986** [comment]
I think this could be closed, maybe we just need to write up something in the docs and link to those 2 links I shared in here
